LSP11SocialRecovery contracts
lukso-network/lsp-smart-contracts pull request #114
Opened 2022-02-25 14:24 UTC by YamenMerhi

# Description
- [x] Add **LSP11SocialRecovery** contract
- [x] Add LSP11SocialRecovery tests 
- [x] Edit functions visibility in **ERC725Utils** to be used in other libraries 
- [x] Add `setupPermission(..)`  function in **LSP6Utils**
- [x] Add **fixtures.ts** to avoid code duplication across tests 

Note: This is the first draft of the contract and it's very likely to be changed after internal discussion

2022-02-25 16:48 UTC, CJ42 reviewed
added comments

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecovery.sol
> +        address _account,
Wouldn't it be better to use the interface type, instead of an `address` as argument?
```suggestion
        ERC725 _account,
```

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecovery.sol
> +        _registerInterface(_INTERFACEID_LSP11);
Since the contract implements only one interface, it might be easier and cheaper that it inherit from a plain `ERC165` contract. See the one from OZ here -> https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/introspection/ERC165.sol

So we could write a `supportsInterface(...)` function inside the Core contract:

```solidity
    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 _interfaceId) public view virtual override returns (bool) {
        return _interfaceId == _INTERFACEID_LSP11 ||
            super.supportsInterface(_interfaceId);
    }
```

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +import "@openzeppelin/contracts/utils/introspection/ERC165Storage.sol";
Maybe putting `@erc725` import first, and then `@openzeppelin` second?

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11Constants.sol
> +bytes4 constant _INTERFACEID_LSP11 = 0x65c8d0e5;
It might be a bit overkill to have one file for just one constant.
Putting this constant directly above the Core contract in the `LSP11SocialRecoveryCore` should be enough in my opinion.

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +    bytes32 private _secretHash;
Was not sure about the order of variables based on the visibility.
So did a quick research.
Based on:

- what is said in the Solidity docs (although about **functions**): https://docs.soliditylang.org/en/v0.8.12/style-guide.html#order-of-functions
- these two contracts from `@openzeppeling/contracts`:
    - https://github.com/OpenZeppelin/openzeppelin-contracts/blob/abdb20a6bdb1700d58ea9e01b7471dafdef52a68/contracts/governance/TimelockController.sol#L24-L27
    - https://github.com/OpenZeppelin/openzeppelin-contracts/blob/abdb20a6bdb1700d58ea9e01b7471dafdef52a68/contracts/governance/Governor.sol#L32-L50
    
`public` state variables should be first.
`private` and `internal` state variables should go next.

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +    uint256 public recoverThreshold;
Would it be relevant to have some of these `public` getter defined in the interface too?
Maybe not all, but some that might be relevant across implementations.

So defined as follow `ILSP11SocialRecovery`:

```solidity
contract ILSP11SocialRecovery {

    // The number of recovery attempt
    function recoverCounter() external view returns (uint256);

    // The minimum number of votes that an address should get
    // to be granted the owner permissions in the ERC725 contract
    function recoverThreshold() external view returns (uint256);

     // The current number of the guardians
    function guardiansNumber() external view returns (uint256);

    ...

}

```

2022-02-25 16:48 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +    uint256 public recoverCounter;
Is it safe to make the counter `public`?

2022-02-28 08:54 UTC, YamenMerhi commented on contracts/LSP11SocialRecovery/LSP11SocialRecovery.sol
> +        address _account,
Absolutely, let's do it also in LSP6.

2022-02-28 08:55 UTC, YamenMerhi commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +    uint256 public recoverThreshold;
Good idea, to discuss

2022-02-28 08:55 UTC, YamenMerhi commented on contracts/LSP11SocialRecovery/LSP11SocialRecoveryCore.sol
> +    uint256 public recoverCounter;
To discuss

2022-02-28 09:08 UTC, CJ42 commented on contracts/LSP11SocialRecovery/LSP11SocialRecovery.sol
> +        address _account,
Only thing about this is that like LSP6, it should be possible to attach this contract to an LSP8 NFT (as mentioned by @frozeman). But an LSP8 uses on ERC725Y (not the full ERC725 with both X + Y).

The contract type parameter might not then be possible in achieving this goal. So instead, maybe we should check that the `address` passed in the constructor implements **either ERC725X or ERC725Y**.

```solidity
constructor(
        address newOwner,
        address _account,
        uint256 newThreshold
    ) {
        require(
            ERC165Lib.supportsInterface(_account, _INTERFACEID_ERC725X) ||
            ERC165Lib.supportsInterface(_account, _INTERFACEID, ERC725Y),
            "linked account is not an ERC725 X or Y contract"
        );
    
        // not sure then what this assignment should look like?
        account = ERC725(_account);

        if (newOwner != owner()) {
            OwnableUnset.initOwner(newOwner);
        }

        recoverThreshold = newThreshold;
        _registerInterface(_INTERFACEID_LSP11);
    }
```

@frozeman @YamenMerhi let me know your thoughts :)

2022-02-28 09:13 UTC, YamenMerhi commented on contracts/LSP11SocialRecovery/LSP11SocialRecovery.sol
> +        address _account,
Ah yeah, or we could put the type as ERC725Y instead of checking the interface, in this way we allow profiles/tokens

2022-02-28 09:29 UTC, YamenMerhi commented on contracts/LSP11SocialRecovery/LSP11Constants.sol
> +bytes4 constant _INTERFACEID_LSP11 = 0x65c8d0e5;
To discuss

2022-03-16 15:22 UTC, CJ42 reviewed
added comments

2022-03-16 15:22 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +            hex"14a6e293",
Maybe it would be better for readability to use `setData.selector`?  (or in case the functions signatures / selectors in the `IERC725Y` interface change).

```suggestion
           IERC725Y.setData.selector
```

Or since we are potentially thinking to use function overloading for `setData(...)` in ERC725Y, we could use:

```solidity
bytes memory payload = abi.encodeWithSignature(
    "setData(bytes32[],bytes[])",
    keys,
    values
);
```

2022-03-21 13:35 UTC, CJ42 approved these changes

2022-07-25 14:41 UTC, CJ42 requested changes
@YamenMerhi added some comments.

Let's not forget to also add the tests for LSP11 to run in the CI!
Both in `package.json` + in the CI workflow.

2022-07-25 14:41 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(keccak256(abi.encodePacked(plainSecret)) == _secretHash, "Wrong secret");
why not putting this `require` statement at the beginning as the first line to run in the function?

2022-07-25 14:41 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +    function setupPermissions(
We should also rename this function. `setupPermissions` is very generic, and does not describe what is happening.
Also IMO the word `setup` implies an interaction is happening, while it's not the case.

The function only create key-value pairs and return them:
- create the key-value pair for the permission array length with value as previous length +1
- create the key-value pair of the address of the new controller for the permission array index
- create the key-value pair of the permissions of the new controller address

I really like this function tho. It's super useful and powerful. It does a good part of the heavy lifting job and devs will definitely re-use this kind of library function in the future 😃 💪 

Any ideas of the naming? A long name is not too much of a problem, but should read and be understandable when reading in an implementation.

2022-07-25 14:53 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +    function setupPermissions(
@YamenMerhi @skimaharvey here are my suggestion of function renaming:

```solidity
function createPermissionsKeysForController(
        IERC725Y account,
        address controller,
        bytes memory permissions
    ) internal view returns (bytes32[] memory permissionsKeys, bytes[] memory permissionsValues) {
```

2022-07-25 15:40 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +    function setupPermissions(
Agreed, since the length of function has no effect on gas, I think it makes more sense calling it this way even though it is long

2022-07-26 05:21 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +    address public override account;
I think we should update to 0.8.10 and above. Prior 0.8.10 version, compiler was adding extra codes (including `EXTCODESIZE` which is expensive). Since then, it is not adding these codes when return data is expected. We make quite a lot of external calls, may be a good idea to think about it? Wdut? 
https://github.com/ethereum/solidity/releases/tag/v0.8.10

2022-07-26 07:06 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        }
Nice I think if we want to optimise even more we could do:
```
        unchecked {
            for (uint256 i = 0; i < guardiansLength; ) {
                if (
                    _guardiansVotes[recoverCounter][recoverProcessId][_guardians.at(i)] ==
                    msg.sender
                ) {
                    ++senderVotes;
                }
                ++i 
            }
        }
```

2022-07-26 07:28 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(!_guardians.contains(newGuardian), "Provided address is already a guardian");
if we dont we probably would need to reduce the length of the error's message as it is > 32 bytes

2022-07-26 09:04 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        }
I think it will be too much, IMO readability > gas opt @CJ42 opinion ?

2022-07-26 09:29 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        address keyManager = ERC725(account).owner();
Actually, I have a different opinion. 

First, deploying and setting up the social recovery contract could be done before having the key manager as owner, this will reduce the cost of mapping every transaction through the key Manager. 

Second, If we made this check in the constructor and removed the check in the `recoverOwnership(...)`, we will have a problem, because let's say we made the check in the constructor and at that time the erc725 contract was owned by LSP6KeyManager but then after a while, the owner changed to an EOA, then while executing the `recoverOwnership(...)` and because we don't have a check for the owner that it supports LSP6, then the transaction will be executed on an EOA successfully and we will not have a revert error and this is wrong ❌ .

That's why IMO it doesn't matter who is the owner of the linked account on the deployment, it matters when we are recovering and the check should be there to ensure 100% that the owner of the linked account support LSP6.

Let's discuss @CJ42 @skimaharvey 🚀

2022-07-26 09:44 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(keccak256(abi.encodePacked(plainSecret)) == _secretHash, "Wrong secret");
The place of the `require` statement was intended to be last because it's the last thing that should be checked.

Although it's a fragile security improvement, you should not reveal that the `plainSecret` is right and the error is coming from the threshold, otherwise, malicious guardians will be knowing your plainSecret and now can vote to recover on another processId and take over your account since they will know the plainSecret.

Example: Let's say you are recovering and you provided the right secret word and you didn't reach the threshold yet.

Using current code, the call will revert and say that you didn't reach the threshold, and the guardians will not know that the plainSecret is right or not because the check of plainSecret is after the check of the threshold. (Even if they can check that the plainSecret is right or not in a manual way)

Using your suggestion, the call will revert and say that you didn't reach the threshold, but at this stage since it's reverting at this line of code, that means that it passed the check of the `plainSecret`, which could be a little bit more dangerous.

Let's discuss @CJ42 @skimaharvey 🚀

2022-07-26 10:17 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +    address public override account;
Yep let's discuss this later. Added a note in Notion

2022-07-26 10:32 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/ILSP11BasicSocialRecovery.sol
> +     * @dev Adds a guardian of the owner
Guardian of the owner, the owner is the linked account.

2022-07-26 10:36 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/ILSP11BasicSocialRecovery.sol
> +    /**
To discuss with frozeman

2022-07-26 10:43 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(!_guardians.contains(newGuardian), "Provided address is already a guardian");
We already discussed the use of custom errors in our code, let's first find the solution for it then we can introduce them. I prefer custom errors over string errors :)
For now, let's limit the error message to < 32.

2022-07-26 10:50 UTC, YamenMerhi commented
@CJ42 @skimaharvey Topics to discuss when frozeman is back:
- Introducing events
- Name of functions and variables 
- Custom errors, etc.

2022-07-26 12:44 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(keccak256(abi.encodePacked(plainSecret)) == _secretHash, "Wrong secret");
Ok make totally sense I agree @YamenMerhi 👍

2022-07-26 12:46 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        }
I think it's ok for readability for to keep it as it is for now.

2022-07-26 12:51 UTC, CJ42 approved these changes

2022-07-26 12:51 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        require(!_guardians.contains(newGuardian), "Provided address is already a guardian");
Same more in favour of a custom error like a `NotGuardian(address _address)`. Will be easier to debug.

2022-07-26 12:51 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +        address keyManager = ERC725(account).owner();
ok make sense for initial setup

2022-08-26 03:59 UTC, deepface19 reviewed
i got error when i try to compile

2022-08-26 03:59 UTC, deepface19 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +                ERC725(account),
got error when i try to compile
``` TypeError: Invalid type for argument in function call. Invalid implicit conversion from contract ERC725 
to contract IERC725Y requested.
   --> contracts/LSP11BasicSocialRecoveryCore.sol:198:17:
    |
198 |                 ERC725(account),
```

2023-01-04 09:55 UTC, CJ42 commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert WrongPlainSecret();
suggested renaming:

```suggestion
            revert InvalidSecret();
```

2023-01-04 12:48 UTC, b00ste approved these changes

2023-01-04 14:52 UTC, CJ42 approved these changes

2023-01-04 22:38 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            for (uint256 i; i < guardians.length; i++) {
cant we have a DoS situation with a big array of guardians? If so may be we should document it?

2023-01-04 22:38 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert WrongPlainSecret();
why don't we check for that before looping on the guardians?

2023-01-04 22:38 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert ThresholdCannotBeHigherThanGuardiansNumber(newThreshold, _guardians.length());
maybe checking that `newThreshold != 0`?

2023-01-04 22:45 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            _guardians.values()
do we really need to emits all the guardians?

2023-01-04 23:36 UTC, skimaharvey requested changes
See thread on discord

2023-01-05 09:14 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            _guardians.values()
It was pointed by Fabian, and i think it might make sense to know who was the guardians at this specific recovery process. But let's discuss

2023-01-05 09:15 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert ThresholdCannotBeHigherThanGuardiansNumber(newThreshold, _guardians.length());
We allow threshold to be 0, so the contract can act like a password recovery

2023-01-05 09:15 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            for (uint256 i; i < guardians.length; i++) {
Good point, will document

2023-01-05 09:16 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert WrongPlainSecret();
@skimaharvey https://github.com/lukso-network/lsp-smart-contracts/pull/114#discussion_r929754074

2023-01-05 09:55 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert WrongPlainSecret();
Hmm yes make it less likely to happen but if you know the `_recoverySecretHash` you can easily check if `keccak256(plainSecret)` is correct or not but I guess yes we can leave it there. No big deals.

2023-01-05 09:58 UTC, skimaharvey commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            _guardians.values()
This guardians array could be quite big and costly when emitting. 
Probably would be in favor of not emitting them. @CJ42 @b00ste ?

2023-01-05 09:58 UTC, skimaharvey approved these changes

2023-01-05 11:58 UTC, YamenMerhi commented on contracts/LSP11BasicSocialRecovery/LSP11BasicSocialRecoveryCore.sol
> +            revert WrongPlainSecret();
I wouldn't go with invalid as secretHash use the word invalid, what about `IncorrectSecret()` ?

2023-01-05 12:02 UTC, b00ste approved these changes

2023-01-05 12:04 UTC, skimaharvey approved these changes

2023-01-05 13:18 UTC, CJ42 approved these changes

2023-01-05 13:18 UTC, merged