test: Migrate LSP7DigitalAsset & LSP8Identifiable DigitalAsset & LSP9Vault tests to mocha
lukso-network/lsp-smart-contracts pull request #249
Opened 2022-08-11 15:08 UTC by b00ste

## What does this PR introduce?
Migrating the tests for the LSP7DigitalAsset, LSP8IdentifiableDigitalAsset and LSP9Vault from jest to mocha, using expect from chai.

2022-08-11 15:22 UTC, YamenMerhi approved these changes

2022-08-11 15:22 UTC, YamenMerhi commented on package.json
> +    "test:lsp4": "NODE_NO_WARNINGS=1  tests/LSP4DigitalAssetMetadata/LSP4Compatibility.test.ts",
you cut `hardhat test --no-compile`, please re-add

2022-08-11 15:28 UTC, YamenMerhi approved these changes

2022-08-12 14:19 UTC, CJ42 requested changes
Awesome job! 🚀 

I have added some review comment.

I would suggest overall that we use `to.equal` ✅ instead of ~`to.be.equal`~ ❌ 

See the chai API reference: https://www.chaijs.com/api/bdd/#method_equal

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.behaviour.ts
>          "0xdeba1e292f8ba88238e10ab3c7f88bd4be4fac56cad5194b6ecceaf653468af1";
I suggest that we use the values from `constants.js` and avoid hex literals in tests for data keys, as these are important (also to just defined them in one place, if they ever need to be changed).

add at the top:

```ts
import { ERC725YKeys } from "../../constants.js"
```

and change by

```suggestion
       ERC725YKeys.LSP4["LSP4TokenName"]
```

or 

```suggestion
        ERC725YKeys.LSP4.LSP4TokenName
```

> I prefer the 1st one to differentiate the LSP standard and the data key, but it is up to you, both syntax are valid :)

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP7DigitalAsset/extensions/LSP7CompatibleERC20.behaviour.ts
>          "0x2f0a68ab07768e01943a599e73362a0e17a63a72e94dd2e384d2c1d4db932756";
Same comment as above

```suggestion
        ERC725YKeys.LSP4["LSP4TokenSymbol"];
```

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP7DigitalAsset/extensions/LSP7Mintable.behavior.ts
>  import { ethers } from "hardhat";
@YamenMerhi @b00ste 

A small detail, but this file is named `.behavior.ts` (US syntax) while the other are `*.behaviour.ts` (UK syntax).

How about sticking to `behaviour.ts`? Let's agree on the common syntax to be consistent 🙂

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP7DigitalAsset/extensions/LSP7Mintable.behavior.ts
> +      expect(tokenReceiverBalance.toNumber()).to.be.equal(amountToMint.toNumber());
The chai matchers from Hardhat now work with BN, so no need anymore to convert `.toNumber()`

```suggestion
      expect(tokenReceiverBalance).to.be.equal(amountToMint);
```

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.behaviour.ts
> +      expect(preTokenSupplyCap.sub(preTotalSupply).toString()).to.be.equal(
```suggestion
      expect(preTokenSupplyCap.sub(preTotalSupply)).to.be.equal(
```

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CappedSupply.behaviour.ts
> +        ).to.be.revertedWith("LSP8CappedSupplyCannotMintOverCap()");
```suggestion
        ).to.be.revertedWithCustomError("LSP8CappedSupplyCannotMintOverCap");
```

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8Enumerable.behavior.ts
>  import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
Same comment as above, let's rename to `behaviour.ts`

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8Mintable.behavior.ts
>  import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
Same as above, let's rename to `behaviour.ts` ✅ , not ~`behavior.ts`~ ❌

2022-08-12 14:19 UTC, CJ42 commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8Mintable.behavior.ts
> +      expect(tokenReceiverBalance.toNumber()).to.be.equal(1);
```suggestion
      expect(tokenReceiverBalance).to.be.equal(1);
```

2022-08-12 15:39 UTC, b00ste commented on tests/LSP7DigitalAsset/LSP7DigitalAsset.behaviour.ts
>              if (postIsOperatorFor.eq("0")) {
It shows as BigNumber and this `postIsOperatorFor == false` seems to be invalid

2022-08-15 14:56 UTC, CJ42 approved these changes

2022-08-15 16:13 UTC, merged