[LSP0 and LSP9] Add two step process for renounceOwnership
lukso-network/lsp-smart-contracts pull request #282
Opened 2022-08-26 23:12 UTC by b00ste

# What does this PR introduce?

This PR introduces a 2-step process for renouncing ownership of an LSP0ERC725UniversalProfile and LSP9Vault.
The method `renounceOwnership(…)` was overridden to save the the `block.number` to `lastRenounceOwnershipBlock` and a new method was added, `confirmRenounceOwnership(…)` that allows you to renounce ownership of the contract if and only if the current `block.number` is smaller or equal to the `block.number` saved in `lastRenounceOwnershipBlock`.

## Link to the issue [Issue](https://github.com/lukso-network/LIPs/issues/115)

2022-08-28 10:10 UTC, CJ42 requested changes
I thought we said that we would put these functions in the `ClaimOwnership` contract?

Also, do we introduce an extra function `confirmRenounceOwnership(...)` as well? If this is the case and it is in `ClaimOwnership` contract, doesn't that change the interface IDs in some ways?

@YamenMerhi @frozeman

2022-08-29 15:45 UTC, YamenMerhi requested changes

2022-08-29 15:45 UTC, YamenMerhi commented on contracts/Custom/IClaimOwnership.sol
> +    error RenounceOwnershipPending(string errorText, uint256 blockNumber);
I don't think this should go in the interface. If agreed please let's remove

2022-08-29 15:45 UTC, YamenMerhi commented on tests/UniversalProfile.behaviour.ts
> +          ethers.utils.hexZeroPad("0x", 20)
You can replace with `ethers.constants.AddressZero`

2022-08-29 15:45 UTC, YamenMerhi commented on tests/UniversalProfile.behaviour.ts
> +        ethers.utils.hexZeroPad("0x", 20)
same here

2022-08-29 15:45 UTC, YamenMerhi commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +          ethers.utils.hexZeroPad("0x", 20)
same here

2022-08-29 15:45 UTC, YamenMerhi commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +            ethers.utils.hexZeroPad("0x", 20)
and here

2022-08-29 17:47 UTC, CJ42 requested changes
I think it's ok for now, but should also tests the more cases, where for instance the block delay timed out (for the future).

2022-08-29 17:47 UTC, CJ42 commented on contracts/Custom/ClaimOwnership.sol
> +    uint256 private _lastBlock;
could you add an extra space between the variable and the natspec comment.

2022-08-29 17:47 UTC, CJ42 commented on contracts/Custom/ClaimOwnership.sol
> +    error RenounceOwnershipAvailableAtBlockNumber(uint256 blockNumber);
It might be better to put the custom error above the contract IMO.

Like this.

```solidity
pragma solidity ^0.8.5;

import {OwnableUnset} from "@erc725/smart-contracts/contracts/custom/OwnableUnset.sol";

error RenounceOwnershipAvailableAtBlockNumber(uint256 blockNumber);

abstract contract ClaimOwnership is IClaimOwnership, OwnableUnset {
    // ...
}
```

2022-08-29 17:47 UTC, CJ42 commented on contracts/Custom/ClaimOwnership.sol
> +        uint256 _delayBlocks = 100;
Maybe we could put that as a `constant` inside the contract. So that it is stored in the contract bytecode, to make it a bit cheaper.

2022-08-29 17:47 UTC, CJ42 commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +        const renounceOwnershipOnce = context.lsp9Vault
You have to `await` here the transaction in order to wait for the transaction receipt.

```suggestion
        const renounceOwnershipOnce = await context.lsp9Vault
```

2022-08-29 17:47 UTC, CJ42 commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +        await expect(renounceOwnershipOnce).to.emit(
and here remove the `await`

2022-08-29 17:47 UTC, CJ42 commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +        const renounceOwnershipSecond = context.lsp9Vault
same comment as above.

2022-08-29 17:47 UTC, CJ42 commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +          .withArgs((await renounceOwnershipOnce).blockNumber + 100);
so here in the end you can remove the `await` in this line :)

2022-08-29 18:39 UTC, b00ste commented on tests/LSP9Vault/LSP9Vault.behaviour.ts
> +        await expect(renounceOwnershipOnce).to.emit(
if i make the suggested changes the test passes with wrong event name

2022-08-29 19:31 UTC, CJ42 approved these changes

2022-08-29 19:36 UTC, YamenMerhi approved these changes

2022-08-29 19:42 UTC, merged