refactor: disallow DELEGATECALL operation in LSP9Vault
lukso-network/lsp-smart-contracts pull request #303
Opened 2022-09-05 13:48 UTC by YamenMerhi

## What does this PR introduce?
- Overriding execute function in LSP9Vault and disallowing the use of delegatecall, since it's a dangerous operation and could lead to the destruction of the vault.

The use of delegatecall in LSP9 is totally optional. 
Referring to the [LSP9 specs](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-9-Vault.md), it's mention that an LSP9Vault must include the following operation: CALL, CREATE, CREATE2, STATICCALL and CAN include the operation DELEGATECALL.

2022-09-05 14:37 UTC, b00ste approved these changes

2022-09-06 10:50 UTC, CJ42 requested changes

2022-09-06 10:50 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
>  import {IERC725Y} from "@erc725/smart-contracts/contracts/interfaces/IERC725Y.sol";
You can remove these two lines from the imports (` import {IERC725X} ...` and `import {IERC725Y} ...`). They are not used in the contract anywhere (neither in the inheritance, nor inside the contract code.

2022-09-06 10:50 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +import "@erc725/smart-contracts/contracts/constants.sol";
Why not adding the exact constants imported here, so they can be easily found?

```solidity
import {
    OPERATION_CALL, 
    OPERATION_STATICCALL, 
    OPERATION_CREATE, 
    OPERATION_CREATE2
} from "@erc725/smart-contracts/contracts/constants.sol";
```

2022-09-06 10:50 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +     * @dev Executes any other smart contract.
would it be worth mentioning in the Natspec docs as well that DELEGATECALL is disallowed?

2022-09-06 10:50 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +     * @dev Calls the universalReceiver function of the vault sender if supports LSP1 InterfaceId
nice extra specs 👍

2022-09-06 10:50 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +import "@erc725/smart-contracts/contracts/constants.sol";
Why not adding the exact constants imported here, so they can be easily found?

```solidity
import {
    OPERATION_CALL, 
    OPERATION_STATICCALL, 
    OPERATION_CREATE, 
    OPERATION_CREATE2
} from "@erc725/smart-contracts/contracts/constants.sol";
```

2022-09-06 11:38 UTC, YamenMerhi commented on contracts/LSP9Vault/LSP9VaultCore.sol
>  import {IERC725Y} from "@erc725/smart-contracts/contracts/interfaces/IERC725Y.sol";
They are used within the natspec

2022-09-06 11:38 UTC, YamenMerhi commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +import "@erc725/smart-contracts/contracts/constants.sol";
Good pt

2022-09-06 11:38 UTC, YamenMerhi commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +     * @dev Executes any other smart contract.
I overrided the @param tag to point out that these are the operation allowed. I guess this is a good base

2022-09-06 15:31 UTC, merged