feat: Add tests for a LSP6 controlled Mintable LSP7
lukso-network/lsp-smart-contracts pull request #308
Opened 2022-09-12 11:30 UTC by b00ste

## What does this PR introduce?

In this pr we create a new test file that tests the behavior of a LSP6 controlled Mintable LSP7.

- using execute(..) in LSP7 through LSP6 --> reverts
- using mint(..) in LSP7 through LSP6 --> reverts
- using renounceOwnership(..) in LSP7 through LSP6 --> reverts
- using transferOwnership(..) in LSP7 through LSP6 --> works
- using setData(..) in lSP7 through LSP6 --> works
- - CHANGEOWNER --> works
- - CHANGEPERMISSIONS --> works 
- - ADDPERMISSIONS --> works
- - SETDATA --> works
- - CALL --> not working
- - STATICCALL --> not working
- - DELEGATECALL --> not working
- - DEPLOY --> not working
- - TRANSFERVALUE --> not working
- - SIGN --> works
- - ENCRYPT --> not tested

2022-09-13 11:38 UTC, CJ42 requested changes
Nice testing for some potential future use cases! I have added some review comments.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    ERC725YKeys.LSP6["AddressPermissions:Permissions"] +
maybe you can store the `address[0]` in a `owner` variable (for the address that has ALL PERMISSIONS)?

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    expect(await context.token.owner()).to.be.equal(context.keyManager.address);
```suggestion
    expect(await context.token.owner()).to.equal(context.keyManager.address);
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    expect(await context.token["getData(bytes32[])"](keys)).to.be.deep.equal(
```suggestion
    expect(await context.token["getData(bytes32[])"](keys)).to.deep.equal(
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +  describe("using execute(..) in LSP7 through LSP6", () => {
```suggestion
  describe("when trying to call execute(..) function on LSP7 through LSP6", () => {
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    it("should revert", async () => {
Maybe we could add a bit more descriptions in the tests, so that we know why it should revert?

```suggestion
    it("should revert because function does not exist on LSP7", async () => {
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      const mintPayload = newTokenContract.interface.encodeFunctionData(
How about adding a comment above, to explain that we try to call the `mint(...)` function in another contract? (as we were discussing)

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +  describe("using mint(..) in LSP7 through LSP6", () => {
same comment as above.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      await expect(executeMintPayload)
I would suggest to put the whole call inside the `expect(...)`, as the tests sometimes are buggy when testing events like that.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    it("should change the owner of LSP7 contract", async () => {
We could add some extra tests here, to ensure that afterwards, to ensure that:

- the functions marked as `onlyOwner` on the LSP7 token contract cannot be called by the KeyManager anymore afterwards.
- only the new owner (the EOA) can call these functions.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +          context.accounts[0].address,
It is a bit misleading here to use the same address as the EOA that had all the permissions previously (`accounts[0]`).

Maybe we could use an other account to make it more explicit? Like:

```js
const newOwner = context.accounts[1];

const transferOwnershipPayload =
        context.token.interface.encodeFunctionData("transferOwnership", [
          newOwner.address,
        ]);

```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +    it("should revert when calling setData(..)", async () => {
ah ok this is done here. Maybe we can improve the description.

Or use a `describe` block?

```js
describe("when previous owner try to interact via the Key Manager", () => {
    it("`setData(...)` -> should revert with 'caller is not the owner' error.", async () => {
        // ....
    }) 
})
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +        ).to.be.deep.equal(values);
```suggestion
        ).to.deep.equal(values);
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      after(async () => {
very nice 👌

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should revert when trying to use `renounceOwnership()`", async () => {
maybe we should not put this test here, as it is not related to the permission CHANGEOWNER.
Because renounceOwnership cannot be called via the KeyManager (the KM does not provide this path).

So maybe in a separate describe block for edge cases?

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +        ).to.be.deep.equal(values);
```suggestion
        ).to.deep.equal(values);
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +          .connect(context.accounts[1])
maybe we can define this signer as `addressCanChangePermission`?
Otherwise, it is difficult to infer which permissions the caller has by reading the test.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should add back ALL_PERMISSIONS of the address", async () => {
This is actually the wrong behaviour that we will have to fix.
It should be possible if you have CHANGEPERMISSIONS permission to add more permissions that it is initially.

See this comment: https://github.com/lukso-network/LIPs/pull/102#issuecomment-1205535756

As a note. Will have to update in the future.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should be allowed to add permissions", async () => {
I suggest this wording, to make it more clear.

```suggestion
      it("should be allowed to add a new controller address with some permissions", async () => {
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should revert when trying to remove permissions", async () => {
same here.

```suggestion
      it("should not be authorized to edit permissions of an existing controller (e.g: removing permissions)", async () => {
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +        await expect(executePayload)
Maybe we can put the contract call direct inside the `expect` here?
Since we don't use the `const` defined.

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +        ).to.be.deep.equal(values);
Can you check that the other tests don't have the `be` like here, but just `to.deep.equal(...)`

```suggestion
        ).to.deep.equal(values);
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should allow second controller to use setData", async () => {
nice test 👌

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +                .keccak256(ethers.utils.toUtf8Bytes("FirstRandomString"))
You can define this variable in a constant at the beginning of the `describe` block and reuse it across tests (define the data key prefix in a constant for instance).

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +          ethers.utils.keccak256(ethers.utils.toUtf8Bytes("FirstRandomString")),
not sure to see here which data key is not allowed.

I guess the first one because it does not have 16 x `00`s? Maybe you could hash another word to make this more explicit.

```suggestion
          ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Not Allowed ERC725Y data key")),
```

2022-09-13 11:38 UTC, CJ42 commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +     */
How about moving the describe block when testing `execute(...)` here?
We could also add the other tests for CALL, DELEGATECALL, STATICCALL, DEPLOY and TRANSFERVALUE in the future. But this is overkill for now.

2022-09-13 14:09 UTC, b00ste commented on tests/LSP6KeyManager/tests/LSP6ControlledToken.test.ts
> +      it("should revert when trying to use `renounceOwnership()`", async () => {
you’re right and the test already exists on line 170

2022-09-14 08:18 UTC, YamenMerhi approved these changes

2022-09-14 08:45 UTC, CJ42 approved these changes

2022-09-14 09:08 UTC, merged