fix: `transferOwnership` —> `renounceOwnership` —> `claimOwnership` bug
lukso-network/lsp-smart-contracts pull request #310
Opened 2022-09-13 10:01 UTC by b00ste

## What does this PR introduce?

This PR fixes the bug described in this [tweet](https://twitter.com/pcaversaccio/status/1569373269228142592?t=3i66r7ZBWTL6ZwWREA6MCQ&s=19). Also there is a test added to check that this behaviour is not happening.

2022-09-13 10:25 UTC, CJ42 requested changes
We need to add some tests for the scenario explained here: https://twitter.com/pcaversaccio/status/1569373269228142592?t=3i66r7ZBWTL6ZwWREA6MCQ&s=19

Also @b00ste can you add a bit more description in the PR body about the issue?
If the tweet ever get deleted, we still have some content to refer to.

2022-09-13 10:37 UTC, b00ste commented
> We need to add some tests for the scenario explained here: https://twitter.com/pcaversaccio/status/1569373269228142592?t=3i66r7ZBWTL6ZwWREA6MCQ&s=19
> 
> we need to ensure with a test that this potential scenario is fixed.
> 
> Also @b00ste can you add a bit more description in the PR body about the issue? If the tweet ever get deleted, we still have some content to refer to.

2022-09-14 11:26 UTC, CJ42 approved these changes

2022-09-14 11:28 UTC, YamenMerhi approved these changes

2022-09-14 11:38 UTC, merged