feat: add typeId delegate to `universalReceiver(..)` function
lukso-network/lsp-smart-contracts pull request #326
Opened 2022-09-27 13:20 UTC by YamenMerhi

## What does this PR introduce?
- Adding routing to the universalReceiver function
- Add tests to check how ABI encoding works and gas costs
- Resolve test according to new behaviour

2022-09-28 17:00 UTC, CJ42 reviewed
added first round of review comments.

2022-09-28 17:00 UTC, CJ42 commented on contracts/Helpers/ABIEncoder.sol
> +        uint256 gasUsed2 = gasleft();
what are you trying to test? how much gas it cost to do `abi.encode` 2 x `bytes`?
The result might likely depend on how big these two `bytes` values are.

2022-09-28 17:00 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @return returnedValue The ABI encoded return value of the LSP1UniversalReceiverDelegate call
I think this docstring is incorrect now because of the changes this PR introduce.

1. I would suggest to rename the variable to plural: `returnValue` > `returnedValues`
2. This returned variable should be described as the result of **both calls**, bot results being abi encoded together.
3. we should also explain what are each of these calls in the docs string (to the default LSP1Delegate, then for the additional LSP1Delegate setup for this typeId).

2022-09-28 17:00 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        bytes memory returnedValue1;
I would recommend using different variable names here.
Because it makes it hard to understand otherwise the actual difference between `returnedValue1` and `returnedValue2`.

Even if it is long.

For instance:

```solidity
        // default LSP1 Delegate.
        bytes memory returnedDataDefaultLSP1Delegate;
        
        // LSP1Delegate for typeId
        bytes memory returnedDataLSP1DelegateForTypeID
```

@skimaharvey @b00ste do you have suggestions for better variable names?

2022-09-28 17:48 UTC, YamenMerhi commented on contracts/Helpers/ABIEncoder.sol
> +        uint256 gasUsed2 = gasleft();
Exactly that's what i did in ABIEncoder.test.ts :)

2022-09-28 17:50 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        bytes memory returnedValue1;
I tried having these names, it will make the whole function looks ugly if we have very long name.
Anyway I am happy to do it.
My suggestion: we can leave it with shortnames or add the long names with a prettier-ignore to preserve the style of the function

2022-09-29 07:21 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        bytes memory returnedValue1;
ok we can try to shorten it then. Probably no need to specify `LSP1` in the name of the variable since we are inside the `universalReceiver(...)` function, so the context is LSP1.

Let's name it:

```js
// default LSP1 Delegate.
bytes memory resultDelegate;
        
// LSP1Delegate for typeId
bytes memory resultTypeID
```

2022-09-29 07:35 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        bytes memory returnedValue1;
Great idea, even tried this and it looks good ⬇️ 
```js
        bytes memory lsp1DelegateValue = _getData(_LSP1_UNIVERSAL_RECEIVER_DELEGATE_KEY);
        bytes memory resultMainDelegate;
        [..]
        bytes memory lsp1TypeIdDelegateValue = _getData(typeId);
        bytes memory resultTypeIdDelegate;
         [..]
        returnedValues = abi.encode(resultMainDelegate, resultTypeIdDelegate);
```

2022-09-29 07:39 UTC, CJ42 requested changes
added review comments.

2022-09-29 07:39 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>       * @dev Forwards the call to the UniversalReceiverDelegate if set.
this docstring needs to be changed. To explain that it forwards the call to the other `LSP1TypeIdDelegate` contract.

It might be a good place here to explain what each of these calls are (briefly).

2022-09-29 07:39 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +            address universalReceiverDelegate = address(bytes20(lsp1TypeIdDelegateValue));
maybe rename to:

```suggestion
            address typeIdDelegate = address(bytes20(lsp1TypeIdDelegateValue));
```

?

You can also declare the variable locally outside of each `if (...) { ... }`, and re-assign it. It might save like 10 gas, but not sure if it would make it more readable.

```solidity
address universalReceiverDelegate;

bytes memory lsp1DelegateValue = _getData(_LSP1_UNIVERSAL_RECEIVER_DELEGATE_KEY);

if (lsp1DelegateValue.length >= 20) {
    universalReceiverDelegate = address(bytes20(lsp1DelegateValue));
    
    // ...
}

bytes memory lsp1TypeIdDelegateValue = _getData(typeId);

if (lsp1TypeIdDelegateValue.length >= 20) {
    universalReceiverDelegate = address(bytes20(lsp1TypeIdDelegateValue));
    
    // ...
}
```

2022-09-29 07:39 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +    using ERC165Checker for address;
I agree on this 👍
it looks much easier to read below compare to before

2022-09-29 07:39 UTC, CJ42 commented on contracts/LSP9Vault/LSP9VaultCore.sol
>      function universalReceiver(bytes32 typeId, bytes calldata receivedData)
same comments I put on LSP0 apply here for LSP9.

2022-09-29 07:39 UTC, CJ42 commented on tests/Helpers/ABIEncoder.test.ts
> +  const verifyResult = async (txParameterA, txParameterB) => {
nicely written tests 👌

2022-09-29 07:39 UTC, CJ42 commented on tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
> +          abiCoder.encode(
_Suggestion_: maybe destructure the returned parameters?
And then do two `expect` for each.

```js
const [resultDelegate, resultTypeID] = abiCoder.decode(result)
expect(resultDelegate).to.equal(
    ethers.utils.hexlify(
        ethers.utils.toUtf8Bytes("LSP1: typeId out of scope")
    ))
expect(resultTypeID).to.equal("0x").
```

Otherwise, looks good to me :)

2022-09-29 07:43 UTC, CJ42 commented
@YamenMerhi I will rename the title of the PR for the release CHANGELOG (in order to show the description properly under the feature subheading)

2022-09-30 08:41 UTC, CJ42 approved these changes

2022-09-30 08:41 UTC, merged