feat: Add reentrancy guard in LSP6 that allows reentrancy only from URD
lukso-network/lsp-smart-contracts pull request #332
Opened 2022-10-07 13:07 UTC by b00ste

## What does this PR introduce?

This PR adds a new contract `LSP6ReentrancyGuard` in the custom contracts folder which introduces a new modifier for blocking reentrancy unless the caller is the URD of the contract.

Additionally it introduces tests for checking that random contracts cannot reenter the execution and that only the URD of the contract is allowed to reenter during the execution.

2022-10-18 09:32 UTC, CJ42 reviewed
added review comments

2022-10-18 09:32 UTC, CJ42 commented on contracts/Helpers/Security/Reentrancy.sol
> +        if (!switchFallback) {
What does this `!switchFallback` check does? Re-enter only once?

2022-10-18 09:32 UTC, CJ42 commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +            //compare URD address and msg.sender
this comment can be removed since it is mentioned in the Natspec comments

2022-10-18 09:32 UTC, CJ42 commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +     * Used in the beggining of the `nonReentrant` modifier, before the method execution starts
```suggestion
     * Used in the beginning of the `nonReentrant` modifier, before the method execution starts
```

2022-10-18 09:32 UTC, CJ42 commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +            if (msg.sender != urdAddress) revert ReentrantAddressNotURD();
I don't think we should have this revert error like this since we are just making an exception for the URD.

Why don't we keep the same one as OpenZeppelin?

```solidity
        // On the first call to nonReentrant, _status will be _NOT_ENTERED
        require(_status != _ENTERED, "ReentrancyGuard: reentrant call");
```

or we just state the caller address in the custom error to have a bit more info as well about which contract tried to re-enter the call:

```solidity
revert ReentrantCall(address reentrantCaller)
```

or a bit more explicit, following your changes @skimaharvey @b00ste 

```solidity
revert ReentrantCallNotFromURD(address reentrantCaller) // how about this?
revert ReentrantCallNotFromLSP1Delegate(address reentrantCaller) // or this?
```

@YamenMerhi any feedbacks?

2022-10-19 09:38 UTC, b00ste commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +            if (msg.sender != urdAddress) revert ReentrantAddressNotURD();
`revert ReentrantCallNotFromLSP1Delegate(address reentrantCaller)` i like this one. since we have an allowed address to reenter i think that we have to specify in the error that the reentrant call is not made from the allowed address, not only that it is a reentrant call, because we kind of allow reentrant calls.

2022-10-19 12:14 UTC, YamenMerhi commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +            if (msg.sender != urdAddress) revert ReentrantAddressNotURD();
I don't mind going with `ReentrantCallNotFromLSP1Delegate` but doesn't make much sense for me, as when it will revert it will be a `ReentrantCall` regardless if the URD is allowed or not.

2022-10-19 20:46 UTC, CJ42 commented on contracts/Custom/LSP6ReentrancyGuard.sol
> +            if (msg.sender != urdAddress) revert ReentrantAddressNotURD();
That's true, then let's just keep it like OZ but just use a custom error for gas savings.

```
revert ReentrantCall(address reentrantCaller)
```

2022-10-20 09:27 UTC, skimaharvey commented on contracts/Helpers/Security/Reentrancy.sol
> +        if (!switchFallback) {
yes because if it does not we would end up with a loop

2022-11-10 12:05 UTC, YamenMerhi requested changes
I don't think it should be applied to `msg.sender`, as we're getting the permissions of relayer in case of `executeRelayCall(..)` which doesn't make any sense. Right ? @b00ste @skimaharvey @CJ42 

The modifier should not be applied to `execute(..)` and `executeRelayCall(..)` in this case, it should be `_verifyPermissions(..)` with removing `view` option as in the modifier we are writing to the state. After adding the modifier to the  `_verifyPermissions(..)` function, we pass the address `from` to the modifier, which pass it to the internal function `_nonReentrantBefore(..)`, in this function we replace `msg.sender` with `from`.

2022-11-10 12:20 UTC, CJ42 requested changes
added review comments

2022-11-10 12:20 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    // Booleans are more expensive than uint256 or any type that takes up a full
can we add a reference link maybe to the OpenZeppelin contract we took it from?

2022-11-10 12:20 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function execute(bytes calldata payload) public payable nonReentrant() returns (bytes memory) {
parentheses are not necessary if the modifier does not have arguments.

```suggestion
    function execute(bytes calldata payload) public payable nonReentrant returns (bytes memory) {
```

2022-11-10 12:20 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            // get and check the permissions of the caller
```suggestion
            // CHECK the caller has REENTRANCY permission
```

2022-11-10 12:20 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * the status is `_ENTERED` in order to revert the call unless the caller is the URD address
this comment is outdated.

```suggestion
     * the status is `_ENTERED` in order to revert the call unless the caller has the REENTRANCY permission
```

2022-11-10 12:20 UTC, CJ42 commented on tests/LSP6KeyManager/tests/Security.test.ts
>        // at this point, the malicious contract fallback function
can we update this comment and put it back above. So like that:

```js
// send LYX to malicious contract
// at this point, the malicious contract fallback function try to drain funds by re-entering the call
// this should not be possible since it does not have the permission `REENTRANCY`
await expect(
        context.keyManager.connect(context.owner).execute(transferPayload)
      )
        .to.be.revertedWithCustomError(context.keyManager, "NotAuthorised")
        .withArgs(maliciousContract.address, "REENTRANCY");
```

2022-11-10 12:20 UTC, CJ42 commented on tests/LSP6KeyManager/tests/Security.test.ts
> +    it("should pass when reentered by URD", async () => {
```suggestion
    it("should pass when reentered by URD and the URD has REENTRANCY permission", async () => {
```

2022-11-10 12:29 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    uint256 private _status;
I tgink we should rename this variable to `_reantrancyStatus`

2022-11-11 11:27 UTC, skimaharvey approved these changes
Nice

2022-11-11 11:27 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * it's the URD of the contract that makes the call.
URD or contract with ReentrancyPermission

2022-11-17 12:23 UTC, YamenMerhi reviewed
For the first round of review, let's see if we agree about changing the location of the check of reentrancy.

2022-11-17 12:23 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    modifier nonReentrant(address from) {
Can be removed, since it's no longer used, rigth ?

2022-11-17 12:23 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _verifyPermissions(address from, bytes calldata payload) internal {
can we re-add view since we didn't change anything here?

2022-11-17 12:23 UTC, YamenMerhi commented on contracts/Helpers/Reentrancy/ReentrancyWithValueTransfer.sol
> +    receive() external payable { }
linter warning

2022-11-17 12:23 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(msg.sender);
I would move this line under `_verifyPermissions(msg.sender, payload);` to allow proper error bubbling

2022-11-17 12:23 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(signer);
I would move this line under `_verifyPermissions(signer, payload);` to allow proper error bubbling

2022-11-17 12:28 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(signer);
same comment as above

2022-11-17 12:57 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(msg.sender);
also we are fetching permissions in  _nonReentrantBefore(msg.sender) + in the `verifyPermission`

2022-11-18 13:32 UTC, skimaharvey approved these changes

2022-11-22 08:41 UTC, YamenMerhi approved these changes

2022-11-25 09:07 UTC, YamenMerhi approved these changes

2022-11-25 09:39 UTC, CJ42 reviewed
added review comments

2022-11-25 09:39 UTC, CJ42 commented on contracts/Helpers/Security/Reentrancy.sol
> +            bytes memory result = Address.verifyCallResult(success, returnData, "");
a small detail but in this Helper contract, maybe we could add a default revert handler string. Like:

```suggestion
            bytes memory result = Address.verifyCallResult(success, returnData, "Reentrancy Helper Contract: failed to re-enter contract");
```

This way if we add tests in the future, we will know more easily if the reentrant call failed. Otherwise with an empty revert reason string, it might be harder to debug.

2022-11-25 09:39 UTC, CJ42 commented on contracts/Helpers/UniversalReceivers/UniversalReceiverDelegateDataUpdater.sol
> +                bytes32(keccak256(bytes("some random data key"))),
The `bytes32` casting is not needed here. `keccak256` will return a `bytes32` value.

```suggestion
                keccak256(bytes("some random data key")),
```

See the Solidity docs:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/31145285/203944046-6eea8a6d-44be-48aa-ad0b-4a35cc519879.png">

https://docs.soliditylang.org/en/v0.8.17/units-and-global-variables.html#mathematical-and-cryptographic-functions

2022-11-25 09:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    // https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol
I think a frozen commit hash, or a specific release version of OZ might be better here for the link.
In case. If the folder structure of the OpenZeppelin repo changes, the link might break and return a "404 Page Not Found" on Github.

2022-11-25 09:39 UTC, CJ42 commented on contracts/Helpers/Reentrancy/RelayReentrancy.sol
> +    receive() external payable {}
is this needed? Does the Helper contract needs to receive funds? 
If not, we can remove it.

2022-11-25 09:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _setupLSP6ReentrancyGuard() internal {
I am a bit worried about this function being `internal`.
I understand that we use it to setup the `_reentrancyStatus` to `_NOT_ENTERED` **on deployment**.

But now since the function is `internal`, through inheritance, any custom implementation of the KeyManager can recall this function in an other function. Which is not really the expected behaviour, since we just want to **set it up only on deployment**.

I am not sure how we could solve this now. Let me know your feedbacks.

2022-11-25 09:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(signer);
> I would move this line under _verifyPermissions(signer, payload); to allow proper error bubbling

@YamenMerhi not sure to understand what you mean by _"allowing proper error bubbling"_. Could you give some details or an example? 🙂 
 
I would leave this line before `_verifyPermissions` actually, because it setup some state in the contract (the `reentrancyStatus` state variable. See below.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/31145285/203947822-ce46a465-4f7f-48c1-8353-f1be9e17e4cf.png">

Since `_verifyPermissions` does a lot of external calls (e.g: reading the permissions to the linked target contract, checking if the contract we want to interact with supports an interface if the payload is `ERC725X.execute(...)`), I think it might be safer to setup the reentrancy status before anything else happen. In case one of the external calls mentioned before is malicious and try to re-enter the KeyManager

(not likely for reading the permissions on the linked target, more more likely when checking with `supportsInterface`, since this can be easily faked as we know).

I think by putting this function here, we follow the _check-effect-interaction_ pattern.

2022-11-25 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        _nonReentrantBefore(signer);
@CJ42 `_verifyPermissions` is view function, so no risk of adding the line after because any external call will be view and will not change the state of any contract.

I was thinking about reverting with the normal permission first if the caller doesn't have them, then reentrancy can come after. But the team agreed about reverting first with reentrancy, as in both cases, in a case of a caller doesn't have any permission, he will need the permissions to interact and to reenter.

2022-11-25 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    // https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol
Yep better

2022-11-25 10:17 UTC, b00ste commented on contracts/Helpers/Reentrancy/RelayReentrancy.sol
> +    receive() external payable {}
Yep, it is needed.

2022-11-25 11:31 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _setupLSP6ReentrancyGuard() internal {
It should be solved right now, the only case when we can initialize is if the status i different to _ENTERED and _NOT_ENERED

2022-11-25 12:33 UTC, CJ42 approved these changes

2022-11-25 12:33 UTC, merged