docs: update smart contracts natspec
lukso-network/lsp-smart-contracts pull request #335
Opened 2022-10-12 10:06 UTC by b00ste

## What does this PR introduce?

In this PR we add some natspec in the following contracts:

- LSP5Utils.sol
- LSP6KeyManagerCore.sol
- LSP6Utils.sol
- LSP7Errors.sol
- LSP8IdentifiableDigitalAssetCore.sol
- LSP8Errors.sol
- LSP10Utils.sol

2022-10-17 12:46 UTC, CJ42 requested changes
added review comments

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @dev returns the permissions of the `caller` for the ERC725Y `target`
```suggestion
     * @dev read the permissions of a `caller` on an ERC725Y `target` contract.
```

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @param target a valid `IERC725Y` interface
```suggestion
     * @param target an `IERC725Y`  contract where to read the permissions.
```

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @param caller the controller address
```suggestion
     * @param caller the controller address to read the permissions from.
```

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @dev returns the allowed addresses of the `caller` for the ERC725Y `target`
There is a "@return" tag for Natspec comments.

I would recommend to use it, so that "@return" describes what is being returned, and "@dev" explains what the function does.

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP7DigitalAsset/LSP7Errors.sol
> + * @dev tx is reverted with this error if the `amount` of tokens which are to be transferred
I think these descriptions are a but long. Maybe we can write them at the "imperative" tense to make them shorter. The wording "tx is reverted" seems quite redundant to me.

Instead of  "tx is reverted ..."
We can use "reverts when ..."

2022-10-17 12:46 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> +     * @dev verifies if the `caller` is operator or owner for the `tokenId`
Great description 👌🏻

2022-10-19 02:18 UTC, CJ42 requested changes
added comments

2022-10-19 02:18 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * @dev returns the `errorName` depending on the `permission` given
```suggestion
     * @dev returns the name of the permission as a string
```

Given the suggested change, we can very likely rename this function to something like "_getPermissionName(...)" or "getPermissionString(...)", etc...

2022-10-19 02:18 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @return an encoded `bytes` value which contains an array of allowed function signatures (to interact with) for the controller address.
This does not return function signatures, but function selectors. Be careful with the terminology here. It's very different.

```suggestion
     * @return an abi-encoded array of functions selectors that the controller address is allowed to interact with.
```

2022-10-19 02:18 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @return an encoded `bytes` value which contains an array of allowed addresses (to interact with) for the controller address.
```suggestion
     * @return an abi-encoded array of addresses that the controller address is allowed to interact with.
```

Please be specific and always mention how it is encoded (= abi-encoded)

2022-10-19 02:18 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +     * @return a `bytes32` BitArray containing the permissions of a controller address.
This is an excellent description comment. Very great job here 👌🏻

2022-10-19 09:40 UTC, CJ42 requested changes

2022-10-19 09:40 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * @dev returns the index of the last non-empty byte, meaning != `0x00`
@b00ste please change this doc comment with what we discussed in pm.

2022-10-21 08:38 UTC, YamenMerhi approved these changes

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> +     * @dev removes `operator` from the list of operators of the `tokenId`
Let's use `for` for consistency, as it is what is used in the Natspec comment above.

```suggestion
     * @dev removes `operator` from the list of operators for the `tokenId`
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> +     * @dev clear all the operators of the `tokenId`
```suggestion
     * @dev clear all the operators for the `tokenId`
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when `tokenId` is already minted
```suggestion
 * @dev reverts when `tokenId` has already been minted
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
>  error LSP8NonExistingOperator(address _address, bytes32 tokenId);
Let's change the name of the parameter

```suggestion
error LSP8NonExistingOperator(address operator, bytes32 tokenId);
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when `_address` is not a operator for the `tokenId`
```suggestion
 * @dev reverts when `operator` is not an operator for the `tokenId`
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when one tries to send token to itself
```suggestion
 * @dev reverts when specifying the same address for `from` and `to` in a token transfer.
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when `operator` is already an authorized to transfer the `tokenId`
```suggestion
 * @dev reverts when `operator` is already authorized for the `tokenId`
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when `tokenId` doesn't exist
```suggestion
 * @dev reverts when `tokenId` has not been minted
```

2022-10-22 14:08 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8Errors.sol
> + * @dev reverts when one tries to set the zero address as operator
```suggestion
 * @dev reverts when trying to set the zero address as an operator
```

2022-10-25 10:21 UTC, merged