refactor!: [WP-C2] Change the verification logic of AllowedERC725YKeys in LSP6
lukso-network/lsp-smart-contracts pull request #352
Opened 2022-11-02 09:56 UTC by b00ste

# What does this PR introduce?

## ⚠️ BREAKING CHANGE!

### Main

- Change in how we store the: `AllowedERC725YKeys` in the ERC725Y storage:
      - before: `bytes32[] encoded array`
     - now: `compactedBytesArray` 

- Change in how we check the `AllowedERC725YKeys` in the LSP6KeyManager according to `compactedBytesArray` type.

### Periphery:
- Add new custom error to `constant.js`

## Rational

<img width="866" alt="9A9E65E3-4CF5-4C52-A77F-D288F1EF4B5B" src="https://user-images.githubusercontent.com/62855857/199459526-09b7c720-9c20-4d00-8444-59c1cd7a08f4.png">

2022-11-02 11:49 UTC, skimaharvey commented on contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
> +    function checkValidCompactBytesArray(bytes memory compactBytesArray)
I think since it returns a bool pretending by `is` is better?
```suggestion
    function isValidCompactBytesArray(bytes memory compactBytesArray)
```

2022-11-02 11:49 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
```suggestion
    function _isValidCompactBytesArray(bytes memory compactBytesArray)
```

2022-11-02 11:49 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            if (!isClearingArray && !_checkValidCompactBytesArray(dataValue)) {
I think `isClearingArray` is not needed here. if `dataValue.length == 0` `_checkValidCompactBytesArray(dataValue))` should return true

2022-11-02 11:49 UTC, skimaharvey commented on contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
> +        address _from,
why `_` in front of the from? (not a big deal since it a tester but I don't think we use `_` elsewhere?

2022-11-02 11:49 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
also same as before if `compactBytesArray` is `0x`, it  will be considered as valid. should it? @YamenMerhi @CJ42 @b00ste

2022-11-02 11:49 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        uint256 pointer = 0;
to me it is a little weird that we don't initialise`foundAllowedKey` but initialize `uint256 pointer = 0;` when we don't need too. Out of consistency I think we should initialize or don't.

2022-11-02 11:51 UTC, skimaharvey commented on tests/utils/helpers.ts
> +}
this is super cool

2022-11-02 14:30 UTC, YamenMerhi commented on contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
> +    function checkValidCompactBytesArray(bytes memory compactBytesArray)
Yep agree

2022-11-02 14:31 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        uint256 pointer = 0;
I would say let's not initialize, not needed as you said

2022-11-02 14:47 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
Should we move this function to LSP2Utils and rename it to `isValidDynamicCompactBytesArray`?
and then the error could be in sync with the one in PR #351 : `InvalidDynamicCompactBytesArray` and maybe adding the bytes as param ?

2022-11-02 15:00 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
Yes this function should not be in the KeyManager contract. Since `CompactBytesArray` is something specific to LSP2, not LSP6.

2022-11-02 21:22 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
> Should we move this function to LSP2Utils and rename it to `isValidDynamicCompactBytesArray`? and then the error could be in sync with the one in PR #351 : `InvalidDynamicCompactBytesArray` and maybe adding the bytes as param ?

Yes I think that is what we should do. Also create a similar one for `FixCompactBytesArray`

2022-11-02 21:45 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
actually, we should review this function as it does not entirely work. For example with the value `0x02000000001100`, after the `2` we would expect 2 bytes however in this case we have 4 `00` bytes. At the moment I dont see any use case where it could be a treat but it is not reassuring. @b00ste @CJ42 @YamenMerhi

2022-11-03 05:50 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            uint256 elementLength = uint256(uint8(bytes1(compactBytesArray[pointer])));
probably should add a check that returns false when `elementLength == 0` 
```suggestion
            uint256 elementLength = uint256(uint8(bytes1(compactBytesArray[pointer])));
if(elementLength == 0) return false;
```

2022-11-03 05:52 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _checkValidCompactBytesArray(bytes memory compactBytesArray)
added a code suggestion following the comment above 
https://github.com/lukso-network/lsp-smart-contracts/pull/352#discussion_r1012520961

2022-11-03 06:09 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        /**
with current implementation `0x` will be considerer as a valid CompactBytesArray, I don't think it makes sense. Especially if we move this function to LSP2Utils.

```suggestion
        if(compactBytesArray.length == 0) return false;
        /**
```

2022-11-03 11:18 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            uint256 elementLength = uint256(uint8(bytes1(compactBytesArray[pointer])));
i made this change instead:
`if (elementLength == 0) pointer = compactBytesArray.length + 1;`

2022-11-03 15:03 UTC, YamenMerhi approved these changes

2022-11-04 09:59 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +                foundAllowedKey = true;
As seens with @CJ42 and @YamenMerhi, here `foundAllowedKey` is not necessary and also should `return` instead so that we don't continue within the loop for nothing. If `allowedKey` is found then we don't need to check the other keys and should just return to save on gas.
I think we should remove the `foundAllowedKey` variable from function and return instead

2022-11-04 10:39 UTC, CJ42 requested changes
added comments

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error NoERC725YDataKeysAllowed();
is this custom error really necessary?
Why don't we simply re-use the custom error we had before?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/31145285/199945140-1ebbee5b-6383-4968-bcf2-1603fabcbc83.png">

Since we reverted the logic (= nothing is allowed if nothing is set), now if a caller is given the permission `SETDATA`, it MUST be given some allowed data keys as well to make its permissions work. So if nothing is listed under its allowed ERC725Y data keys and the caller is trying to `setData(...)`, then the data key provided as input is not allowed in the end.

Unless you see a specific reason and argument to states to the caller "you have no data keys allowed".

I guess it depends on the perspective, but it feels a bit strange imo.

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * on the linked target
Minor but can probably put that on the same line as the Natspec comment above

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        bytes memory allowedERC725YKeysCompacted = ERC725Y(target).getAllowedERC725YKeysFor(from);
Very nice variable name with the word "Compacted" in it 👌

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            //bytes32 allowedKey = bytes32(allowedERC725YKeysCompacted[pointer + 1:pointer + 1 + length]);
this line can be deleted (commented code)

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
maybe we can remove this blank like, to put the variable `allowedERC725YKeysCompacted` and the call to the internal function `_verifyAllowedERC725YKeys(...)` next to each other :)

See the difference in the screenshot below.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/31145285/199948939-ea69eab1-7c68-4175-b814-fb3ab6467b7e.png">

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * @dev Verify if the `inputKey` is present in `alloedERC725KeysCompacted` stored on the `from`'s ERC725Y contract
```suggestion
     * @dev Verify if the `inputKey` is present in `allowedERC725KeysCompacted` stored on the `from`'s ERC725Y contract
```

2022-11-04 10:39 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _verifyAllowedERC725YSingleKey(address from, bytes32 inputKey, bytes memory allowedERC725YKeysCompacted) internal pure {
We can refactor this function like this:

- we can remove the variable `foundAllowedKey`, and `return` directly as soon as we find a match.
<img width="394" alt="image" src="https://user-images.githubusercontent.com/31145285/199949626-e7daeaee-32cb-40e8-883b-268cb3b547cc.png">

- this below can be removed, since we don't allow a single byte length of `0`

<img width="524" alt="image" src="https://user-images.githubusercontent.com/31145285/199949879-44831b3f-046f-4a60-9976-052ab1a4d6ce.png">

- If we did not find anything, after the `while` loop, we revert.

```solidity
/**
     * @dev Verify if the `inputKey` is present in `allowedERC725KeysCompacted` stored on the `from`'s ERC725Y contract
     */
    function _verifyAllowedERC725YSingleKey(address from, bytes32 inputKey, bytes memory allowedERC725YKeysCompacted) internal pure {
        if (allowedERC725YKeysCompacted.length == 0) revert NoERC725YDataKeysAllowed();
        if (!LSP2Utils.isValidCompactBytesArray(allowedERC725YKeysCompacted)) revert InvalidCompactBytesArray(allowedERC725YKeysCompacted);

        /**
         * pointer will always land on these values:
         *
         * ↓↓
         * 03 a00000
         * 05 fff83a0011
         * 20 aa0000000000000000000000000000000000000000000000000000000000cafe
         * 12 bb000000000000000000000000000000beef
         * 19 cc00000000000000000000000000000000000000000000deed
         * ↑↑
         *
         * the pointer can only land on the length of the following bytes value.
         */
        uint256 pointer;

        /**
         * iterate over each key by saving in the `pointer` variable the index for
         * the length of the following key until the `pointer` reaches an undefined value
         *
         * 0x 03 a00000 03 fff83a 20 aa00...00cafe
         *    ↑↑        ↑↑        ↑↑
         *  first  |  second  |  third
         *  length |  length  |  length
         */
        while (!foundAllowedKey && pointer < allowedERC725YKeysCompacted.length) {
            /**
             * save the length of the following allowed key
             * which is saved in `allowedERC725YKeys[pointer]`
             */
            uint256 length = uint256(uint8(bytes1(allowedERC725YKeysCompacted[pointer])));

            /*
             * transform the allowed key situated from `pointer + 1` until `pointer + 1 + length` to a bytes32 value
             * E.g. 0xfff83a -> 0xfff83a0000000000000000000000000000000000000000000000000000000000
             */
            bytes32 allowedKey = bytes32(allowedERC725YKeysCompacted.slice(
                pointer + 1,
                length
            ));

            /**
             * the bitmask discard the last `32 - length` bytes of the input key via ANDing &
             * so to compare only the relevant parts of each ERC725Y keys
             *
             * E.g.:
             *
             * allowed key = 0xa00000
             *
             *      &     compare this part
             *                 vvvvvv
             * checked key = 0xa00000cafecafecafecafecafecafecafe000000000000000000000011223344
             *
             *                                              discard this part
             *                       vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
             *        mask = 0xffffff0000000000000000000000000000000000000000000000000000000000
             */
            bytes32 mask = bytes32(
                0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
            ) << (8 * (32 - length));

            if (allowedKey == (inputKey & mask)) {
                return;
            } else {
                // move the pointer to the first index of the first fixed key
                pointer += length + 1;
            }
        }

        revert NotAllowedERC725YKey(from, inputKey);
    }
```

2022-11-04 10:39 UTC, CJ42 commented on tests/utils/helpers.ts
> +export function encodeCompactedBytes(inputKeys: BytesLike[]) {
suggesting renaming:

```suggestion
export function encodeCompactBytesArray(inputKeys: BytesLike[]) {
```

2022-11-04 10:39 UTC, CJ42 commented on tests/utils/fixtures.ts
> +        ethers.utils.hexZeroPad(PERMISSIONS.SUPER_SETDATA, 32),
nice, will help to better benchmark gas costs 👌

2022-11-04 10:39 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionSetData.test.ts
> +      describe("For address that has permission SETDATA with AlloedERC725YDataKeys", () => {
```suggestion
      describe("For address that has permission SETDATA with AllowedERC725YDataKeys", () => {
```

2022-11-04 10:39 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionSetData.test.ts
> +      // move on with the test
```suggestion

```

2022-11-04 10:51 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error NoERC725YDataKeysAllowed();
We use this error only when caller has zero AllowedERC725YKeys. I might be misleading to get revert error `NotAllowedERC725YKey(..)` whenever you have nothing allowed. Receiving `NoERC725YDataKeysAllowed(..)` error can be more insightful in some situations.

2022-11-04 11:03 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error NoERC725YDataKeysAllowed();
Yep technically in both cases we can use `NotAllowedERC725YKey` because the input key cannot be set either because there is no keys allowed at all, or because the input key is not part of the allowedERC725YKeyCompacted, but i think that in case there is no allowedERC725YCompacted keys in the storage its more precise to point to this case because it's a cause of `NotAllowedERC725YKey`.

If we have this seperation and i got:
- `NotAllowedERC725YKey` i know that there is a list of allowedERC725YKey in the storage of the UP but the input key that i am providing is not part of them.
- `NoAllowedERC725YKey` i know that there is nothing in the `allowedERC725YKey` of the storage of UP. that's why setting the input key was reverted

2022-11-04 11:12 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error NoERC725YDataKeysAllowed();
yes I think it is disputable, only thing is that for allowed calls permissions we are using the generic `NotAllowedCall` error when there are no allowed calls or when the call is not in the list of allowed calls permission. We could also implement a new custom error `NoCallsAllowed` when the allowed calls permission is empty. 
I am fine with both but I think we should be consistent with the behaviors between allowed calls and allowed keys. If we implement `NoAllowedERC725YKey` we should as well implement `NoAllowedCalls`

2022-11-04 11:15 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error NoERC725YDataKeysAllowed();
when introducing a specific custom error for when the permission is empty: 
cons: 
- more bytecode at deployment
pro: 
- more precise and also I believe more efficient at runtime since we are not returning any params

2022-11-04 11:24 UTC, skimaharvey approved these changes

2022-11-04 12:56 UTC, CJ42 reviewed
added 2nd round of review comments

2022-11-04 12:56 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +     * @dev verify the permissions of the _from abddress that want to interact with the `target`
```suggestion
     * @dev verify the permissions of the _from address that want to interact with the `target`
```

2022-11-04 12:56 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionSetData.test.ts
> +        "0x562d53c1631c0c1620e183763f5f6356addcf78f26cbbd0b9eb7061d7c897ea1",
name this variable `hardcodedDataKey` (some that we know it comes from a hardcoded value in the Solidity contract.

2022-11-04 12:56 UTC, CJ42 commented on tests/LSP6KeyManager/internals/AllowedERC725YKeys.internal.ts
> +      it("Verifying the validity of a CompactBytesArray containing 2 dynamic keys", async () => {
Please explain what it should return (`true` or `false`).

```suggestion
      it("should return true for a CompactBytesArray containing 2 dynamic keys", async () => {
```

2022-11-04 12:56 UTC, CJ42 commented on tests/LSP6KeyManager/internals/AllowedERC725YKeys.internal.ts
> +      dataKeysToCheck = [
Not so important, but maybe to clarify:

```suggestion
      dataKeysToRevert = [
```

2022-11-04 12:56 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
>        describe("when caller is an address with permission SETDATA + CHANGEPERMISSIONS", () => {
```suggestion
      describe("when caller is an address with permission SETDATA + CHANGEPERMISSIONS + no Allowed ERC725Y Keys", () => {
```

2022-11-04 12:58 UTC, CJ42 requested changes

2022-11-04 14:16 UTC, CJ42 approved these changes

2022-11-04 14:16 UTC, merged

2022-11-08 19:56 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionChangeAddPermissions.test.ts
> +        it("(should fail): 2 x keys + add 2 x new permissions + increment AddressPermissions[].length by +2", async () => {
this test should not have been changed, but re-adapted in the`before` setup. As now, we do not have any tests to test if it works.

2022-11-08 19:56 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionSetData.test.ts
> +      describe("For address that has permission SETDATA without any AllowedERC725YDataKeys", () => {
nice perfect 👌

2023-04-08 10:25 UTC, CJ42 commented on contracts/Helpers/KeyManager/KeyManagerInternalsTester.sol
> +        return true;
@b00ste I missed this change while reviewing. This should have never been changed like this.

The point of this file and functions is to expose the `internal` functions publicly so they can be tested via unit tests.
Neither the `verifyAllowedERC725YSingleKey`, nor the `verifyAllowedERC725YKeys` functions return a `boolean` inside the KeyManagerCore.

We should simply test if the check pass (= don't revert), or fail (= revert).

These functions (and their unit tests in TS) **must be exactly the same as it is in the Key Manager Core.**