refactor: optimise `_verifyAllowedERC725YKeys` and properly test bytes32(0) key
lukso-network/lsp-smart-contracts pull request #357
Opened 2022-11-07 17:15 UTC by b00ste

## What does this PR introduce?

- Optimising `_verifyAllowedERC725YKeys` so it is more gas efficient.

2022-11-08 19:25 UTC, CJ42 requested changes

2022-11-08 19:25 UTC, CJ42 commented on tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
> +        it(`should revert when trying to set any random data key (e.g: ${testCase.datakeyToSet})`, async () => {
Maybe we can encapsulate this in a `describe` block?

```suggestion
describe("should revert when trying to set any random data key that is not in the list of AllowedERC725YKeys")
        it(`e.g: ${testCase.datakeyToSet})`, async () => {
```

2022-11-08 19:25 UTC, CJ42 commented on tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
> +          if (
Why do we have a `if / else` block inside the tests?
We should not have such conditionals inside the tests imo, as this will end up making it:
- very hard to maintain
- very hard to debug if it fails in the CI.

We should create a separate test here, especially in the case pf the zero data key.

Especially as now, the name of the test states "any random data key", but the data key tested is not random at it is the zero data key.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/31145285/200656248-c3f599ee-7b98-46a1-9421-f1db4752ab26.png">

Please put this in a separate test, so that we can easily find it 🙏

2022-11-08 19:25 UTC, CJ42 commented on tests/LSP6KeyManager/tests/AllowedERC725YKeys.test.ts
> +      it("should pass when trying to set an array of data keys including bytes32(0)", async () => {
I think there is an error here. It states "should pass" but inside the test, it tests that it reverts.

```suggestion
      it("should revert when trying to set an array of data keys including bytes32(0)", async () => {
```

2022-11-08 19:31 UTC, CJ42 commented
@b00ste @YamenMerhi @skimaharvey 
We need to describe it very explicitly. Both in the tests + the Solidity file that "**we currently do not allow to set the zero data key**".

But this might change in the future.

Because I do imagine a use case where someone want to:

- set a value for the data key: `0x00000000...00000000`.
- set a value for a data key / or have an allowed ERC725Y data key that starts with a certain number of leading zero bytes.
_example:_ input data key = `0x00000000abcdefabcdef...`, so in the allowed ERC725Y data keys, we have as one of the entry 

```
length
v 
0400000000
  ^^^^^^^^^
  anything starting with `0x00000000`
```

2022-11-08 21:55 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
instead of checking the isCompactBytesArray before the while loop, on line 550 we could add a check: 
`if(lengths += length > allowedERC725YKeysCompacted.length) revert InvalidEncodedAllowedERC725YKeys(allowedERC725YKeysCompacted)`

2022-11-08 21:59 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
you cannot be 100% sure that the loop will iterate over all AllowedERC725YKeys, it might end on the first key and the CompactBytesArray can still be invalid.

2022-11-08 22:05 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
yes but I think this is what we discussed with Fabian this morning. Even when checking the lengths we cannot be sure they are valid

2022-11-08 22:07 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
may be I misunderstood @CJ42 @YamenMerhi

2022-11-08 22:08 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
in the case of the lsp2 check we have a valid CompactBytesArray, in this case we don’t have even that. i am not sure this is the way to check it

2022-11-08 22:11 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
yes we have a valid `CompactBytesArray` but may be not a valid keys and looping twice of the `allowedERC725YKeysCompacted` is expensive as discussed this morning

2022-11-08 22:40 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
should we add a check here that prevents having a length of over 32 to avoid an overflow error? @b00ste @CJ42 @YamenMerhi

2022-11-08 22:42 UTC, skimaharvey commented
> > @b00ste @YamenMerhi @skimaharvey We need to describe it very explicitly. Both in the tests + the Solidity file that "**we currently do not allow to set the zero data key**".
> > ⚠️ But this might change in the future.
> > Because I do imagine a use case where someone want to:
> > 
> > * set a value for the data key: `0x00000000...00000000`.
> > * set a value for a data key / or have an allowed ERC725Y data key that starts with a certain number of leading zero bytes.
> >   _example:_ input data key = `0x00000000abcdefabcdef...`, so in the allowed ERC725Y data keys, we have as one of the entry
> > 
> > ```
> > length
> > v 
> > 0400000000
> >   ^^^^^^^^^
> >   anything starting with `0x00000000`
> > ```
> 
> In the current implementation we can set dynamic keys which are bytes1(0) … bytes31(0), the only one that is not allowed is bytes32(0)

hey @b00ste, where is this check made? with the dynamic bytes can't we set a length of 32 and bytes32(0) as a corresponding bytes?

2022-11-08 23:06 UTC, YamenMerhi commented
Can we add a test case where:
- You have under your allowedERC725YKey the bytes32(0) dataKey as allowed key.
- Try to set a random key and see if it passes or not.

2022-11-08 23:08 UTC, b00ste commented
> Can we add a test case where:
> 
> * You have under your allowedERC725YKey the bytes32(0) dataKey as allowed key.
> * Try to set a random key and see if it passes or not.

we have test for that already

2022-11-08 23:14 UTC, b00ste commented
> > > @b00ste @YamenMerhi @skimaharvey We need to describe it very explicitly. Both in the tests + the Solidity file that "**we currently do not allow to set the zero data key**".
> > > ⚠️ But this might change in the future.
> > > Because I do imagine a use case where someone want to:
> > > 
> > > * set a value for the data key: `0x00000000...00000000`.
> > > * set a value for a data key / or have an allowed ERC725Y data key that starts with a certain number of leading zero bytes.
> > >   _example:_ input data key = `0x00000000abcdefabcdef...`, so in the allowed ERC725Y data keys, we have as one of the entry
> > > 
> > > ```
> > > length
> > > v 
> > > 0400000000
> > >   ^^^^^^^^^
> > >   anything starting with `0x00000000`
> > > ```
> > 
> > 
> > In the current implementation we can set dynamic keys which are bytes1(0) … bytes31(0), the only one that is not allowed is bytes32(0)
> 
> hey @b00ste, where is this check made? with the dynamic bytes can't we set a length of 32 and bytes32(0) as a corresponding bytes?

Line 1770 in the tests, that’s what we do there, we have the bytes32(0) key as an allowed key and we still revert, as discussed. we revert for random keys as well and for bytes31(0) dynamic key because those are not part of AllowedERC725YKeys

2022-11-09 09:20 UTC, YamenMerhi approved these changes

2022-11-09 09:43 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
TBD: https://app.clickup.com/t/3ua07je

2022-11-09 12:37 UTC, CJ42 approved these changes

2022-11-09 12:43 UTC, merged