feat: introduce batch `execute(bytes[])` and`executeRelayCall(bytes[],uint256[],bytes[])` on the LSP6 Key Manager
lukso-network/lsp-smart-contracts pull request #367
Opened 2022-11-11 16:10 UTC by CJ42

2022-11-17 13:14 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        for (uint256 ii = 0; ii <= payloads.length - 1; ii++) {
why `payloads.length - 1`? also should we not store the calculation in a memory variable instead of doing at each step?

2022-11-17 13:28 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +                results[ii] = _execute(payloads[ii], msg.value);
I think it could interesting to add a test where: 
- I call `execute(bytes[] calldata payloads)` with a value 
- one of my payload, will call the execute function of the UP which will call back this function.
I think it could renter with the same`msg.value` ? @CJ42

2022-11-17 13:58 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        for (uint256 ii = 0; ii <= payloads.length - 1; ii++) {
cleaner `uint256 ii; ii < payloads.length; ii++`

2022-11-17 13:59 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        for (uint256 ii = 0; ii <= payloads.length - 1; ii++) {
yes this might be a bit cheaper. I can try it out.

2022-11-17 15:08 UTC, YamenMerhi reviewed
Cool, Initially looks good to me! Would be good to add more tests, such as 
- If one payload reverts at first and last it reverts with `executeRelayCall` and `execute`
- Trying to pass an array of same signature would fail in `executeRelayCall`
- If we are sending value and the first payload is setData, it reverts,
- etc ..

2022-11-17 21:20 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        for (uint256 ii = 0; ii <= payloads.length - 1; ii++) {
Yes also we are using the batch `executeRelayCall`func we are using `uint256 ii; ii < payloads.length; ii++`. I think out of consistency we should use the same

2022-11-17 21:30 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6Constants.sol
> +bytes4 constant _LSP6_EXECUTE_RELAYCALL_BATCH_SELECTOR = 0x4edb7c01;
i dont think `_LSP6_EXECUTE_BATCH_SELECTOR`, `_LSP6_EXECUTE_RELAYCALL_SELECTOR` and `_LSP6_EXECUTE_BATCH_SELECTOR` are used anywhere

2022-11-17 21:30 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    ) public payable returns (bytes[] memory) {
do you think we should add a check that all parameters`.length` are equal?
@CJ42 @YamenMerhi @b00ste

2022-11-17 21:36 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    ) public payable returns (bytes[] memory) {
for example I send 3 `signature`, 3 `nonce` and 2 `payload`. Since we look depending on the `payloads.length`, we will not loop over the last `signatures` and `nonces`.

2022-11-17 21:43 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
>          emit Executed(msg.value, bytes4(payload));
I think we should use `msgValue` instead of `msg.value`?

2022-11-18 09:23 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    ) public payable returns (bytes[] memory) {
I think we should verify that all the arrays have the same length as we do in `batchTransfer(..)` in LSP7 & LSP8 out of consistency

2022-11-18 09:25 UTC, b00ste approved these changes
I think we should check the array lengths in `executeRelayCall(bytes[],uint256[],bytes[])` otherwise LGTM
Also the test are interesting, maybe we can think of some other interesting scenarios

2022-11-18 11:28 UTC, skimaharvey approved these changes
Nice

2022-11-18 14:09 UTC, skimaharvey requested changes
see thread on SC channel

2022-11-24 10:35 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        }
how about checking the values array length as well?

2022-11-24 10:41 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +
I am not sure why we just simply add up all the values and make sure that they add up?
something like this
```js
        uint256 totalValues;

        for (uint256 ii; ii < payloads.length; ii = GasLib.uncheckedIncrement(ii)) {

            results[ii] = _executeRelayCall(signatures[ii], nonces[ii], payloads[ii], values[ii]);
            totalValues += values[ii]
        }
        if (totalValues != msg.value){revert  CustomError}
   ```

2022-11-24 10:46 UTC, skimaharvey requested changes

2022-11-24 10:46 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +    function _execute(bytes calldata payload, uint256 msgValue) internal returns (bytes memory) {
I think we should start with msgValue and the payload

2022-11-24 10:56 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        }
same comment as: https://github.com/lukso-network/lsp-smart-contracts/pull/367/files#r1031359410

2022-11-24 11:29 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error LSP6BatchInsufficientMsgValue(uint256 totalValues, uint256 msgValue);
I would be nice to have more or less similar naming for this and the following custom error.
```suggestion
error LSP6BatchInsufficientValueSent(uint256 totalValues, uint256 msgValue);
```

2022-11-24 11:29 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error LSP6BatchCannotLeaveFundsOnKeyManager(uint256 totalValues, uint256 msgValue);
```suggestion
error LSP6BatchExcessiveValueSent(uint256 totalValues, uint256 msgValue);
```

2022-11-24 13:01 UTC, YamenMerhi approved these changes

2022-11-24 13:03 UTC, b00ste approved these changes
LGTM 😎

2022-11-24 13:09 UTC, skimaharvey approved these changes

2022-11-24 14:35 UTC, merged