feat!: Add LSP17 FallbackExtension implementation in LSP0 & LSP9
lukso-network/lsp-smart-contracts pull request #369
Opened 2022-11-16 22:39 UTC by YamenMerhi

## What does this PR introduce?

- Modifying the fallback function of the LSP0 and LSP9 to have the logic of LSP17FallbackExtension + emitting the `ValueReceived` event in case `msg.value > 0`.

### The fallback function behavior:

**- A)** If `msg.value` > 0 emit `ValueReceived` event.

**- B)** If `msg.data.length  < 4` or `msg.sig == bytes4(0)` don't check for extension, just return

**- C)** If `msg.data.length > 4 && msg.sig != bytes4(0)`:

        - C-1) Construct the data key relevant for the `msg.sig` received

        - C-2) Check in the storage if there is an address stored under the data key constructed
        
        - C-3) If `addressRetreived == address(0)` return
        
        - C-4) If `addressRetreived != address(0)`:

                 - C-4-1)

2022-11-17 09:13 UTC, frozeman commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +                    let success := call(gas(), extension, 0, 0, add(calldatasize(), 52), 0, 0)
maybe we should forward gas - what we need to execute the rest statements below.

2022-11-17 09:14 UTC, frozeman commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +
Wouldn't it be better to make LSP17 a utils contract used in both, LSP0 and LSP9?

2022-11-17 09:14 UTC, frozeman approved these changes

2022-11-17 22:18 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * to a function selector. If there is no extension stored under the data key, return.
may be "appended by". You use "with" on like 101. I am not sure neither. Probably will need @CJ42 gramarly input

2022-11-17 22:18 UTC, skimaharvey commented on contracts/LSP17FallbackExtensions/LSP17FallbackExtension.sol
> +     * Returns the return value on success and revert in case of failure.
i dont think this is correct? `fallback` functions do not return, also `_fallbackExtension()` doesn't? wdut @YamenMerhi @b00ste @CJ42

2022-11-17 22:18 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Returns the return value on success and revert in case of failure.
i dont think `fallback()` can return

2022-11-18 13:22 UTC, b00ste approved these changes

2022-11-18 14:14 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Returns the return value on success and revert in case of failure.
You can write the return using inline assembly, like i did

2022-11-20 23:56 UTC, skimaharvey approved these changes
LGTM if we decide to go/go exclusively for `call` 🚀

2022-11-20 23:56 UTC, skimaharvey commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +        // Up to the implementor contract to return an extension based on a function selector
hmmm I am not sure about this because without this, everything after line 48 wont work. It is a must be overridden.
I saw that you implemented them in LSP0 and LSP9 but may be we should `revert` here just so the devs knows why its extensions don't work.

2022-11-22 09:47 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * to a function selector. If there is no extension stored under the data key, return.
Suggestion:

```
Forwards the call to an extension contract (address). This address can be retrieved from the ERC725Y data key-value store using the data key below (function selector appended to the prefix): 

_LSP17_FALLBACK_EXTENSIONS_HANDLER_ + <function-selector>

If there is no extension stored under the data key, return.
```

2022-11-22 10:38 UTC, CJ42 requested changes
added first round of review

2022-11-22 10:38 UTC, CJ42 commented on contracts/Helpers/FallbackExtensions/CheckerExtension.sol
> +        if (msg.data.length != 120) revert();
I am not sure to understand this check.

Since the value parameters are `address` and `uint256`, they are direct types. So there should not be any offset in the calldata.

The calldata should be made of just the `bytes4` of the selector + bytes32 words padded for each arguments.

![image](https://user-images.githubusercontent.com/31145285/203285250-3914b89d-d92f-422e-83f1-ee0af5f43654.png)

![image](https://user-images.githubusercontent.com/31145285/203285299-bb25f837-aae5-4f4b-99c9-7b3efb32ba94.png)

So the calldata here is 68 bytes, not 120.

```
0xe825d37d000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000000000000000000000000000000000000000000c8
```

2022-11-22 10:38 UTC, CJ42 commented on contracts/Helpers/FallbackExtensions/CheckerExtension.sol
> +            address(bytes20(msg.data[msg.data.length - 52:msg.data.length - 32]))
Here the end of the slice is not necessarily needed, since the `bytes20(...)` casting will cut the first 20 bytes.

```suggestion
            address(bytes20(msg.data[msg.data.length - 52:]))
```

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +    function _getExtension(bytes4 functionSelector) internal view virtual returns (address) {
I am not in favour of this.
This can be easily forgotten.

The best way to ensure that the function is implemented is by not making the compiler compile if the function is not implemented.

We can simply write the function definition and end it with a semicolon, removing the whole function body.

```suggestion
    function _getExtension(bytes4 functionSelector) internal view virtual returns (address);
```

If the contract inherits this contract and the function is not implemented, it will not compile, forcing the developer to implement the function.

We can adjust the comments by putting the comment inside the function above the function definition.

```solidity
/**
     * @dev Returns the extension mapped to a specific function selector
     * If no extension was found, return the address(0)
     * To be overrided.
     * Up to the implementor contract to return an extension based on a function selector
     */
    function _getExtension(bytes4 functionSelector) internal view virtual returns (address);
```

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> + * to an extension mapped to the function selector being called, set originaly by the parent contract
```suggestion
 * to an extension mapped to the function selector being called, set originally by the parent contract
```

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +    // solhint-disable
why is this solhint disable comment needed here?

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +     * The call to the extension is appended with bytes20 (msg.sender) and bytes32 (msg.value).
The comment here is incorrect. 

The call to the extension is appended by an `address` and a `uint256` ✅ 
Not a `bytes20` and a `bytes32` ❌ 

The difference here is very important because of the padding. 

Especially between:

- `address` (padded on the left).

![Screenshot 2022-11-22 at 10 30 34](https://user-images.githubusercontent.com/31145285/203292165-04e5c4da-1a45-4190-a158-f393be4fe577.png)



- `bytes20` (padded on the right).

![image](https://user-images.githubusercontent.com/31145285/203292131-d60cecbb-3b49-4ef0-a65a-1e33547dae0f.png)

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +        else {
The `else` here is not needed. Can be removed.

2022-11-22 10:38 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +            else {
Same here, the `else` is not needed because the previous statement `return`.

2022-11-22 10:42 UTC, skimaharvey commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +    function _getExtension(bytes4 functionSelector) internal view virtual returns (address) {
nice way.

2022-11-22 10:45 UTC, YamenMerhi commented on contracts/Helpers/FallbackExtensions/CheckerExtension.sol
> +        if (msg.data.length != 120) revert();
There is comments already explaining the purpose of the function:
```
// Checks that the msg.sender + msg.value are appended to the msg.data
// Length should be: 4 + 32 + 32 + 20 + 32
```

2022-11-22 10:46 UTC, YamenMerhi commented on contracts/Helpers/FallbackExtensions/CheckerExtension.sol
> +            address(bytes20(msg.data[msg.data.length - 52:msg.data.length - 32]))
Just want to make sure to point that the original msg.sender is from the point x till the point y

2022-11-22 10:48 UTC, YamenMerhi commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +     * The call to the extension is appended with bytes20 (msg.sender) and bytes32 (msg.value).
We don't have padding, we already removed the padding in the fallback function. So it's just bytes20 and bytes32 **appended** to the calldata without any offset or zeropad

2022-11-22 10:57 UTC, YamenMerhi commented on contracts/Helpers/ERC165Interfaces.sol
> +        bytes4 interfaceId = bytes4(keccak256(abi.encodePacked("LSP17Extendable")));
Yes, same for the LSP17Extension, no public function, just a behavior

2022-11-22 14:48 UTC, CJ42 approved these changes

2022-11-22 14:48 UTC, merged