refactor: Create an interface for LSP14
lukso-network/lsp-smart-contracts pull request #400
Opened 2022-12-16 10:26 UTC by b00ste

## What does this PR introduce?

In this PR the ILSP14Ownable2Step is created, to be used in other contracts.

2022-12-16 13:55 UTC, YamenMerhi commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +
I suggest we add owner function in here

2022-12-16 13:55 UTC, YamenMerhi commented on contracts/Helpers/ERC165Interfaces.sol
> +            ILSP14Ownable2Step.pendingOwner.selector ^
You can do `OwnableUnset.owner.selector` ^ `type(ILSP14).interfaceId`

2022-12-16 13:55 UTC, YamenMerhi commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Initiate the process of renouncing ownerhsip or confirm the renouncement of the contract
My suggestion: 
> Initiate the process of renouncing ownerhsip on the first call and confirm the renouncement of the ownership on the second call

2022-12-16 13:55 UTC, YamenMerhi commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Initiate the process of transferring ownership of the contract
My suggestion:
> Initiate the process of transferring ownership of the contract by setting the pending owner

2022-12-16 13:55 UTC, YamenMerhi commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> + * @dev Modified version of OwnableUnset contract in which, tarnsferring or renouncing ownership
transferring*

2022-12-16 16:10 UTC, CJ42 requested changes
added review comments

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> + * @dev Modified version of OwnableUnset contract in which, tarnsferring or renouncing ownership
```suggestion
 * @dev Extended version of Ownable (EIP173) in which, transferring or renouncing ownership
```

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +    event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner);
Should we have the `OwnershipTransferred` event defined in the interface as well?

@YamenMerhi @skimaharvey @b00ste

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +
Agree it should be added as well.

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev emitted whenever the `transferOwnership(..)` 2-step process is started
Suggested changes.

```suggestion
     * @dev emitted when starting the `transferOwnership(..)` 2-step process.
```

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev emitted whenever the `renounceOwnership(..)` 2-step process is started
Suggested changes

```suggestion
     * @dev emitted when starting the `renounceOwnership(..)` 2-step process.
```

2022-12-16 16:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Initiate the process of accepting ownership of the contract
I don't agree with this definition.
This does not initiate the process. It finalizes it.

```suggestion
     * @dev Complete the process of transferring ownership. MUST be called by the pendingOwner.
```

2022-12-17 15:34 UTC, skimaharvey commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +    event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner);
I believe it is usually a good practice to include struct and events in the interfaces

2022-12-19 11:21 UTC, skimaharvey approved these changes

2022-12-19 14:18 UTC, CJ42 approved these changes

2022-12-19 14:21 UTC, merged