Lsp2 utils/update generate array element key at index
lukso-network/lsp-smart-contracts pull request #404
Opened 2022-12-17 15:01 UTC by skimaharvey

## What this PR introduce? 

- [x] Change index param to `uint128` for the  `generateArrayElementKeyAtIndex(...)` function
- [x] Add checks to prevent cast errors when casting bytes down

2022-12-17 15:25 UTC, skimaharvey commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            if (newArrayLength > type(uint64).max) {
The reason here I am comparing to `uint64` is because on line 102 we cast down to bytes8 and to avoid overriding keys

2022-12-19 08:32 UTC, b00ste approved these changes

2022-12-20 15:17 UTC, CJ42 approved these changes

2022-12-20 15:17 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +                oldArrayLength128
since we are using the variable only once, we can inline to avoid keeping track of it on the stack.

```suggestion
                uint128(oldArrayLength128)
```

2022-12-20 15:17 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            uint128 oldArrayLength128 = uint128(oldArrayLength);
this variable can be removed and inlined. See comment below.

2022-12-20 16:41 UTC, YamenMerhi approved these changes

2022-12-20 17:28 UTC, CJ42 requested changes
@skimaharvey you need to add the latest changes from `develop` so that the last CI job runs.

2023-01-04 14:47 UTC, CJ42 approved these changes

2023-01-04 14:47 UTC, merged