refactor!:  [WP-I16] Revert instead of return when no extension exist in LSP17
lukso-network/lsp-smart-contracts pull request #433
Opened 2023-01-11 10:10 UTC by YamenMerhi

## What does this PR introduce?
### Breaking Changes 🚫 
- Change the LSP17 logic to revert when there is no extension for the function selector being called 
- If the first 4 bytes are plain 4 zero bytes, the call is allowed and it just return, this check allow sending graffiti to not be checked against an extension.

### New Behavior  
- LSP0 & LSP9 now revert if the function selector being called with doesn't have an extension
- If the call to LSP0 & LSP9 is prepended with 4 bytes(0), the call is allowed and we just return.

2023-01-11 13:37 UTC, skimaharvey approved these changes

2023-01-11 14:39 UTC, b00ste approved these changes

2023-01-12 09:41 UTC, CJ42 requested changes
The changes looks good. Added some review comments

2023-01-12 09:41 UTC, CJ42 commented on constants.js
> +			error: 'NoExtensionForFunctionSelector(bytes4)',
maybe we could rename it to?

```suggestion
			error: 'NoExtensionFoundForFunctionSelector(bytes4)',
```

2023-01-12 09:41 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Errors.sol
> +error NoExtensionForFunctionSelector(bytes4 functionSelector);
As suggested above in the `constants.js`

```suggestion
error NoExtensionFoundForFunctionSelector(bytes4 functionSelector);
```

2023-01-12 09:41 UTC, CJ42 commented on contracts/LSP17ContractExtension/LSP17Extendable.sol
> +     * @dev Forwards the call to an extension mapped to a function selector. If the address of
Suggested comment change

```suggestion
     * @dev Forwards the call to an extension mapped to a function selector. If no extension address 
     * is mapped to the function selector (address(0)), then revert.
```

2023-01-12 09:41 UTC, CJ42 commented on tests/LSP16UniversalFactory/LSP16UniversalFactory.test.ts
> +          "0x00000000aabbccdd",
We could add an extra comment here to describe that it is just some random data sent along.

```suggestion
            "0x00000000aabbccdd", // send some random data along prepended with `
0x00000000`
```

2023-01-12 09:41 UTC, CJ42 commented on tests/LSP17ContractExtension/LSP17Extendable.behaviour.ts
> +        describe("when the payload is equal to 4 bytes of zeros", () => {
```suggestion
        describe("when the payload is `0x00000000`", () => {
```

2023-01-12 09:41 UTC, CJ42 commented on tests/LSP17ContractExtension/LSP17Extendable.behaviour.ts
> +        describe("when the payload is larger than 4 bytes of zeros", () => {
Suggested improvement in the description of the test

```suggestion
        describe("when the payload is `0x00000000` + some random data ('graffiti')", () => {
```

2023-01-12 17:37 UTC, CJ42 approved these changes

2023-01-12 18:03 UTC, merged