refactor: add check for the payload length in `LSP6KeyManagerCore`
lukso-network/lsp-smart-contracts pull request #449
Opened 2023-01-18 13:14 UTC by b00ste

### What does this PR introduce?

In this PR the following changes are made:
- A new error added, 'InvalidPayload(bytes)'.
- A check added in both internal function, `` and `` in order to verify that the payload is not smaller than 4 bytes.

2023-01-18 15:49 UTC, CJ42 requested changes

2023-01-18 15:49 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionCall.test.ts
> +    describe("when the payload is smaller than 4 bytes", () => {
Could we put this test in the file `OtherScenarios.test.ts` for the Key Manager test suite?

I had already started to draft one test long time ago and left it there skipped. 

Maybe we can also re-arrange this test to ensure this new custom error is returned with an empty payload? :)

https://github.com/lukso-network/lsp-smart-contracts/blob/5f4b9a7b2e224f1536be8d5164f58b57016cafcd/tests/LSP6KeyManager/tests/OtherScenarios.test.ts#L55-L57

2023-01-18 16:16 UTC, skimaharvey approved these changes

2023-01-19 08:24 UTC, YamenMerhi approved these changes

2023-01-19 08:55 UTC, merged