fix: [WP-I6] add `onERC721Received` check for the `safeTransferFrom` functions of `LSP8CompatibleERC721` contracts
lukso-network/lsp-smart-contracts pull request #455
Opened 2023-01-20 13:19 UTC by CJ42

# What does this PR introduce?

## ⚠️ BREAKING CHANGES

In `LSP8CompatibleERC721` and `LSP8CompatibleERC721Init`:

- [x] make the `allowNonLSP1Recipient` parameter set to `true` by default for all transfer functions (`transfer` from LSP8, `transferFrom` and `safeTransferFrom` from ERC721).

- [x] for the `safeTransferFrom` function, add an extra call to check that the token receiver MUST implement the `onERC721Received` function and return the magic value (`onERC721Received(address,address,uint256,bytes)` function selector).

## 🧪 Tests

- [x] add tests for the following scenarios below.

- when `to` is an EOA = ✅ pass  
- when `to`  is a contract that supports + implement LSP1 
    - but does not implement `onERC721Received` = ❌ fail and revert  
    - if it also implements `onERC721Received`, but the function `onERC721Received` reverts = ❌ fails and revert  
    - if it also implements `onERC721Received` , but the function `onERC721Received`  does not return the right bytes value = ❌ fails and revert  
    - if it also implements `onERC721Received` = ✅ pass  

- when `to` is a contract that does not supports LSP1
    - but does not implement `onERC721Received` = ❌ fail and revert  
    - if it also implements `onERC721Received` , but the function `onERC721Received` reverts = ❌ fails and revert  
    - if it also implements `onERC721Received` , but the function `onERC721Received` does not return the right bytes value = ❌ fails and revert  
    - if it also implements `onERC721Received` = ✅ pass

2023-01-21 18:18 UTC, YamenMerhi requested changes
First round of review

2023-01-21 18:18 UTC, YamenMerhi commented on tests/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.test.ts
> +  describe.skip("when using LSP8 contract with proxy", () => {
`.skip`

2023-01-21 18:18 UTC, YamenMerhi commented on contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721InitAbstract.sol
> +                    assembly {
linter error for assembly

2023-01-21 18:18 UTC, YamenMerhi commented on contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol
> +                    assembly {
linter error for assembly

2023-01-24 08:32 UTC, skimaharvey approved these changes

2023-01-24 08:36 UTC, b00ste approved these changes

2023-01-24 08:40 UTC, YamenMerhi approved these changes
LGTM 🚀 What would be a good additional test is to test whether using `transferFrom` or `safeTransferFrom` when `onERC721Received(..)` pass and LSP1 revert, the whole call will revert even if `allowNonLSP1Recipient` is true.

2023-01-24 09:29 UTC, merged