refactor: separate the LSP6 core contract in logic modules
lukso-network/lsp-smart-contracts pull request #461
Opened 2023-01-27 12:48 UTC by b00ste

### What does this PR introduce?

- [ ] Move set data permissions verification logic in `LSP6SetDataLogicModule.sol`
- [ ] Move execute permissions verification logic in `LSP6ExecuteLogicModule.sol`
- [ ] Move ownership transfer permissions verification logic in `LSP6OwnershipLogicModule.sol`
- [ ] Move `getPermissionName(...)` and `requirePermissions(...)` to the `LSP6Utils.sol` for re-usability in modules and core contract.

2023-02-07 09:54 UTC, YamenMerhi commented
Could you try to merge develop, then clone RV internal repo, and run the foundry tests again the new splitted contracts ?

2023-02-14 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            _verifyCanSetData(_target, from, permissions, inputKeys, inputValues);
Maybe `LSP6SetDataLogicModule. _verifyCanSetData` will make it easier to know where the function exist

2023-02-14 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            _verifyCanExecute(_target, from, permissions, payload);
Same here `LSP6ExecuteLogicModule. _verifyCanExecute ` will make it easier to know where the function exists

2023-02-14 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            _verifyOwnershipPermissions(from, permissions);
here

2023-02-14 09:54 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            _verifyCanSetData(_target, from, permissions, inputKey, inputValue);
and here

2023-02-14 09:54 UTC, CJ42 requested changes
added requested changes

2023-02-14 09:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +    {
this is a good idea to put this function here in the `LSP6Utils`. It is useful, "implementation agnostic" and can be reused 👌

2023-02-14 09:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +    ) internal pure {
I am not in favour of having this function in `LSP6Utils`. Because this function does not add any additional functionality to the `library`.  It simply re-uses the same `hasPermission` function from the same library + revert.

I think reverting in a library is ok when it is related to some properties that fail but should be true. For instance taking from OpenZeppelin:
- `Clones.sol`: if cloning a contract fails and return the `address(0)`: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol#L35
- `Create2.sol`: if deploying a contract at a predetermined address but not being able to fund it because of insufficient balance: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Create2.sol#L31
- `Strings.sol`: when converting a number to hex, but the number is `0`: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L68
- `ECDSA.sol`: when some of the properties of the signature (`v.` `r`, `s`, length, etc...) are invalid: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L23-L33

In this case, we force the implementation to revert with the custom error `NotAuthorised`. **But it should be up to the implementation contract really to implement how they want to handle the case if an address does not have some permissions**. For instance, a custom implementation of a Key Manager could:
- revert with a reason string.
- revert with a custom error different than this one (a custom error related to their own protocol).
- not revert but simply return `false` if the controller does not have the permissions, or `true` if it has them.

, but it should be up to the implementation contract (the custom Key Manager being built by the developer) to implement how to handle how they want trevert the way they want (wit how to revert should be up to the implementation

2023-02-14 09:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6LogicModules/LSP6OwnershipLogicModule.sol
> +        LSP6Utils.requirePermissions(
I am not totally convinced about the usefulness of this module 🤔  but ok why not

2023-02-14 10:02 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6LogicModules/LSP6OwnershipLogicModule.sol
> +        LSP6Utils.requirePermissions(
I made it so we can have a very basic example for a module. Basically, to show that you don't have to make complex modules like the ones for `execute(..)` or `setData(..)`

2023-02-14 11:52 UTC, b00ste commented
<img width="786" alt="Screenshot 2023-02-14 at 13 51 54" src="https://user-images.githubusercontent.com/62855857/218730513-04d4fa1e-0b64-416a-a077-e368a1f38de6.png">

2023-02-14 15:14 UTC, YamenMerhi approved these changes

2023-02-14 15:15 UTC, skimaharvey approved these changes

2023-02-14 16:47 UTC, CJ42 approved these changes

2023-02-14 16:47 UTC, merged