perf: reduce LSP1DelegateUP deployment cost + add more tests for LSP1 return values
lukso-network/lsp-smart-contracts pull request #479
Opened 2023-02-21 17:24 UTC by CJ42

# What does this PR introduce?

- refactor LSP1DelegateUP to reduce deployment cost by 15k gas.
- add test to check the returned value of LSP1 when a non-vault contract call the `universalReceiver(...)` function with a LSP9 related typeId

2023-02-22 13:40 UTC, YamenMerhi requested changes
Will continue reviewing after discussiong/ doing action on the requested change

2023-02-22 13:40 UTC, YamenMerhi commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +            (bytes32[] memory dataKeys, bytes[] memory dataValues) = isReceiving
I would suggest either reverting this change or refactoring in a way to have this logic:
```js
            // if the map value is already set, then do nothing
            if (bytes12(notifierMapValue) != bytes12(0))
                return "LSP1: asset received is already registered";
                
            // if there is no map value for the asset/vault to remove, then do nothing
            if (bytes12(notifierMapValue) == bytes12(0))
                return "LSP1: asset sent is not registered";
```

Because currently if a vault is not registered and you are trying to transfer it away, it will revert. Because we are not checking if the asset is not registered. Plus to check if the vault is already registered to avoid setting the same data again for the same vault in another element in the array.

2023-02-24 12:01 UTC, b00ste approved these changes

2023-02-24 13:45 UTC, YamenMerhi approved these changes

2023-02-27 15:37 UTC, merged