refactor!: change `CHANGEPERMISSIONS` to `EDITPERMISSIONS`
lukso-network/lsp-smart-contracts pull request #481
Opened 2023-02-22 11:14 UTC by b00ste

## ⚠️ BREAKING CHANGE!

Changing the name of the `CHANGEPERMISSIONS` permission to `EDITPERMISSIONS`.

2023-02-22 13:32 UTC, YamenMerhi requested changes
We should also change the describe string to match the new name of the permission, at least do a global search and replace.
Check here ⬇️ 
![Screen Shot 2023-02-22 at 3 30 56 PM](https://user-images.githubusercontent.com/86341666/220634495-8b10b17e-cc4c-4b1c-ae82-41e390b45edf.png)

2023-02-23 08:55 UTC, YamenMerhi approved these changes

2023-02-23 09:45 UTC, skimaharvey approved these changes

2023-02-24 08:40 UTC, CJ42 approved these changes

2023-02-24 08:40 UTC, merged