feat: add basic implementation of LSP20ReverseVerification in LSP0
lukso-network/lsp-smart-contracts pull request #488
Opened 2023-03-06 10:06 UTC by YamenMerhi

## What does this PR introduce ?
- Add basic implementation of LSP20 in LSP0.
- Add tests

2023-03-06 11:23 UTC, CJ42 reviewed
1st round of review

2023-03-06 11:23 UTC, CJ42 commented on contracts/LSP20ReverseVerification/LSP20ReverseVerification.sol
> +            bytes32 magicValue = abi.decode(returnedData, (bytes32));
need to test if `returnData` is more than 32 bytes (e.g: 33 bytes, 50 bytes). Need to make sure that `abi.decode` does not revert.

2023-03-06 11:23 UTC, CJ42 commented on tests/UniversalProfile.behaviour.ts
> +import { ethers, network } from "hardhat";
```suggestion
import { ethers } from "hardhat";
```

2023-03-06 11:23 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +  universalProfile: UniversalProfile;
```suggestion
  universalProfile: UniversalProfile | LSP0ERC725Account;
```

2023-03-06 11:23 UTC, CJ42 commented on tests/UniversalProfile.test.ts
> +            reverseVerificationContext.universalProfile as LSP0ERC725Account,
```suggestion
            reverseVerificationContext.universalProfile,
```

2023-03-07 23:36 UTC, CJ42 reviewed
2nd round of review @YamenMerhi

2023-03-07 23:36 UTC, CJ42 commented on tests/UniversalProfile.test.ts
> +    const buildLSP20TestContext = async (): Promise<LSP20TestContext> => {
@YamenMerhi an additional note.

It could be useful to put an optional param here, so that we can fund the UP on deployment directly (if any future LSP20 related tests imply value transfers).

Like this:

![image](https://user-images.githubusercontent.com/31145285/223577316-eb1fb01b-9dbe-42c3-8cef-dbacdc0a5b49.png)

I can see in the LSP20 test suite that so far, no tests involve value transfer.
We can add this either now, or in any future PR. :)

2023-03-07 23:36 UTC, CJ42 commented on tests/UniversalProfile.test.ts
> +            reverseVerificationContext.universalProfile as LSP0ERC725Account,
please put the additional type above in `LSP20TestContext` and not use `as`

2023-03-07 23:36 UTC, CJ42 commented on tests/UniversalProfile.test.ts
> +      const universalProfileInit = await new UniversalProfileInit__factory(
I think a small improvement could be for the describe block:

```js
describe("when using UniversalProfile contract with proxy", () => {
    // ...
}
```

to have an initial `before` hook that just deploy the base `UniversalProfileInit` contract, and inside each context building (for LSP14, LSP20, etc...), we can just deploy + attach the proxy.

This will avoid having to deploy the base contract on each context and could slightly improve the CI (since these contracts are big and have a lot of bytecode, I guess they can take a bit of time to deploy and the `await` can be a bit longer.

![Screenshot 2023-03-07 at 23 25 32](https://user-images.githubusercontent.com/31145285/223578865-1151c08c-fd39-4afe-a158-77752224f08f.png)

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +      describe("that implements verifyCallResult but return an expanded magic value", () => {
what is meant by "expanded magic value" here?

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +        before(async () => {
Could you add a space between the `before` and the variable declarations please :)

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +        it("should pass when calling LSP0 functions", async () => {
```suggestion
        it("should pass when calling `setData(bytes32,bytes)`", async () => {
```

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +        it("should revert when calling LSP0 functions", async () => {
```suggestion
        it("should revert when calling `setData(bytes32,bytes)`", async () => {
```

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +        it("should pass when calling LSP0 functions", async () => {
please be specific in the name of the test to explain which actual is being called directly on the LSP0 contract.

2023-03-07 23:36 UTC, CJ42 commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +        after("reverting to previous owner", async () => {
very nice tear down for the tests 👌

2023-03-10 11:50 UTC, CJ42 requested changes
The CI is not running here. We need to edit the CI to run:
- either when we merge for this branch in particular
- or if we merge to any branch

2023-03-14 09:45 UTC, YamenMerhi commented on tests/UniversalProfile.test.ts
> +    const buildLSP20TestContext = async (): Promise<LSP20TestContext> => {
We can include this change when it's needed, for now lets keep it simple 👍

2023-03-14 09:46 UTC, YamenMerhi commented on tests/LSP20ReverseVerification/LSP20ReverseVerification.behaviour.ts
> +      describe("that implements verifyCallResult but return an expanded magic value", () => {
The magic value padded with 0s

2023-03-14 09:52 UTC, YamenMerhi commented on tests/UniversalProfile.test.ts
> +      const universalProfileInit = await new UniversalProfileInit__factory(
Done

2023-03-14 10:00 UTC, YamenMerhi commented on contracts/LSP20ReverseVerification/LSP20ReverseVerification.sol
> +            bytes32 magicValue = abi.decode(returnedData, (bytes32));
Tested by me and @b00ste locally to avoid adding additional mock contracts, any bytes more than 32 will be discarded and pass.

2023-03-15 15:51 UTC, CJ42 commented on contracts/Mocks/LSP20Owners/FallbackReturnMagicValue.sol
> +        target = newTarget;
what is the reason here for setting the state variable in this mock contract to the `newTarget` param?

2023-03-15 15:51 UTC, CJ42 commented on contracts/Mocks/LSP20Owners/FallbackReturnMagicValue.sol
> +
remove blank line

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            bytes4(bytes.concat(bytes3(ILSP20CallVerification.lsp20VerifyCall.selector), hex"01"));
can we try to alias `ILSP20CallVerification` to `ILSP20` so that the prettier make it fit in one line?
Not a big deal otherwise

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +import "@erc725/smart-contracts/contracts/errors.sol";
good reorg 👌

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * MUST pass when called by the owner or by an address allowed by the owner as per
suggested change (TBD)

```suggestion
     * MUST pass when called by the owner or by an authorised address that pass the verification check performed by LSP20 - CallVerification specification
```

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>  {
Does the inheritance order have an impact?

Maybe we could put:
- the ERC interfaces first
- then the LSP interfaces in order by their number

It looks odd to me that IERC1271 is between LSP20 and LSP1

I would suggest this order:

```
abstract contract LSP0ERC725AccountCore is
    ERC725XCore,
    ERC725YCore,
    IERC1271,
    ILSP1UniversalReceiver
    LSP14Ownable2Step,
    LSP17Extendable,
    LSP20CallVerification,   
{
```

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>          if (msg.value != 0) emit ValueReceived(msg.sender, msg.value);
I would suggest that we move this event above the `_verifyCall` internal function call. 
It might be better to write first to the logs that some value was received, otherwise the order of events in User Interfaces will be weird.

For instance if it is a custom Key Manager (or other access control contract) that write to state first and then emit an event (for example let's call it `NewPermissionCheck`) before verifying the permission, the order will end up being:

- `NewPermissionCheck`
- `CallVerified`
- `ValueReceived`

The correct order IMO should be:

- `ValueReceived`
- `NewPermissionCheck`
- `CallVerified`

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>          if (msg.value != 0) emit ValueReceived(msg.sender, msg.value);
same comment as above

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        bool verifyAfter;
This is bugging me, the fact that this local variable is not initialized.

I am not sure how risky it is, but I belive it can cause some problems.

See this: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables

I would suggest to refactor to do it the other way around as suggest above for `execute(...)`

2023-03-15 15:51 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +
would be good to add a comment here to explain why we pass an empty `""`

2023-03-15 15:51 UTC, CJ42 commented on contracts/Mocks/LSP20Owners/FirstCallReturnMagicValue.sol
> +        revert();
please add a `@solhint-disable <reason>` comment here to silence the linter

2023-03-15 15:51 UTC, CJ42 commented on contracts/Mocks/LSP20Owners/ImplementingFallback.sol
> +    fallback() external {
please put `@solhint-disable <reason>` comment

2023-03-15 20:24 UTC, YamenMerhi commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +            return "";
To be done in a separate PR

2023-03-16 02:55 UTC, skimaharvey approved these changes
Looks great to me 🚀

2023-03-16 02:55 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>  {
Look better this way however the order of inheritance can affect the function overriding and state variable shadowing. We can try it out (may need to reorganise the constructor execution)

2023-03-16 02:55 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
>          if (msg.value != 0) emit ValueReceived(msg.sender, msg.value);
good point, emitting the `ValueReceived` event before other events can provide a more accurate chronological representation of the smart contract's internal operations

2023-03-16 02:55 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        if (verifyAfter) _verifyCallResult(_owner, "");
this all part around `owner()`/`owner`/`currentOwner` 😓 (not sure we can do anything better) 
I think `verifyAfter` could probably break the above assumption? 
```
        require(
            currentOwner == owner(),
            "LSP14: newOwner MUST accept ownership in a separate transaction"
        );
        ```
 May be we should move it down

2023-03-16 10:03 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        if (verifyAfter) _verifyCallResult(_owner, "");
We decided with @b00ste to replicate this check twice in case of call owner verification, one after the lsp1 notification, and one after the verifyCallResult call

2023-03-16 13:31 UTC, merged