fix: require `SUPER_TRANSFERVALUE` permission for deploying contracts with value
lukso-network/lsp-smart-contracts pull request #505
Opened 2023-03-15 20:23 UTC by YamenMerhi

## What does this PR introduce ?
- Require `SUPER_TRANSFERVALUE` permission for deploying contracts with value

2023-03-15 21:31 UTC, CJ42 requested changes
Added review comments

2023-03-15 21:31 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        if (isFundingContract) {
I think we can simplify here by keeping the extra conditional check that you deleted '&& !hasSuperTransferValue'.

And revert immediately with 'revert NotAuthorised(...)' inside the if block.

2023-03-15 21:31 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Utils.sol
> +        if (permission == _PERMISSION_SUPER_TRANSFERVALUE) return "SUPER_TRANSFERVALUE";
If we do the change I suggested above (keep the conditional check from before), we can remove this newly added line.

2023-03-15 21:31 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        if (isFundingContract) {
We could also revert with 'NotAuthorised(controller, "FUND ON DEPLOYMENT")' 

Or something like that to be specific and explicit.

2023-03-15 21:31 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
> -      );
We need to add at least one of the following test to ensure it works and deploy + fund the newly created contract when the caller has:
- DEPLOY + SUPER_TRANSFERVALUE --> deploy via CREATE
- DEPLOY + SUPER_TRANSFERVALUE --> deploy via CREATE2

Can you re-add the same tests from before where we were deploying + funding another UP (using a UP). These were good tests and a very creative use case imo 🙂💜

2023-03-16 08:31 UTC, YamenMerhi commented on tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
> -      );
These tests are already existing, added by you [here](https://github.com/lukso-network/lsp-smart-contracts/pull/505/files#diff-d4697674dc7cb0aaa901316c52580dee047e932aab70e5b515ebf6aa5b5f5ec2L551-L729)

2023-03-16 08:33 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        if (isFundingContract) {
I think it's good to revert with the permission needed,  "FUND ON DEPLOYMENT" doesn't point that you should have `SUPER_TRANSFERVALUE` not `TRANSFERVALUE`

2023-03-16 08:35 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        if (isFundingContract) {
I think it's simpler and cheaper to keep it the way it is, because its already pointing to what it does:
- If you are funding the contract ==> require Super_TransferValue permission.
Is the same
- If you are funding the contract ==> you don't have the Super_TransferValue permission revert with ..

2023-03-16 08:47 UTC, CJ42 approved these changes

2023-03-16 08:47 UTC, CJ42 commented on tests/LSP6KeyManager/tests/PermissionDeploy.test.ts
> -      );
all good, I had forgotten

2023-03-16 09:22 UTC, merged