refactor: rename GasLib to GasUtils and remove uncheckedIncrement from LSP2
lukso-network/lsp-smart-contracts pull request #539
Opened 2023-03-29 09:38 UTC by YamenMerhi

# What does this PR introduce?

## ♻️ Refactor

- rename GasLib to GasUtils
- remove uncheckedIncrement from LSP2

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [x] Ran `npm run linter`
- [x] Ran `npm run prettier`
- [x] Ran `npm run build`
- [x] Ran `npm run test`

2023-03-29 09:44 UTC, skimaharvey approved these changes

2023-03-30 07:26 UTC, b00ste approved these changes

2023-03-30 09:23 UTC, CJ42 requested changes

2023-03-30 09:23 UTC, CJ42 commented on contracts/Utils/GasUtils.sol
> +     * @dev Returns the unchecked incremented value of a given uint256
Let's not use the word "Return" in a `@dev` tag.
We need to explain what is happening under the hood and what is the behaviour. Not describe the code.

```suggestion
     * @dev Increment the `i` value by +1 without checking for arithmetic overflow. 
     if `i` is `max(uint256)`, this will not revert and wrap `i` to `0`.
```

2023-03-30 11:14 UTC, merged