refactor!: create a script for generating errors and events
lukso-network/lsp-smart-contracts pull request #542
Opened 2023-03-30 09:10 UTC by b00ste

# What does this PR introduce?

This PR automates the following things:
- Generating Error hash, and the description of the error from its natspec.
- Generating Event hash, and the description of the event from its natspec.

## ⚠️ BREAKING CHANGES

The type of the `Errors` and `Events` constants has changed.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [x] Ran `npm run linter`
- [x] Ran `npm run prettier`
- [x] Ran `npm run build`
- [x] Ran `npm run test`

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +const extractErrorsFromlist = (): [string[], string[]] => {
`extractErrorsFromList`

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +  var jsonErrors = JSON.stringify(generateErrors());
lets use `let` or `const`

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +  return (
I think template literals is nicer 
```
return `${text.substring(0, openParenthesesIndex + 1)}${parameters}${text.substring(closeParenthesesIndex)}`;
```

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +  if (closeParenthesesIndex == -1) return text;
`===` strict equality is better

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +// const used = process.memoryUsage().heapUsed / 1024 / 1024;
may be remove the comments?

2023-03-30 09:27 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +    for (let j = 0; j < fileContentByLines.length; j++) {
may be instead of using `i` and `j` for loop indices we could use `fileIdx` and `lineIdx`

2023-03-30 09:43 UTC, b00ste commented on scripts/errors_and_events/generate.ts
> +  return (
I think it overcomplicates it 😬

2023-03-30 09:55 UTC, skimaharvey commented on scripts/errors_and_events/generate.ts
> +  return (
yes it is fine this way

2023-03-30 09:55 UTC, skimaharvey approved these changes
Really nice add btw

2023-03-30 12:14 UTC, YamenMerhi approved these changes
Super! 

A few event signatures are removed from here, which are relevant for erc725.
They are present in the `constants.js` file in `@erc725/smart-contracts` package.

Should we keep also keep them generated here somehow ?

2023-04-01 23:14 UTC, richtera requested changes
The exec function also is not sync, so I had problems running this task locally.
I have a fix for this and I can put it on another branch, but I also have another PR that solves the devdocs/userdocs generation using a hardhat task.
It's possible to fix using ```js
import { exec } from "child_process";
import { artifacts } from "hardhat";
import path from "path";
const hre = require("hardhat");

const main = async () => {
  const contracts = hre.config.packager.contracts;

  await Promise.all(
    contracts.map(async (contract: string) => {
      const artifact = await artifacts.readArtifact(contract);

      const options = {
        env: {
          ...process.env,
          PATH: `${process.env.PATH}:${path.join(
            process.cwd(),
            "node_modules/.bin"
          )}`,
        },
      };
      // generate devdocs
      await new Promise<void>((resolve, reject) => {
        exec(
          `solc --devdoc --pretty-json \
@openzeppelin/="$(pwd)"/node_modules/@openzeppelin/ \
solidity-bytes-utils/="$(pwd)"/node_modules/solidity-bytes-utils/ \
@erc725="$(pwd)"/node_modules/@erc725/ \
        ${artifact.sourceName} -o devdocs/${contract}`,
          options,
          (error) => {
            if (error) {
              return reject(error);
            }
            return resolve();
          }
        );
      });

      // generate userdocs
      await new Promise<void>((resolve, reject) => {
        exec(
          `solc --userdoc --pretty-json \
@openzeppelin/="$(pwd)"/node_modules/@openzeppelin/ \
solidity-bytes-utils/="$(pwd)"/node_modules/solidity-bytes-utils/ \
@erc725="$(pwd)"/node_modules/@erc725/ \
${artifact.sourceName} -o userdocs/${contract}`,
          options,
          (error) => {
            if (error) {
              return reject(error);
            }
            return resolve();
          }
        );
      });
    })
  );
};

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

2023-04-01 23:20 UTC, richtera commented on scripts/ci/generate-docs.ts
> +        @openzeppelin/="$(pwd)"/node_modules/@openzeppelin/ \
I created #550 based on this to implement these patches. I created #549 to propose a different implementation which uses a hardhat task to generate the docs.

2023-04-02 00:42 UTC, CJ42 commented on scripts/ci/generate-docs.ts
> +        @openzeppelin/="$(pwd)"/node_modules/@openzeppelin/ \
@richtera it was intended to be used via the CI. So the solc compiler would be installed in a step before in the CI.

But in retrospec, I think this is not necessary to use the `solc` command line interface.

The Build infos from Hardhat contain all the necessary infos (including the Natspec comments). I can see that's what you tried to do in your PR.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/31145285/229324339-769f017d-64c0-4afe-bd56-3559c8e41b53.png">

I have also opened a draft PR to propose something similar 😄 

https://github.com/lukso-network/lsp-smart-contracts/pull/551/files#diff-2307051e3734c6c60989f18ba7020796d68188b8213e0ffcb6189f3a12ae182f

2023-04-03 09:10 UTC, b00ste commented on scripts/ci/generate-docs.ts
> +        ${artifact.sourceName} -o userdocs/${contract}`);
that folder is being deleted anyways after the JSONs are generated.

2023-04-11 08:09 UTC, closed without merging

2023-04-11 08:10 UTC, CJ42 commented
Closed in favour of #549