feat: Allow calling `ERC725X.execute(uint256[],address[],uint256[],bytes[])` through the LSP6
lukso-network/lsp-smart-contracts pull request #557
Opened 2023-04-03 16:17 UTC by b00ste

# What does this PR introduce?

This PR introduces the path `ERC725X.execute(uint256[],address[],uint256[],bytes[])` to LSP6KeyManager.

## 🚀 Feature

Previously calling `ERC725X.execute(uint256[],address[],uint256[],bytes[])` would revert with the custom error `InvalidERC725Function`. Now the call goes to the `target` contract. 

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [ ] Ran `npm run linter`
- [ ] Ran `npm run prettier`
- [x] Ran `npm run build`
- [ ] Ran `npm run test`

2023-04-04 13:35 UTC, b00ste commented
LSP6KeyManager deployment cost 3298129 => 3724578

2023-04-05 17:45 UTC, CJ42 requested changes
The reason there is a 400k gas difference is because there 5 or 6 x internal functions that are duplicated to use the "memory" keyword (as currently it is calldata).

We need to:
1) use "memory" for the internal functions instead of "calldata", (but keep "calldata" for the
function implementations of the public interface).

2) refactor the code to not have to pass "bytes" to the internal functions but instead the decoded parameters. We should not have to reconstruct a "singleExecute" payload. This is very inefficient especially in a loop.

To implement this batch feature, the current internal functions of the LSP6 Execute module (that are currently used to verify a single payload) need a bit of refactoring.

2023-04-05 17:45 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +    EXECUTE_SELECTOR
This can be removed once we have refactored to use the internal functions in a for loop

2023-04-06 19:27 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error ERC725XBatchExecuteArrayParamsLengthMissmatch();
Let's import and reuse the one from the @erc725 repo, like for the setData([],[]) path.
No point duplicating this definition, as there will be 2 x error selectors for exactly the same thing.

![image](https://user-images.githubusercontent.com/31145285/230471908-81161436-aece-4eeb-bc2b-e4d8d742b054.png)

2023-04-06 19:27 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        address callee,
I think "to" was a better name. callee makes sense but is a very specific Smart Contract technical term.
Only smart contract devs will understand this term.
Let's revert to the previous name.

2023-04-06 19:27 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            ) = abi.decode(payload[4:], (uint256[], address[], uint256[], bytes[]));
Hmmm this is more tricky that I thought and I did not see it coming.

Because now with this refactoring, we can see that we are not ensuring anymore that for every single payload in a batch ERC725X.execute([],[],[],[]), the offset of the fourth "data" parameter is always 0x...80.

![image](https://user-images.githubusercontent.com/31145285/230474658-ee63a4cd-c6b7-418d-a582-bf90f46d68fc.png)

We should ensure this is as well, not only for the single ERC725X.execute(uint256,address,ui t256,bytes).

Maybe we could try an other alternative approach.

_alternative 1:_ by looping through calldata slices.
The starting offset on every iterations could be easy to calculate. The ending offset could be a bit more harder but feasible.

_alternative 2:_

Or we could combine both: abi-decoding the four arrays but having a pre-check as well on the calldata at the start of each iterations.

2023-04-06 19:34 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            ) = abi.decode(payload[4:], (uint256[], address[], uint256[], bytes[]));
Actually maybe for bytes[] the offset check is not necessary.

But since there are 4 x arrays now (for each params list), there are probably more offsets to be checked for safety.

2023-04-06 20:54 UTC, CJ42 requested changes
This new feature needs more investigation and research. Blocking for now ❌🔎

2023-04-06 20:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +        bool isCallDataPresent = data.length > 0;
this read better this way 👌🏻

2023-04-06 20:54 UTC, CJ42 commented on contracts/Mocks/KeyManager/KeyManagerInternalsTester.sol
> +        (uint256 operationType, address callee, uint256 value, bytes memory data) = abi.decode(
⚠️❌ I am blocking this PR as this kind of diff should NEVER happen.

2023-04-06 20:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            (uint256 operationType, address callee, uint256 value, bytes memory data) = abi.decode(
since abi.decode reverts in Solidity 0.8.0, it would be good to add more unit tests for this internal function to be aware the different kind of behaviours and payloads that would make abi-decode revert or not.

We need to make more research and investigations as we always brought up with @skimaharvey and not go straight in with these code changes.

> we should also do the same for setData that also use abi.decode. Have more unit tests for the internal functions that verify setData payloads.

2023-04-21 05:20 UTC, CJ42 commented
For reference, on Ethereum, this increase in deployment cost would result in the following:

before: 3,298,128
after: 3,420,298

+ 122,170
 
x 50 (gas price) = 6,108,500 gwei = 0.0061085 ETH

1 ETH = 1,770 EUR
1 ETH = 1,940 USD

0.0061085 = 10.81 EUR
0.0061085 = 11.85 USD

2023-04-22 09:45 UTC, closed without merging

2023-04-22 09:45 UTC, CJ42 commented
Closing this PR as we need more investigations for potential bugs for this path + review the gas increase (both deployment + runtime)