fix: [TRST-M-5] `renounceOwnership()` bug
lukso-network/lsp-smart-contracts pull request #562
Opened 2023-04-14 10:01 UTC by b00ste

# What does this PR introduce?

This PR introduces a fix for a bug that occurs on new EVM blockchains, when someone intends to use LSP14.

## 🐛 Bug

In the current Implementation if the `block.number` is smaller than 400, then `renounceOwnership(..)` starts with the second step, bypassing the first step.

Fixes #???? 

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [ ] Ran `npm run linter`
- [ ] Ran `npm run prettier`
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-04-19 09:10 UTC, CJ42 requested changes

2023-04-19 09:10 UTC, CJ42 commented on tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
> +      // You would never be able to deploy a contract and initiate `renounceOwnership(..)`
Good test and comments. Just suggested some rewording


```suggestion
      // in a real blockchain environment, you would not likely be able to deploy a contract 
      // and initiate `renounceOwnership(..)` in the block 0
```

2023-04-19 09:10 UTC, CJ42 commented on tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
> +        2
Are we sure this state variable is at this storage slot?
Maybe we use this in the other tests, but this has changed since we have added more changes?

I would suggest to get the slot number where this state variable is defined programmatically, rather than a hardcoded literal.
By looking through the build-info of the contract.
There might be some content in the JSON file (either the AST, or something else) that contains the storage layout where we can grab this info.

This is required to ensure the correctness of the test.
I am happy to help and assist with this.

2023-04-19 09:10 UTC, CJ42 commented on tests/LSP14Ownable2Step/LSP14Ownable2Step.behaviour.ts
> +        ethers.BigNumber.from(_renounceOwnershipStartedAtAfter).toNumber()
Is the `toNumber()` needed? Does the test fail if you remove it?

I think chai with Hardhat handle comparisons between regular numbers and big numbers.

Try to remove it and see if the tests still pass:

```suggestion
        ethers.BigNumber.from(_renounceOwnershipStartedAtAfter)
```

2023-04-19 09:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +            RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY + RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD &&
Let's be VERY careful here!

Order of precedence of operators is very odd in Solidity.

https://docs.soliditylang.org/en/v0.8.19/types.html#order-of-precedence-of-operators

Let's put groups to compare in parentheses + define the a local variable.

> NB: `renounceOwnershipCanStartAt` could be better named maybe? 

```suggestion
            uint256 renounceOwnershipCanStartAt = RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY + RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD;
             bool isNewNetwork = (currentBlock <
            renounceOwnershipCanStartAt) && (_renounceOwnershipStartedAt == 0)
```

2023-04-19 09:10 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +            RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY + RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD &&
I am also not sure about this fix.
@YamenMerhi @skimaharvey we can look at this later

2023-04-22 05:26 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +            RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY + RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD &&
I really don't get it at all. Why overcomplicating with this complex local variable when the recommendation is very straight forward?

![image](https://user-images.githubusercontent.com/31145285/233764409-bf25b9c3-af01-40cf-964c-f7d07e5027db.jpeg)

2023-05-03 09:24 UTC, CJ42 approved these changes

2023-05-03 11:55 UTC, YamenMerhi approved these changes

2023-05-03 13:40 UTC, merged