refactor: [TRST-M-7] Incorrect permission check due to confusion between empty call and the zero selector
lukso-network/lsp-smart-contracts pull request #577
Opened 2023-04-28 09:13 UTC by b00ste

# What does this PR introduce?

## 🐛 Bug

Add an `isEmptyCall` parameter to `_extractExecuteParameters(..)` and retrieve it in `_extractCallType(..)`. If it is not true,
_ALLOWEDCALLS_WRITE should be turned on even for selector 0x00000000.

Fixes #???? 

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [ ] Ran `npm run linter` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-05-02 07:54 UTC, CJ42 requested changes
we might need an extra test to check the fix work. Don't know which one tho

2023-05-02 07:54 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
> +            requiredCallTypes = _ALLOWEDCALLS_WRITE;
we should probably rename these `constant` to:

- `_ALLOWEDCALLS_WRITE ` --> `_ALLOWEDCALLS_CALL`
- `_ALLOWEDCALLS_READ` --> `_ALLOWEDCALLS_STATICCALL`
- `_ALLOWEDCALLS_EXECUTE` --> `_ALLOWEDCALLS_DELEGATECALL`
- `_ALLOWEDCALLS_VALUE` --> `_ALLOWEDCALLS_TRANSFERVALUE`

2023-05-02 08:06 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6Modules/LSP6ExecuteModule.sol
>              : bytes4(0);
Yeah, that's for  getting the function selector, if you look a bit down we return `isEmptyCall = executeCalldata.length == 164`

2023-05-03 13:41 UTC, CJ42 approved these changes

2023-05-04 07:54 UTC, YamenMerhi commented on contracts/Mocks/FallbackExtensions/GraffitiEventExtension.sol
> +    fallback(bytes calldata data) external payable returns (bytes memory) {
Can you resolve solhint warnings

2023-05-04 07:55 UTC, YamenMerhi approved these changes

2023-05-04 08:08 UTC, b00ste commented on contracts/Mocks/FallbackExtensions/GraffitiEventExtension.sol
> +    fallback(bytes calldata data) external payable returns (bytes memory) {
done

2023-05-04 09:26 UTC, merged