feat: Add validity timestamps for Relay Calls
lukso-network/lsp-smart-contracts pull request #581
Opened 2023-05-03 10:33 UTC by b00ste

# What does this PR introduce?

## 🚀 Feature

Add validity timestamps, start/end for each Relay Call, verify if it's valid and add to the signature.

Fixes #???? 

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote Documentation
- [ ] Ran `npm run linter` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-05-04 14:17 UTC, CJ42 commented on contracts/LSP6KeyManager/ILSP6KeyManager.sol
> +     * @param validityTimestamps two timestamps combined, first timestamp limits from when the payload can be executed and the second timestamp delimits the end of the validity of the payload
```suggestion
     * @param validityTimestamps two `uint128` timestamps concatenated, the first timestamp determines from when the payload can be executed, the second timestamp delimits the end of the validity of the payload
```

2023-05-04 14:17 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> + * @dev reverts when relay call end timestamp is smaller than the current timestamp
Suggesting alternative description for the Natspec

```suggestion
 * @dev reverts when the period to execute the relay call has expired
```

2023-05-04 14:17 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        uint128 startTimestamp = uint128(validityTimestamps >> 128);
very nice, clean and readable 👌 ❤️

2023-05-04 14:17 UTC, CJ42 commented on tests/utils/helpers.ts
> +  startingTimestamp?: number,
Not sure I understand.
Is this intended to be using:
- for 1st parameter: either `timeBefore` or `startingTimestamp`?
- for 2nd parameter: either `timeAfter` or `endingTimeStamp`?

2023-05-04 14:17 UTC, CJ42 commented on tests/utils/helpers.ts
> +  if (time.seconds) totalTime += time.seconds * 60;
there must be an easy way in JS to do that with `Date` object.

2023-05-04 14:21 UTC, b00ste commented on tests/utils/helpers.ts
> +  startingTimestamp?: number,
Either first 2 params or the last 2 params. First 2 generate timestamp from now with the wanted modifications and the last 2 params are for custom timestamps just converted to hex, glued and returned

2023-05-04 14:21 UTC, b00ste commented on tests/utils/helpers.ts
> +  if (time.seconds) totalTime += time.seconds * 60;
will check that

2023-05-04 15:02 UTC, b00ste commented on tests/utils/helpers.ts
> +  if (time.seconds) totalTime += time.seconds * 60;
The way it is seems to be the easiest way, lmk if you find something else.

2023-05-08 08:35 UTC, YamenMerhi commented on contracts/LSP6KeyManager/ILSP6KeyManager.sol
> +     * @param validityTimestamps two `uint128` timestamps concatenated, the first timestamp determines from when the payload can be executed, the second timestamp delimits the end of the validity of
Maybe we can mention in the @dev tag about the null (meaning no timestamp)

2023-05-08 09:30 UTC, CJ42 requested changes

2023-05-08 09:30 UTC, CJ42 commented on tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
> +          describe("start timestamp < now > end timestamp", () => {
needing extra blank line before the `describe` block.

2023-05-08 09:30 UTC, CJ42 commented on tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
> +          describe("start timestamp = now > end timestamp", () => {
can we write the test with plain English sentences please?
It' hard to review and understand the context as we need to decipher the math symbols with the `=` and `<`

2023-05-08 09:30 UTC, CJ42 commented on tests/LSP6KeyManager/Relay/ExecuteRelayCall.test.ts
> +              await time.setNextBlockTimestamp(now);
nice! 🚀

2023-05-08 10:56 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error RelayCallNotValidYet();
```suggestion
error RelayCallBeforeStartTime();
```

2023-05-08 10:56 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            if (startTimestamp > block.timestamp) {
```suggestion
            if (block.timestamp < startTimestamp) {
```

2023-05-08 10:56 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +            if (endTimestamp < block.timestamp) {
```suggestion
            if (block.timestamp > endTimestamp) {
```

2023-05-08 11:36 UTC, CJ42 approved these changes

2023-05-08 11:37 UTC, merged