docs: update LSP14 Natspec
lukso-network/lsp-smart-contracts pull request #629
Opened 2023-07-17 08:27 UTC by b00ste

# What does this PR introduce?

## 📄 Documentation

This PR updates the Natspec of the LSP14 contracts.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-10 11:39 UTC, Hugoo approved these changes
Looking good!

2023-08-10 11:39 UTC, Hugoo commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Emitted when starting the {renounceOwnership(..)} 2-step process.
2-step or 2-steps ?

2023-08-10 11:39 UTC, Hugoo commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> -     * @custom:info If no ownership transfer is in progress, the pendingOwner will be `address(0)`.
Not true anymore?

2023-08-10 11:39 UTC, Hugoo commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> -     * @custom:danger Leaves the contract without an owner. Once ownership of the contract has been renounced, any functions that are restricted to be called by the owner will be permanently inaccess
I think this is nice information - why do you want to remove it?

2023-08-10 11:39 UTC, Hugoo commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +     * @custom:danger Leaves the contract without an owner. Once ownership of the contract has been renounced, any functions that are restricted to be called by the owner will be permanently inaccess
Ah ok I see you moved it here

2023-08-10 11:39 UTC, Hugoo commented on docs/contracts/LSP14Ownable2Step/LSP14Ownable2Step.md
> +<br/>
Is this needed? The br

2023-08-11 06:36 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Emitted when starting the {transferOwnership(..)} 2-step process.
```suggestion
     * @dev Emitted when {transferOwnership} was called for the first time, and the first step of transferring ownership completed successfully and set the {pendingOwner}.
```

2023-08-11 06:36 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @notice Ownership transfer initiated. From: `previousOwner`. To: `newOwner`.
```suggestion
     * @notice The transfer of ownership of the contract was initiated. Pending new owner set to: `newOwner`.
```

2023-08-11 06:36 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Emitted when starting the {renounceOwnership(..)} 2-step process.
I would go with the name of the standard so singular

2023-08-11 06:56 UTC, CJ42 requested changes
Added review comments

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @notice Ownership renouncement complete.
Suggested changes:

```suggestion
     * @notice Successfully renounced ownership of the contract. This contract is now owned by anyone, it's owner is `address(0)`.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * function {owner()} external view returns (address);
We should remove the `()` for any references between `{}`

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> -     * @custom:info If no ownership transfer is in progress, the pendingOwner will be `address(0)`.
This was moved below
<img width="934" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/4876b5d4-d362-410a-90eb-3a962e9257a8">

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> -     * @custom:requirements
Ok we put in the implementation to display the callouts. Marking this as resolved

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @dev Transfer ownership of the contract from the current {owner()} to the {pendingOwner()}.
Same here could you please remove the `()`

```suggestion
     * @dev Transfer ownership of the contract from the current {owner} to the {pendingOwner}.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * 2. The second is used as a confirmation and will leave the contract without an owner.
```suggestion
     * 2. The second call is used as a confirmation and will leave the contract without an owner.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * @notice `msg.sender` is renouncing ownership of contract: `address(this)`.
Nice `@notice` tag! 👌 

```suggestion
     * @notice `msg.sender` is renouncing ownership of contract `address(this)`.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Errors.sol
> + * @dev Reverts when trying to renounce ownership before the initial confirmation delay
Small detail but let's try to not forget the final period, so that it shows as full sentences in the docs :)

```suggestion
 * @dev Reverts when trying to renounce ownership before the initial confirmation delay.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Errors.sol
> + * @param renounceOwnershipStart The start of the period when you one can confirm the renouncement of ownership.
Let's be specific here and mention timestamp / or block number (whatever is used)

```suggestion
 * @param renounceOwnershipStart The timestamp when one can confirm the renouncement of ownership.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Errors.sol
> + * @param renounceOwnershipEnd The end of the period when you one can confirm the renouncement of ownership.
Same here

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Errors.sol
> + * @notice Cannot transfer ownerhsip to yourself.
Typo + let's be explicit here.

```suggestion
 * @notice Cannot transfer ownership to the address of the contract itself.
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> + * @dev This contract is a modified version of the [`OwnableUnset.sol`] implementation, where transferring and renouncing ownership works as a 2-step process. This can be used as a confirmation mecha
Let's put examples of "mistakes"

```suggestion
 * @dev This contract is a modified version of the [`OwnableUnset.sol`] implementation, where transferring and renouncing ownership works as a 2-step process. This can be used as a confirmation mechanism to prevent potential mistakes when transferring ownership of the contract, where the control of the contract could be lost forever (_e.g: providing the wrong address as a parameter to the function, transferring ownership to an EOA for which the user lost its private key, etc..._)
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +     * @custom:requirements `newOwner` cannot accept ownership of the contract in the same transaction.
Let's add an extra explicit example here.

```suggestion
     * @custom:requirements `newOwner` cannot accept ownership of the contract in the same transaction (For instance, via a callback from its {universalReceiver} function).
```

2023-08-11 06:56 UTC, CJ42 commented on contracts/LSP14Ownable2Step/LSP14Ownable2Step.sol
> +     * @custom:danger Leaves the contract without an owner. Once ownership of the contract has been renounced, any functions that are restricted to be called by the owner will be permanently inaccess
Is it not singular here?

```suggestion
     * @custom:danger Leaves the contract without an owner. Once ownership of the contract has been renounced, any function that are restricted to be called by the owner only will be permanently inaccessible, making these functions not callable anymore and unusable.
```

2023-08-11 08:46 UTC, b00ste commented on contracts/LSP14Ownable2Step/ILSP14Ownable2Step.sol
> +     * function {owner()} external view returns (address);
why? I think having `()` makes it clear that it is not a state variable but a callable function

2023-08-11 13:03 UTC, CJ42 approved these changes

2023-08-11 13:04 UTC, merged