chore: update `hardhat-dodoc` & dodoc config & dodoc template
lukso-network/lsp-smart-contracts pull request #630
Opened 2023-07-17 08:29 UTC by b00ste

# What does this PR introduce?

## ♻️ Refactor

This PR updates the following things:
- `hardhat-dodoc` to v0.3.8.
- dodoc config with new helper function & `include`.
- dodoc template with specs link at the top.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-07-23 03:23 UTC, CJ42 requested changes
We need to change how the links are generated in the helper functions, as right now, this will generate broken links for ERC725 and functions from IZ contracts like ERC165, ERC1271, ...

2023-07-23 03:23 UTC, CJ42 commented on dodoc/template.sqrl
> +<!-- This file is auto-generated. Do not edit! -->
This comment is misleading for the reader new to the repo.
This file is not directly autogenerated by running a command.
It is used to autogenerate Markdown docs.

The "do not edit" implies that we cannot touch this file too, but we will if the generated docs contain errors, or we want to improve them.

Please change to:

```suggestion
<!-- SquirellyJS template file used to generate developer docs in Markdown by parsing the Natspec comments of Solidity contracts (".sol") -->
```

2023-07-23 03:23 UTC, CJ42 commented on dodoc/template.sqrl
> +<!-- Check `@lukso-network/lsp-smart-contracts/CONTRIBUTING.md#solidity-code-comments` for more information. -->
We can also add a comment to point to the docs/ folder to see the output of the auto generated docs

2023-07-23 03:23 UTC, CJ42 commented on dodoc/template.sqrl
> +:::info Soldity implementation
Typo here:

```suggestion
:::info Solidity implementation
```

2023-07-23 03:23 UTC, CJ42 commented on dodoc/config.ts
> +  return `${linkBase}lsp-smart-contracts/blob/develop/${contractPath}`;
This will not work and generate broken 404 links in the docs for:
- the ERC725 contracts
- the functions from inherited ERC contracts, like 1271, 165, OZ, etc...

We need to think properly of a better way to handle these cases.

2023-07-23 03:25 UTC, CJ42 commented
@b00ste we can also remove the docs/ folder from the .gitignore in this PR, without pushing any new autogenerated docs.

Let's do that at the end once we have addressed all the issues.

2023-07-23 08:55 UTC, b00ste commented on dodoc/template.sqrl
> +<!-- This file is auto-generated. Do not edit! -->
The comment is for the final `.md` file, not for the template.

2023-07-23 08:55 UTC, b00ste commented on dodoc/template.sqrl
> +<!-- Check `@lukso-network/lsp-smart-contracts/CONTRIBUTING.md#solidity-code-comments` for more information. -->
Same as above

2023-07-23 08:57 UTC, b00ste commented on dodoc/config.ts
> +  return `${linkBase}lsp-smart-contracts/blob/develop/${contractPath}`;
True, the only think I see we can do is add manually links for external contracts

2023-08-08 14:21 UTC, CJ42 approved these changes

2023-08-08 14:49 UTC, CJ42 approved these changes

2023-08-09 07:13 UTC, merged