docs: update LSP0 Natspec
lukso-network/lsp-smart-contracts pull request #631
Opened 2023-07-17 08:31 UTC by b00ste

# What does this PR introduce?

## 📄 Documentation

This PR updates the Natspec of the LSP0 contracts.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-15 16:56 UTC, CJ42 requested changes
Added first round of review.

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725Account.sol
> + * - Detecting supported standards using [ERC-165]
I suggest it is not needed to repeat this in the standard and proxy version of the contract. Just having this described in the `Core` is fine.

You can specify in the `@title` for these that it is the standard or proxy or abstract proxy version.

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
> +     * @return results An array of abi-encoded returned data by the executed functions.
```suggestion
     * @return results An array of abi-encode data returned by the functions executed.
```

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
> +     * @notice `value` tokens received from `sender`.
```suggestion
     * @notice `value` native tokens received from `sender`.
```

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
> +     * @param sender The address of the sender.
```suggestion
     * @param sender The address that sent some native tokens to this contract.
```

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725Account.sol
> +     * @notice Deploying an LSP0ERC725Account with owner set to: `initialOwner`
```suggestion
     * @notice Deploying a LSP0ERC725Account contract with owner set to address `initialOwner`
```

2023-08-15 16:56 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725Account.sol
> +     * - {OwnershipTransferred} event when `initialOwner` is set.
```suggestion
     * - {OwnershipTransferred} event when `initialOwner` is set as the contract {owner}.
```

2023-08-15 16:56 UTC, CJ42 commented on docs/contracts/ERC725/ERC725.md
Nice 👌

2023-08-21 14:53 UTC, CJ42 requested changes
Added some requested changes.

Also suggesting to re-use the `@notice` tags from ERC725 when possible, and make sure they are there :)

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/ILSP0ERC725Account.sol
> +     * @dev Allows a caller to batch different function calls in one call. Perform a `delegatecall` on self, to call different functions with preserving the context.
Missing `@notice` tag

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> + * - Storing data in a generic way using [ERC-725Y]
```suggestion
 * - A generic data key-value store using [ERC-725Y]
```

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> + * - Secure ownership management using [LSP-14-Ownable2Step]
```suggestion
 * - Safer ownership management through 2-steps transfer using [LSP-14-Ownable2Step]
```

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> + * - Verifying calls on the owner to allow unified and standard interaction with the account using [LSP-20-CallVerification]
```suggestion
 * - Verifying calls on the owner to make it easier to interact with the account directly using [LSP-20-CallVerification]
```

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @notice Achieves the goal of [LSP-17-ContractExtension] standard by extending the contract to handle calls of functions that do not exist natively, forwarding the function call to the extensio
This is not a `@notice` tag to display to the user. Suggesting to refactor and put the `@notice` tag in the interface if possible.

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @custom:info It's not possible to send value along the functions call due to the use of `delegatecall`.
Nice use of callouts 👌

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * - The length of the parameters provided must be equal.
Nice, let's keep these in this repo and not in ERC725 (So ERC725 does not have any `@custom` tag and is not tied to our docs.

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @notice Achieves the goal of [LSP-1-UniversalReceiver] by allowing the account to be notified about incoming/outgoing transactions and enabling reactions to these actions.
Suggest to review this `@notice` tag too.

2023-08-21 14:53 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @notice Achieves the goal of [ERC-165] to detect supported interfaces and [LSP-17-ContractExtension] by
Same here.

2023-08-22 12:46 UTC, YamenMerhi approved these changes

2023-08-22 13:03 UTC, CJ42 approved these changes

2023-08-22 13:03 UTC, merged