refactor: improve LSP23 readability
lukso-network/lsp-smart-contracts pull request #650
Opened 2023-08-02 14:44 UTC by b00ste

# What does this PR introduce?

## ♻️ Refactor

This PR applies the following changes:
- Split the main contract in:
    1. main contract
    2. interface 
    3. errors file
- Split `deployContracts(...)` in another 2 internal functions for better readability and separation of concern.
- Split the `DeployedContracts(...)` & `DeployedERC1167Proxies(...)` event in 5 events:
    1. `DeployedContract(...)`
    2. `DeployedOwnerContract(...)`
    3. `DeployedERC1167Proxie(...)`
    4. `DeployedOwnerERC1167Proxie(...)`
    5. `PostDeployment(...)`
  This allows for an easier use of events, eg. `DeployedContract` is used when the initial contract was successfully deployed but also before the owner contract was deployed. 
  The execution timeline is correct. Also allows for easier to read events, instead of a single event with 4 simple parameters and 2 structs, into events containing 1 simple param, 1 struct and the last event containing 2 simple params.
- Move the `salt` parameter into the `ControlledContract` struct because it is only used when deploying the initial contract. Makes it cluttered having it as a separate parameter.
- Move Natspec to the interface and inheriting it in the main contract.

With all these changes the tests were running good, no issues.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-02 15:25 UTC, skimaharvey commented
Thanks for the PR 🚀 
- ✅  splitted contracts is better
- ✅  2 internal functions witht the `deployContracts` function makes sense
- 🚫 would not split the event into different events it would be more difficult to retrieve them. The end goal is to make it easy to retrieve all infos at once
- ✔️ thats a good point, we use to have two different salts but its true than now salt is used only in the `OwnerControlledContract` so it may make sense to add it to the struct directly. Need to check with the rest of team

2023-08-03 09:17 UTC, skimaharvey commented on tests/testBug.test.ts
> +import { ethers } from 'hardhat';
Do we need this file on this PR?

2023-08-03 09:21 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
>      function _deployAndInitializeOwnerControlledProxy(
should rename to `_deployAndInitializeOwnerControlledContractProxy` out of consistency

2023-08-03 09:31 UTC, CJ42 reviewed
Added first round of review

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
> +     * @param salt A value used to ensure uniqueness of the created proxies.
```suggestion
     * @param salt A unique value used to ensure each created proxies are unique.
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/LSP23Errors.sol
> + *
Missing Natspec description here for `@dev` and `@param`

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/LSP23Errors.sol
> + * @dev reverts when the `msg.value` sent is not equal to the sum of value used for the deployment of the contract and its owner contract.
```suggestion
 * @dev Reverts when the `msg.value` sent is not equal to the sum of value used for the deployment of the contract and its owner contract.
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +    /*
```suggestion
    /**
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +    /*
```suggestion
    /**
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        emit DeployedERC1167Proxie(
Since the param of this event do not depend on the `success` and `returnedData`, we could emit it before the external to avoid out of order events in the logs.

I suggest move this emit statement before the external call.

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        if (ownerContractDeploymentInit.addControlledContractAddress) {
Suggest refactoring as follow for readability:

```solidity
bool shouldAppendControlledContractAddress = 
        
/**
 * if addControlledContractAddress is true, the controlled contract address + extraInitialisationBytes 
 * will be appended to the initializationCalldata 
 */
if (ownerContractDeploymentInit.addControlledContractAddress) {
   // ...
} else {
    // ...
}
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        if (ownerContractDeploymentInit.addControlledContractAddress) {
Suggesting the following refactoring:

```solidity
bytes memory ownerInitializationBytes = ownerContractDeploymentInit.initializationCalldata;
        
/* if addControlledContractAddress is true */
if (ownerContractDeploymentInit.addControlledContractAddress) {
    /* append the controlled contract address + extraInitialisationBytes to the initializationCalldata */
    ownerInitializationBytes = abi.encodePacked(
        ownerInitializationBytes,
        abi.encode(controlledContractAddress),
        ownerContractDeploymentInit.extraInitializationParams
    );
 }
```

2023-08-03 09:31 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        emit DeployedOwnerERC1167Proxie(
Same suggest to emit this event as well before the external call.

This was spotted by Slither

<img width="1582" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/9af5f2b2-6d44-4494-b74f-037305521184">

2023-08-03 09:34 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
> +        bytes creationBytecode /* the bytecode of the owner contract with the constructor params before the controlled contract address param */;
nice

2023-08-03 09:38 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
> +        uint256 value;
not sure. fine with me @b00ste @YamenMerhi

2023-08-03 09:40 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
> +     * @param salt A value used to ensure uniqueness of the created proxies.
probably should mention something related to the address

2023-08-03 09:40 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        if (ownerContractDeploymentInit.addControlledContractAddress) {
yes looks good

2023-08-03 09:40 UTC, b00ste commented on tests/testBug.test.ts
> +import { ethers } from 'hardhat';
nope, sorry

2023-08-03 09:42 UTC, skimaharvey commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        emit DeployedOwnerERC1167Proxie(
I honestly think we should revert to single event for now

2023-08-03 09:42 UTC, skimaharvey requested changes
Would revert to single event for now

2023-08-03 09:45 UTC, b00ste commented on contracts/LSP23MultiChainDeployment/IOwnerControlledContractDeployer.sol
> +        uint256 value;
good suggestion

2023-08-03 09:46 UTC, b00ste commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        if (ownerContractDeploymentInit.addControlledContractAddress) {
nice

2023-08-03 13:22 UTC, skimaharvey approved these changes
Looks great! Thanks

2023-08-03 14:53 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/LSP23Errors.sol
> + *
Nice! Marking this as resolved

2023-08-03 14:53 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        /*  here owner refers as the future owner of the controlled contract at the end of the transaction */
```suggestion
        /* here owner refers to the future owner of the controlled contract at the end of the transaction */
```

2023-08-03 14:53 UTC, CJ42 commented on contracts/LSP23MultiChainDeployment/OwnerControlledContractDeployer.sol
> +        /* if addControlledContractAddress is true, the controlled contract address + extraConstructorParams will be appended to the constructor params */
Suggesting to break this comment across multiple lines, as it is too long and too hard to read

2023-08-04 09:51 UTC, CJ42 approved these changes

2023-08-04 09:52 UTC, merged