refactor: save used relay call signature
lukso-network/lsp-smart-contracts pull request #670
Opened 2023-08-09 09:40 UTC by b00ste

# What does this PR introduce?

## ♻️ Refactor

After investigating the way signatures are stored in [`Safe.sol`](https://github.com/safe-global/safe-contracts/blob/d2dfe316ff24162159ee48b05dd6827cf95f06db/contracts/Safe.sol#L67-L68), it turns out that they have a [`signMessage(...)`](https://github.com/safe-global/safe-contracts/blob/d2dfe316ff24162159ee48b05dd6827cf95f06db/contracts/libraries/SignMessageLib.sol#L22) function which marks a signature as approved signature. That further is checked in [`isValidSignature(...)`](https://github.com/safe-global/safe-contracts/blob/d2dfe316ff24162159ee48b05dd6827cf95f06db/contracts/handler/CompatibilityFallbackHandler.sol#L34) which requires that a signature to be approved.

With this said, they don't quite have the same purpose as in our case. We need to store signatures in order to not allow double use while they store signatures that are approved. In our case we cannot use [`signMessage(...)`](https://github.com/safe-global/safe-contracts/blob/d2dfe316ff24162159ee48b05dd6827cf95f06db/contracts/libraries/SignMessageLib.sol#L22) as it will block gases execution and will require for someone to have gas in order to approve a signature. We need an approach that does not break the ux behind relay calls.

I took the liberty to implement it in the following way:
- Before executing a relay call, we check that the signature is marked as unused (0) in the `signedMessages` mapping.
- After executing a relay call successfully we mark the signature as used (1) in the `signedMessages` mapping.

That would 100% not allow any signature to be used twice.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-09 09:40 UTC, Hugoo commented
Task linked: [DEV-7688 Add signed messages inside the mapping. (after use)](https://app.clickup.com/t/2645698/DEV-7688)

2023-08-09 10:31 UTC, skimaharvey commented on tests/Reentrancy/LSP6/LSP6Reentrancy.test.ts
> +            .to.be.revertedWithCustomError(context.keyManager, 'CannotUseSignatureTwice')
probably should rename line 140?

2023-08-09 10:31 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(signature)] == 1) {
why use one over bool? is it really a gas optimisation?
Also:
- probably could store the `keccak256(signature)` into a stack variable as we do it again below
- initially i thought we were going to store the hash of the `keccak256(encodedMessage)` but I guess signature makes sense as well

2023-08-09 10:40 UTC, YamenMerhi commented
Few things I had in mind:
- Need to decide what is best for the visibility of the mapping (should it be public or internal)
- Why not store the signature itself instead of a hash, lowering the possibilities of a hash collision.

2023-08-09 11:05 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(signature)] == 1) {
I took the safe implementation, my guess would be that it is indeed cheaper. 
For the first point, yes but is we do as Yamen suggested then it makes no sense to store the signature plain bytes to the stack.
For the second point, to me it makes more sense to check the signature as the signature is the thing that you don't want to re-play.

Wdyt @skimaharvey @CJ42? Should we keep the current mapping? Or change it to one from the below examples?
- `mapping (bytes32 => bool) signedMessages;`
- `mapping (bytes => uint256) signedMessages;`
- `mapping (bytes => bool) signedMessages;`

2023-08-09 11:31 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(signature)] == 1) {
would not store `bytes` but `bytes32` . I think first one is good `mapping (bytes32 => bool) signedMessages;`

2023-08-09 12:40 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(signature)] == 1) {
imo lets investigate signature malleability more before merging this PR https://github.com/kadenzipfel/smart-contract-vulnerabilities/blob/master/vulnerabilities/signature-malleability.md

2023-08-09 12:40 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(signature)] == 1) {
thats why we should may be actually store the hash of the `encodedMessage` message so we cant find the equivalent

2023-08-10 08:16 UTC, skimaharvey approved these changes

2023-08-10 08:16 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(encodedMessage)] == 1) {
so you dont think its worth it saving the hashing in a stack variable?

2023-08-10 08:16 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(encodedMessage)] == 1) {
also not sure about using 1 vs bool

2023-08-10 08:17 UTC, skimaharvey commented
LGTM.
- Just not sure we should not save the hash the `econdedMessage` in a stack variable. 
- Using bool instead of `1`

2023-08-10 16:36 UTC, CJ42 requested changes

2023-08-10 16:36 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(encodedMessage)] == 1) {
Depending if we implement this or not, I recommended we cache the keccak256 hash in a local variable, instead of re-hashing again further down below.

Hashing is costly in gas, the more bytes there are to hash

2023-08-11 09:13 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        if (signedMessages[keccak256(encodedMessage)] == 1) {
it is, just got out of my mind

2023-08-15 17:15 UTC, CJ42 commented
@b00ste @skimaharvey 

I suggest we put this PR as draft.
Also could you check how much gas difference there is for the deployment cost by comparing the gas benchmark of the Github actions?

(Looks like the gas diff for Foundry does not show this)

2023-08-21 17:16 UTC, closed without merging