refactor: return when URD has no permission for UP
lukso-network/lsp-smart-contracts pull request #672
Opened 2023-08-10 13:01 UTC by b00ste

# What does this PR introduce?

## ♻️ Refactor

Allow the UP URD to return when it cannot update the `dataKeys`.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-10 13:01 UTC, Hugoo commented
Task linked: [DEV-7686 [C4#95] Potential Reversion in Transfer due to LSP1 Interface Support Check](https://app.clickup.com/t/2645698/DEV-7686)

2023-08-10 13:20 UTC, skimaharvey commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +            (, bytes memory returnedData) = msg.sender.call(
すべてのケースで `returnedData` を返すことに意味があるのだろうか？

2023-08-10 17:26 UTC, CJ42 requested changes
This PR is not ready. There is more to do than that at the LSP1 level to change the behaviour suggested by the PR title.

Let's discuss first.

Also, this is a breaking change. We should make the PR as "refactor!" and mention it in the description.

2023-08-10 17:26 UTC, CJ42 commented on tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
> +    describe('when receiving LSP9', () => {
```suggestion
    describe('when becoming the owner of LSP9 Vaults', () => {
```

2023-08-10 17:28 UTC, CJ42 commented
@b00ste Also please add the C4 issue number in the PR title so that we can keep track of it

2023-08-15 08:46 UTC, CJ42 reviewed
Added review comments

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            bytes32[] memory keys,
```suggestion
            bytes32[] memory lsp10DataKeys,
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            bytes[] memory values,
```suggestion
            bytes[] memory lsp10DataValues,
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            bytes memory errorMsg
```suggestion
            bytes memory errorMessage
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            bytes32[] memory keys,
Same comment as above

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            return (keys, values, "LSP10: Vault index superior to uint128");
Maybe we can specify which data key the error is related to?

```suggestion
            return (keys, values, "LSP10: `LSP10Vault[index]` index superior to uint128");
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +            return (keys, values, "LSP10: Out of bounds");
same here:

```suggestion
            return (keys, values, "LSP10: `LSP10Vaults[]` Array Out of bounds");
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +        if (notifier == tx.origin)
Suggest adding curly brackets for consistency:

```suggestion
        if (notifier == tx.origin) {
            // ...
        }
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ) internal virtual returns (bytes memory errorMsg) {
```suggestion
    ) internal virtual returns (bytes memory errorMessage) {
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +             */
Suggesting single line comment here:

```
// `generateReceivedAssetKeys(...)` returns empty arrays when encountering errors
```

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +             */
Actually this could be put at the top as a  Natspec comment above the function using the `@custom:warning` tag

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +             */
Same this can be put as a `@custom:warning` comment

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateVault/LSP1UniversalReceiverDelegateVault.sol
> +    ) public payable virtual returns (bytes memory errorMsg) {
I would suggest to rename this argument to just `returnedMessage`, as it can be misleading.

If the function goes successfully, there is no error message but just an empty `""`. 

This should also be documented in the `@return` tag as well for the contract docs.

2023-08-15 08:46 UTC, CJ42 commented on contracts/LSP5ReceivedAssets/LSP5Utils.sol
Same comments from LSP10 apply here

2023-08-15 12:40 UTC, CJ42 approved these changes

2023-08-15 17:13 UTC, CJ42 commented
> @b00ste Also please add the C4 issue number in the PR title so that we can keep track of it

@b00ste please 🙏  :)

2023-08-15 19:23 UTC, CJ42 requested changes
@b00ste @YamenMerhi @skimaharvey 

Ok I decided to not approve this PR for the following reasons:
- we cannot update a Utility library that is intended to be used by anyone to make our implementation code work (this is the equivalent to ask to update the code of web3.js / ethers.js to make the code of your app work).
- this is increasing the runtime cost by 2k + for simple token / NFT transfers. This is too much for just such a simple change of behaviour.
- we need to have an idea of the change in the deployment cost as well for the LSP1Delegate. Just to be aware at least, this is not the most important, as LSP1 Delegate is only deployed once for everyone.

2023-08-15 20:48 UTC, skimaharvey commented
> @b00ste @YamenMerhi @skimaharvey
> 
> Ok I decided to not approve this PR for the following reasons:
> 
> * we cannot update a Utility library that is intended to be used by anyone to make our implementation code work (this is the equivalent to ask to update the code of web3.js / ethers.js to make the code of your app work).
> * this is increasing the runtime cost by 2k + for simple token / NFT transfers. This is too much for just such a simple change of behaviour.
> * we need to have an idea of the change in the deployment cost as well for the LSP1Delegate. Just to be aware at least, this is not the most important, as LSP1 Delegate is only deployed once for everyone.

Agreed lets think it more through and see if we dont have other solution that do not impact the library

2023-08-18 14:51 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +     * @return returnedMessage The result of the reaction for `typeId`.
return param name can be removed here I guess?

2023-08-23 08:42 UTC, CJ42 reviewed
added review comments

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        IERC725Y ERC725YContract = IERC725Y(receiver);
There is something returned by solhint here

<img width="672" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/68b87444-f6fd-48cd-a84e-9ecd5ed1e565">

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +     * @custom:warning Returns empty arrays when encountering errors. Otherwise the arrays must have 3 data keys and 3 data values.
```suggestion
     * @custom:warning This function returns empty arrays when encountering errors. Otherwise the arrays will contain 3 data keys and 3 data values.
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +     * @return lsp10DataKeys An array Data Keys used to update the [LSP-10-ReceivedAssets] data.
```suggestion
     * @return lsp10DataKeys An array of data keys used to update the [LSP-10-ReceivedAssets] data.
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +     * @return lsp10DataValues An array Data Values used to update the [LSP-10-ReceivedAssets] data.
```suggestion
     * @return lsp10DataValues An array of data values used to update the [LSP-10-ReceivedAssets] data.
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        /// --- Array ---
```suggestion
        /// --- `LSP10Vaults[]` Array ---
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        if (currentArrayLengthBytes.length == 0) {
Maybe we can we group these two `if` statements together?

```solidity
if (
    // invalid `currentArrayLengthBytes`
    currentArrayLengthBytes.length == 0 ||
    // overflow
    uint128(bytes16(currentArrayLengthBytes)) == type(uint128).max
) {
    return (lsp10DataKeys, lsp10DataValues);
}
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        /// --- Mapping ---
```suggestion
        /// --- `LSP10VaultsMap:<vault-address>` Mapping ---
```

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        IERC725Y ERC725YContract = IERC725Y(sender);
Same here:

<img width="682" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/ae98d94e-cb91-4d98-b3e1-49900004f093">

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +     * @return lsp10DataKeys An array Data Keys used to update the [LSP-10-ReceivedAssets] data.
same comment as above for here

2023-08-23 08:42 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        if (currentArrayLengthBytes.length == 0) {
Or instead you can keep two separate `if` checks but do the same way as you did in `LSP5Utils`

<img width="820" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/078dbe0c-b75b-4f75-a94c-746873ac27a4">

2023-08-23 08:48 UTC, CJ42 commented on contracts/LSP10ReceivedVaults/LSP10Utils.sol
> +        bytes20 vaultAddress
suggest keeping this parameter as an address and casting below.
So that the parameter name fits with better with the type

2023-08-23 11:06 UTC, skimaharvey approved these changes
Very nice. Except the few comments brought by @CJ42 & @YamenMerhi LGTM

2023-08-23 16:53 UTC, merged