refactor: rename to LSP23LinkedContractsFactory
lukso-network/lsp-smart-contracts pull request #675
Opened 2023-08-12 07:05 UTC by skimaharvey

# What does this PR introduce? 

Rename `LinkedContractsFactory` to `LSP23LinkedContractsFactory`

2023-08-12 08:11 UTC, b00ste approved these changes

2023-08-12 13:23 UTC, CJ42 requested changes
Please do not forget to also change the name in `hardhat.config.ts`. Otherwise the JSON artifacts will not be present in the npm package!

https://github.com/lukso-network/lsp-smart-contracts/blob/614cec6c07cdef74b493f2d04a61374acacd1e8d/hardhat.config.ts#L153

2023-08-12 13:23 UTC, CJ42 commented on tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
> +      // await LSP23LinkedContractsFactory.deployContracts(
is this intended to be commented?

2023-08-13 10:19 UTC, skimaharvey commented on tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
> +      // await LSP23LinkedContractsFactory.deployContracts(
Yes I can remove it but basically it is not working when deploying two contracts at once. I am guessing it is something wrong with hardhat node. 
the `callstatic` does work though

2023-08-13 10:19 UTC, skimaharvey commented on tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
> +      // await LSP23LinkedContractsFactory.deployContracts(
wanted to leave the comment to show that I tried. Also if you guys can try on your end that would be awesome ;)

2023-08-14 07:57 UTC, YamenMerhi approved these changes
Need to change also in `hardhat.config.ts`

2023-08-14 10:03 UTC, CJ42 commented on tests/LSP23LinkedContractsDeployment/LSP23LinkedContractsDeployment.test.ts
> +      // await LSP23LinkedContractsFactory.deployContracts(
resolved in last commit ✅

2023-08-14 10:03 UTC, CJ42 approved these changes

2023-08-15 09:11 UTC, CJ42 approved these changes

2023-08-15 09:11 UTC, merged