refactor: add input validations when setting data in `LSP6SetDataModule`
lukso-network/lsp-smart-contracts pull request #679
Opened 2023-08-14 16:45 UTC by b00ste

# What does this PR introduce?

### PR Checklist

## ♻️ Refactor

Add input validations for the data values of specific data keys.

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-08-14 16:45 UTC, Hugoo commented
Task linked: [DEV-7685 [C4#115] Missing input validations](https://app.clickup.com/t/2645698/DEV-7685)

2023-08-15 14:42 UTC, CJ42 requested changes

2023-08-15 14:42 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> + * @param dataKey The data key that requires a specific length for the `dataValue`.
Suggested changes:

```suggestion
 * @param dataKey The data key associated with the invalid `dataValue` that was set.
```

2023-08-15 14:42 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> + * @param dataValue The data value that must have a specific length.
```suggestion
 * @param dataValue The data value that has an invalid length.
```

2023-08-15 14:42 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Errors.sol
> + * @param zeroValueRequiredLength The `dataValue` length required for any normal value set under the `dataKey`.
I am not sure I understand this parameter name. What does the `zeroValue` mean in the parameter name?

2023-08-15 14:42 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +                // validate Data Value length
```suggestion
                // validate the number of bytes in `dataValue`
```

2023-08-15 14:42 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +                    0,
I think we can get rid of this parameter.
And just replace the second one by the `invalidLength` of the `byte memory dataValue`

2023-08-15 14:42 UTC, CJ42 commented on docs/contracts/LSP6KeyManager/LSP6KeyManager.md
Nice! 🙏

2023-08-15 14:42 UTC, CJ42 commented on tests/LSP20CallVerification/LSP6/Admin/PermissionChangeAddExtensions.test.ts
> +              ethers.utils.hexZeroPad(ethers.utils.hexlify(8), 16),
Nice catch! 🙏

2023-08-15 17:12 UTC, CJ42 requested changes
Let's please review the newly added errors. This is adding 66k gas on deployment. It's way too much for just one check and two new custom errors.

Let's see if we can reduce this gas by some small refactoring or re-using the other errors 🙏

2023-08-15 21:09 UTC, b00ste commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +                    0,
Wdym?

2023-08-22 18:21 UTC, YamenMerhi reviewed
Was it discussed to have it strictly the length or the minimum length?

2023-08-22 18:21 UTC, YamenMerhi commented on contracts/LSP6KeyManager/LSP6Errors.sol
> +error InvalidDataValuesForDataKeys(bytes dataValue);
Maybe add the data key as parameter to know that the dataValue is invalid for what data key

2023-08-22 18:51 UTC, CJ42 commented
> Was it discussed to have it strictly the length or the minimum length?

Good point. I remember @frozeman  saying it should be at least the minimum length. Any extra byte we ignore it.

2023-08-22 20:07 UTC, skimaharvey approved these changes
LGTM

2023-08-22 20:08 UTC, skimaharvey commented
> > Was it discussed to have it strictly the length or the minimum length?
> 
> Good point. I remember @frozeman saying it should be at least the minimum length. Any extra byte we ignore it.
I believe for most strictly makes more sense as we are casting after but could be wrong

2023-08-23 08:21 UTC, CJ42 reviewed
Added some final suggestions for the Natspec

2023-08-23 08:21 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +                // validate the number of bytes in `dataValue`
```suggestion
                // CHECK that `dataValue` contains at least 32 bytes, which is the required length for a permission BitArray
```

2023-08-23 08:21 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +            // validate the number of bytes in `dataValue`
```suggestion
            // CHECK that `dataValue` contains at least 20 bytes, which corresponds to an address for a LSP1 Delegate contract
```

2023-08-23 08:21 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +            // validate the number of bytes in `dataValue`
```suggestion
            // CHECK that `dataValue` contains at least 20 bytes, which corresponds to an address for a LSP17 Extension
```

2023-08-23 08:21 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +            if (inputDataValue.length != 16 && inputDataValue.length != 0) {
For this I would keep exactly like this, to be exactly 16 bytes long or 0 bytes, as this is how we check it also in LSP5Utils.

https://github.com/lukso-network/lsp-smart-contracts/blob/083d9970065b747ce0e1bfb5f4d98a3a86a164f4/contracts/LSP5ReceivedAssets/LSP5Utils.sol#L80-L87

2023-08-23 08:21 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
> +            // validate the number of bytes in `dataValue`
```suggestion
            // CHECK that `dataValue` is exactly 16 bytes long or `0x` (= not set), as the array length of `AddressPermissions[]` MUST be a `uint128` value.
```

2023-08-23 12:15 UTC, CJ42 approved these changes

2023-08-23 14:24 UTC, merged