Dev 7694
lukso-network/lsp-smart-contracts pull request #681
Opened 2023-08-15 11:31 UTC by skimaharvey

# What does this PR introduce? 

- make LSP7 variables internals 
- make LSP8 variables internal 
- modify approval logic to be compliant with erc721 
- add test

2023-08-15 11:31 UTC, Hugoo commented
Task linked: [DEV-7694 (C4 #118) - LSP8CompatibleERC721's approve() deviates from ERC-721 specification](https://app.clickup.com/t/2645698/DEV-7694)

2023-08-15 14:45 UTC, CJ42 requested changes
@skimaharvey Since we changed the visibility to `internal` for the state variables, let's refactor the internal `_transfer` function at the same time in the LSP8 Compatible ERC721

https://github.com/lukso-network/lsp-smart-contracts/blob/f0372f88942040caae91fd63d8b239402de1a072/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol#L245C14-L257

2023-08-16 08:27 UTC, b00ste approved these changes

2023-08-22 08:37 UTC, CJ42 commented
> @skimaharvey Since we changed the visibility to `internal` for the state variables, let's refactor the internal `_transfer` function at the same time in the LSP8 Compatible ERC721
> 
> https://github.com/lukso-network/lsp-smart-contracts/blob/f0372f88942040caae91fd63d8b239402de1a072/contracts/LSP8IdentifiableDigitalAsset/extensions/LSP8CompatibleERC721.sol#L245C14-L257

Let's do this in an other PR.

2023-08-22 08:37 UTC, CJ42 approved these changes

2023-08-23 10:03 UTC, merged