feat: Non transferable token extensions
lukso-network/lsp-smart-contracts pull request #692
Opened 2023-08-30 10:06 UTC by samuel-videau

# What does this PR introduce?

## 🚀 Feature
This PR introduce an extension to make tokens (LSP7 or LSP8) non-transferable.

In these extensions, the _transfer functions are overriten to revert if called. 
A flag (as a ERC725Y key) is added, in order to let application/smart contracts know if they are dealing with a non-transferable token. This flag can't be edited after contract deployment or initialization.

Thoughts: 
- 2 keys were added for the flags (LSP7NonTransferable & LSP8NonTransferable), though it might be interesting having a common "LSPNonTransferable" key that would be shared by any token standard that want to implement a non-transferable logic.
- Should we also override functions like `authorizeOperator` ?

### PR Checklist

- [x] Wrote Tests
- [x] Wrote & Generated Documentation (readme/natspec/dodoc)
- [x] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [x] Ran `npm run format` (prettier)
- [x] Ran `npm run build`
- [x] Ran `npm run test`

2023-09-11 11:01 UTC, CJ42 requested changes

2023-09-11 11:01 UTC, CJ42 commented on contracts/LSP7DigitalAsset/extensions/LSP7NonTransferable.sol
> +     * @param isNonDivisible_ Specify if the LSP7 token is a fungible or non-fungible token
This is not correct. If this parameter is `true`, the token is still a fungible token.

```suggestion
     * @param isNonDivisible_ Specify if the tokens from this contract can be divided in smaller units or not.
```

2023-09-11 11:01 UTC, CJ42 commented on contracts/LSP7DigitalAsset/extensions/LSP7NonTransferable.sol
> +     * @notice This function override _transfer function to make it non-transferable
```suggestion
     * @notice This function override the internal `_transfer` function to make it non-transferable
```

2023-09-11 11:01 UTC, CJ42 commented on contracts/LSP7DigitalAsset/extensions/LSP7NonTransferableInitAbstract.sol
> +     * @param isNonDivisible_ Specify if the LSP7 token is a fungible or non-fungible token
same as in the other file.

2023-09-12 03:45 UTC, samuel-videau commented on constants.ts
> +    LSP7NonTransferable: '0xb48a0085fb2c841c614d8c650033c5b790f407c071b9176ca4f2003db3613a1f',
Issue created: https://github.com/lukso-network/LIPs/issues/231

2024-07-26 12:48 UTC, CJ42 commented
Closing this PR as similar to #804 and #805

We need more inputs and clarify more the roadmap on the Token extension for tokens and NFTs. PR could be re-opened tho in the future if we consider this is relevant.

Also this feature might not require a token extension, as it can be easily done by overriding the internal `_transfer` function.

2024-07-26 12:48 UTC, closed without merging