chore: [C4] Add first batch of QA fixes
lukso-network/lsp-smart-contracts pull request #693
Opened 2023-08-30 10:07 UTC by YamenMerhi

# What does this PR introduce?

Add some of the QA fixes 

### PR Checklist

- [x] Wrote Tests
- [x] Wrote & Generated Documentation (readme/natspec/dodoc)
- [x] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [x] Ran `npm run format` (prettier)
- [x] Ran `npm run build`
- [x] Ran `npm run test`

2023-09-11 11:09 UTC, CJ42 requested changes

2023-09-11 11:09 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +        address accountOwner = owner();
nice 👌  variable shadowing here?

2023-09-11 11:09 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        bool isSetData = bytes4(data) == IERC725Y.setData.selector ||
great 👌

2023-09-11 11:09 UTC, CJ42 commented on tests/UniversalProfile.behaviour.ts
> +    it('should fail when setting empty data keys', async () => {
```suggestion
    it('should fail when passing empty arrays of data keys / values', async () => {
```

2023-09-11 11:09 UTC, CJ42 commented on contracts/LSP20CallVerification/LSP20CallVerification.sol
> +        return bytes1(magicValue[3]) == 0x01;
Type casting not needed here. Index access on `bytesN` returns a `bytes1` already.

```suggestion
        return magicValue[3] == 0x01;
```

2023-09-26 09:23 UTC, YamenMerhi commented on contracts/LSP20CallVerification/LSP20CallVerification.sol
> +        return bytes1(magicValue[3]) == 0x01;
Being done in another PR

2023-09-26 10:07 UTC, b00ste approved these changes

2023-09-27 07:13 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @custom:danger Leaves the contract without an owner. Once ownership of the contract has been renounced, any functions that are restricted to be called by the owner or an address allowed by the
LSP9 have no LSP20 so this does not apply

2023-09-27 09:24 UTC, CJ42 reviewed
added some small review comments

2023-09-27 10:02 UTC, CJ42 approved these changes

2023-09-27 10:12 UTC, merged