chore: [C4] Add first batch of Gas optimization
lukso-network/lsp-smart-contracts pull request #695
Opened 2023-08-31 17:14 UTC by YamenMerhi

# What does this PR introduce?

- Add first batch of Gas optimization

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-09-11 11:13 UTC, CJ42 approved these changes

2023-09-11 11:13 UTC, CJ42 commented on contracts/LSP25ExecuteRelayCall/LSP25MultiChannelNonce.sol
> -        uint256 nonceInChannel = _nonceStore[from][channelId];
Hmm this seems a bit less readable to me. But not a big deal otherwise, I am happy with the changes.

What do you think @skimaharvey @b00ste @YamenMerhi ?

2023-09-11 11:13 UTC, CJ42 commented on contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
> +            _operatorAuthorizedAmount[from][operator] =
nice so this removes a `SLOAD` basically? 👌

2023-09-11 11:29 UTC, skimaharvey commented on contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
> +        _tokenOwnerBalances[from] = balance - amount;
im wondering if it is not dangerous particularly with reentrancies with the `_beforeTokenTransfer` hooks. Possibly `balance` will not be the same

2023-09-11 11:31 UTC, skimaharvey commented on contracts/LSP7DigitalAsset/LSP7DigitalAssetCore.sol
> +        _tokenOwnerBalances[from] = balance - amount;
in our case `_beforeTokenTransfer` does not do anything but possibly in some implementation it will. We could then face some issues where the value of `balance` has changed. 
I think we should discard this change

2023-09-26 09:27 UTC, b00ste approved these changes

2023-09-26 16:36 UTC, CJ42 requested changes

2023-09-26 16:36 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        address target_ = _target;
Not a big fan of using postfix underscore (except `constructor` arguments). Would suggest a different variable name in camelCase to maintain Solidity style guide

```suggestion
        address targetContract = _target;
```

2023-09-26 16:36 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +                isSetData || (reentrancyStatus == _ENTERED)
I think because of the order of precedence of operators, `isSetData` should always be checked first.

See from the Solidity docs. But good idea to surround it in parentheses in case 👌 

![image](https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/7948e122-cbac-4f66-b334-5479ba757413)

![image](https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/238ff1f2-403b-4635-85f3-b4f17f8b1eee)

2023-09-26 16:36 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        address target_ = _target;
same comment as above

2023-09-26 16:36 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> +        address target_,
same comment as above. It feels inconsistent to have one parameter name that is prepended with a `_`. Suggest renaming to this to make it more explicit with the word _"Contract"_, as we are running a payload in a targeted smart contract

```suggestion
        address targetContract,
```

2023-09-26 16:36 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/LSP8IdentifiableDigitalAssetCore.sol
> +        return (caller == tokenOwnerOf(tokenId) ||
We will need to increase the line width for Solidity files. This is hard to read (@skimaharvey )

2023-09-27 07:36 UTC, CJ42 approved these changes

2023-09-27 07:36 UTC, CJ42 commented
Amazing! 🚀

2023-09-27 07:36 UTC, merged