chore: minify artifacts
lukso-network/lsp-smart-contracts pull request #707
Opened 2023-09-07 09:14 UTC by b00ste

# What does this PR introduce?

## 🤖 CI

Minify artifacts before publishing to `npm`.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-09-07 09:14 UTC, Hugoo commented
Task linked: [DEV-5006 [Investigation] Minifying JSON artifacts.](https://app.clickup.com/t/2645698/DEV-5006)

2023-09-11 11:24 UTC, CJ42 requested changes
Could you do the same steps as the `publish-npm-artifact.yml` and then do `npm pack` to compare the difference in size before and after minifying.

2023-09-11 14:09 UTC, CJ42 approved these changes

2023-09-13 09:07 UTC, b00ste commented
PR would make `JSON` files unreadable.

2023-09-13 09:07 UTC, closed without merging