docs: add LSP17 Natspec about `msg.value` not forwarded to extension
lukso-network/lsp-smart-contracts pull request #721
Opened 2023-09-15 14:41 UTC by CJ42

# What does this PR introduce?

## 📄 Documentation

Add note in Natspec comment above `_fallbackLSP17Extendable` function about the fact that this function does not forward the `msg.value` to the extension contract + add basic code snippet to show how this can be done.

2023-09-19 13:57 UTC, YamenMerhi requested changes

2023-09-19 13:57 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Reverts if there is no extension for the function being called.
This is deleted, can we get it back ?
```
being called, except for the bytes4(0) function selector, which passes even if there is no extension for it.
```

2023-09-19 13:57 UTC, YamenMerhi commented on contracts/LSP9Vault/LSP9VaultCore.sol
> +     * Reverts if there is no extension for the function being called.
This is deleted, can we get it back ?
```
being called, except for the bytes4(0) function selector, which passes even if there is no extension for it.
```

2023-09-19 14:18 UTC, skimaharvey approved these changes
LGTM

2023-09-21 10:22 UTC, YamenMerhi approved these changes

2023-09-21 10:23 UTC, merged