feat: allow sending value when using `setData(..)` through the LSP6
lukso-network/lsp-smart-contracts pull request #725
Opened 2023-09-20 12:59 UTC by b00ste

# What does this PR introduce?

## 🚀 Feature

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-09-22 16:47 UTC, CJ42 approved these changes

2023-09-22 16:47 UTC, CJ42 commented on contracts/LSP20CallVerification/LSP20CallVerification.sol
> +        return magicValue[3] == 0x01;
Nice 👌

2023-09-22 16:47 UTC, CJ42 commented on tests/LSP6KeyManager/Interactions/BatchExecute.test.ts
> +          const totalMsgValue = ethers.utils.parseEther('4');
Could be done with `.reduce` like it is done below.

```js
const totalMsgValue = msgValues.reduce((accumulator, currentValue) =>
            accumulator.add(currentValue),
          );
```

2023-09-27 11:28 UTC, CJ42 requested changes
If we allow to send native tokens while setting data, we need now to add the permission check of `TRANSFERVALUE` while setting data + tests for it.

I suggest we park this PR on the side and put it as draft for now until we have discussed and agreed on the decision with @frozeman

2023-09-27 11:28 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> -        uint256 msgValue,
We need to keep this parameter, as we also need to check for permissions.

2023-09-27 11:28 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> -            if (msgValue != 0) revert CannotSendValueToSetData();
Since we are removing the custom error, we need to check for permission `TRANSFERVALUE` in addition to check for the permission `SETDATA` below via `_verifyCanSetData(...)`.

2023-10-01 08:18 UTC, skimaharvey commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> -            if (msgValue != 0) revert CannotSendValueToSetData();
why? It is just founding the account when setting data? not transfering?

2023-10-10 09:26 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6KeyManagerCore.sol
> -            if (msgValue != 0) revert CannotSendValueToSetData();
Yes indeed. Got it wrong

2023-10-10 09:31 UTC, skimaharvey approved these changes
LGTM

2023-10-10 09:33 UTC, YamenMerhi approved these changes

2023-10-10 10:04 UTC, merged