feat!: Add `renounceOwnership()` path through the LSP6
lukso-network/lsp-smart-contracts pull request #728
Opened 2023-09-25 13:00 UTC by b00ste

# What does this PR introduce?

## 🚀 Feature

Add new path for `CHANGEOWNER` permission, the `renounceOwnership()` path.

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-09-26 17:11 UTC, CJ42 requested changes

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP20CallVerification/LSP6/Admin/PermissionChangeOwner.test.ts
> +      await context.universalProfile.connect(context.owner).renounceOwnership();
Let's add some extra checks:
- event `RenounceOwnershipStarted` has been emitted
- `_pendingOwner` has been deleted if it was set before.

![image](https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/8cf30d74-eb3c-4c12-aaf7-b168de725eb9)

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP6KeyManager/Admin/PermissionChangeOwner.test.ts
> +        await newKeyManager.connect(context.owner).execute(payload);
Suggest adding the same tests mentioned above for LSP20 test suite

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP6KeyManager/Admin/PermissionChangeOwner.test.ts
> +        await setupKeyManager(context, [], []);
Maybe it would be cleaner to put this in a `beforeEach` hook at the top? Under the first `describe` block?

![image](https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/fa45f8de-32c0-47ea-93be-8e3e840a89e7)

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP6KeyManager/Admin/PermissionChangeOwner.test.ts
> +        expect(await context.universalProfile.owner()).to.equal(ethers.constants.AddressZero);
Suggest testing the events and storage is cleared as mentioned in LSP20 test suite too.

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP6KeyManager/LSP6ControlledToken.test.ts
> +    before("previous token contract's ownership was renounced, build new context", async () => {
Nice setup description 👌

2023-09-26 17:11 UTC, CJ42 commented on tests/LSP6KeyManager/LSP6ControlledToken.test.ts
> +    it("`mint(..)` -> should revert with 'InvalidERC725Function' error.", async () => {
I am not understanding this change. Why it is a new revert message now?

2023-09-27 07:38 UTC, skimaharvey approved these changes
Except the comments brought out by @CJ42 it looks good to me

2023-09-27 08:36 UTC, b00ste commented on tests/LSP6KeyManager/LSP6ControlledToken.test.ts
> +    it("`mint(..)` -> should revert with 'InvalidERC725Function' error.", async () => {
it is not a new revert message, the test is the same, the test description was wrong.

2023-09-27 08:46 UTC, b00ste commented on tests/LSP6KeyManager/Admin/PermissionChangeOwner.test.ts
> +        await setupKeyManager(context, [], []);
We could, but that would mean building the context twice instead of a single time, which means tests would take a bit more time

2023-09-28 08:08 UTC, CJ42 approved these changes

2023-09-28 08:09 UTC, merged