refactor!: Add UniversalReceiverDelegate Interface and functions
lukso-network/lsp-smart-contracts pull request #741
Opened 2023-10-10 10:25 UTC by YamenMerhi

# What does this PR introduce?

## ⚠️ BREAKING CHANGES
## ♻️ Refactor

-  Add UniversalReceiverDelegate Interface and functions

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-10-11 15:24 UTC, CJ42 requested changes
Let's make sure the `universalReceiverDelegate` functions (in both the contracts/ and the Mock contracts) that inherit the ILSP1Delegate interface have the `override` keyword, so that they can be compiled with old solc versions and so that the CI passes once it is merged ✅

2023-10-11 15:24 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +    ILSP1UniversalReceiverDelegate
Maybe we can alias if it shortens the line length and improve readability?

```suggestion
    ILSP1UniversalReceiverDelegate as ILSP1Delegate
```

2023-10-11 15:24 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +                    universalReceiverDelegate
Would that make it more readable and shorter?

```solidity
resultDefaultDelegate = ILSP1Delegate(lsp1Delegate).universalReceiverDelegate(
    msg.sender,
    msg.value,
    typeId,
    receivedData
);
```

2023-10-11 15:24 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ) public virtual returns (bytes memory) {
Do we want to keep this function not payable? Would there be a use case to make it payable?

2023-10-11 15:24 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ILSP1UniversalReceiverDelegate
interface should go before `ERC165` in the inheritance. From most base (left) to most derived (right)

2023-10-11 15:24 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ) public virtual returns (bytes memory) {
It is also missing the `override` keyword, so that it can compile with `solc < 0.8.8`

2023-10-11 15:24 UTC, CJ42 commented on contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateDataUpdater.sol
>  contract UniversalReceiverDelegateDataUpdater is ERC165Storage {
We could add the `ILSP1Delegate` in the inheritance here, even if it is a Mock contract.

2023-10-11 15:24 UTC, CJ42 commented on contracts/Mocks/UniversalReceivers/UniversalReceiverDelegateGasConsumer.sol
> +    ) public virtual returns (bytes memory) {
same comment about old solc compiler version (otherwise CI will fail once it is merge into `develop`).

2023-10-11 15:24 UTC, CJ42 commented on tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
> -  describe('edge cases', () => {
We could keep this test to ensure that we cannot send value to the `universalReceiverDelegate` function maybe?

2023-10-11 15:24 UTC, CJ42 commented on scripts/interfaceIds.ts
>        // adjust the source path for LSP20 and LSP17 contracts
```suggestion
      // adjust the source path for LSP1Delegate, LSP20 and LSP17 contracts
```

2023-10-11 17:37 UTC, YamenMerhi commented on tests/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP.behaviour.ts
> -  describe('edge cases', () => {
you don't have the option to send value when the function is not payable

2023-10-12 18:10 UTC, YamenMerhi commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ILSP1UniversalReceiverDelegate
@CJ42 I think most base is `ERC165` and most derived is `ILSP1`

2023-10-12 18:10 UTC, YamenMerhi commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ) public virtual returns (bytes memory) {
I don't think it should be payable

2023-10-12 20:19 UTC, CJ42 approved these changes

2023-10-13 09:31 UTC, CJ42 commented on contracts/LSP1UniversalReceiver/LSP1UniversalReceiverDelegateUP/LSP1UniversalReceiverDelegateUP.sol
> +    ILSP1UniversalReceiverDelegate
We can leave it like that for now until we add tests to check the inheritance graph + linearization.

2023-10-13 10:55 UTC, b00ste approved these changes

2023-10-13 10:56 UTC, skimaharvey approved these changes

2023-10-13 11:36 UTC, merged