Lsp20/accept ownership
lukso-network/lsp-smart-contracts pull request #747
Opened 2023-10-12 13:52 UTC by skimaharvey

# What does this PR introduce

- [x] Add lsp20 to `acceptOwnership`

2023-10-13 12:18 UTC, CJ42 requested changes
Added review comments

2023-10-13 12:18 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +                _verifyCallResult(pendingOwnerAddress, "");
We need to move this line after the LSP1 external calls to notify previous owner and new owner.

2023-10-13 12:18 UTC, CJ42 commented on tests/LSP20CallVerification/LSP20WithLSP14.behaviour.ts
> +    describe('when caller is not the pending owner but pending owner is a key manager', () => {
We should move these tests in this file, since they are directly related to LSP6.

<img width="346" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/e0ac0899-40d9-4ed5-9f88-4a6f2c1f4dde">

Tests in this file are not.

2023-10-13 12:18 UTC, CJ42 commented on tests/LSP20CallVerification/LSP20WithLSP14.behaviour.ts
> -      ).to.be.revertedWith('LSP14: caller is not the pendingOwner');
Let's refactor to a custom error. Easy optimisation here. 

```solidity
error CallerNotPendingOwner()
```

2023-10-13 12:18 UTC, CJ42 commented on tests/foundry/LSP14Ownable2Step/TwoStepRenounceOwnership.sol
> +        vm.expectRevert();
Can't you test the custom error here in Foundry?

2023-10-13 12:22 UTC, skimaharvey commented on tests/LSP20CallVerification/LSP20WithLSP14.behaviour.ts
> +    describe('when caller is not the pending owner but pending owner is a key manager', () => {
I dont think so I am calling acceptOwnership directly on the UP

2023-10-13 12:22 UTC, skimaharvey commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +                _verifyCallResult(pendingOwnerAddress, "");
good point. will update

2023-10-13 13:46 UTC, CJ42 commented on tests/LSP20CallVerification/LSP20WithLSP14.behaviour.ts
> +    describe('when caller is not the pending owner but pending owner is a key manager', () => {
Sorry I meant the LSP6 folder inside LSP20 😅 

<img width="313" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/e6950e00-7c58-431e-828b-830b739dcd86">

2023-10-16 09:24 UTC, skimaharvey commented on tests/LSP20CallVerification/LSP20WithLSP14.behaviour.ts
> +    describe('when caller is not the pending owner but pending owner is a key manager', () => {
imo it should stay there as `acceptOwnership` is an lsp14 function

2023-10-16 10:17 UTC, b00ste approved these changes

2023-10-17 08:32 UTC, CJ42 approved these changes

2023-10-17 09:33 UTC, merged