fix: allow setting 21 bytes under LSP17Extension data key in LSP6KeyManager
lukso-network/lsp-smart-contracts pull request #777
Opened 2023-10-31 14:59 UTC by YamenMerhi

# What does this PR introduce?
## 🐛 Bug

- allow setting 21 bytes under LSP17Extension data key in LSP6KeyManager

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-10-31 15:05 UTC, CJ42 approved these changes
Should we test it with the other restricted controllers as well?

2023-11-01 13:30 UTC, CJ42 commented on contracts/LSP6KeyManager/LSP6Modules/LSP6SetDataModule.sol
>              // CHECK that `dataValue` contains exactly 20 bytes, which corresponds to an address for a LSP17 Extension
```suggestion
            // CHECK that `dataValue` contains exactly 20 or 21 bytes (if setting to forward value), which corresponds to an address for a LSP17 Extension
```

2023-11-02 09:44 UTC, skimaharvey approved these changes

2023-11-02 13:15 UTC, b00ste approved these changes

2023-11-02 14:04 UTC, CJ42 requested changes
We cannot write tests like that.
We need to check that validation happen also depending on the controller permission.

For instance, that regardless if controller has `ADDEXTENSION`, or `CHANGEEXTENSION`, or both, the error of invalid value being set occur.

2023-11-02 14:04 UTC, CJ42 commented on tests/LSP6KeyManager/Admin/PermissionChangeAddExtensions.test.ts
> +    describe('when setting random bytes under the LSP17Extension data key ', () => {
These tests are a copy paste of LSP20.
We are not in a LSP20 context here, we are calling via LSP6.

2023-11-02 14:50 UTC, CJ42 approved these changes

2023-11-02 15:16 UTC, merged