docs: Improve natspec for LSP0
lukso-network/lsp-smart-contracts pull request #794
Opened 2023-11-06 17:54 UTC by YamenMerhi

# What does this PR introduce?

## 📄 Documentation

docs: Improve natspec for LSP0

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-11-06 18:35 UTC, CJ42 requested changes

2023-11-06 18:35 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @custom:hint If you would like to forward the `msg.value` to the extension contract, you should store an additiona `0x01` byte after the address of the extension under the corresponding LSP17
```suggestion
     * @custom:hint If you would like to forward the `msg.value` to the extension contract, you should store an additional `0x01` byte after the address of the extension under the corresponding LSP17 data key.
```

2023-11-06 18:35 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @custom:events {UniversalReceiver} event when receiving native tokens.
Why is there this Natspec tag and comment block? It is already present below

<img width="546" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/616abf83-7a6d-4d5c-a3fe-2f3078d5ca9a">

2023-11-06 18:35 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * @notice Invokes the `universalReceiver` function logic internally when receiving native tokens.
This is not a `@notice` tag, but documentation for developers. Suggesting adding this under the `@dev` tag.

2023-11-06 18:35 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Whenever the call is associated with native tokens, the function will delegate internally the handling of native tokens to the {universalReceiver} function passing `_TYPEID_LSP0_VALUE_RECEIVED
Also worth mentioning when receiving less than 4 bytes of data.

2023-11-06 18:35 UTC, CJ42 commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Whenever the call is associated with native tokens, the function will delegate internally the handling of native tokens to the {universalReceiver} function passing `_TYPEID_LSP0_VALUE_RECEIVED
> except when the native token will be sent directly to the extension.

This last sentence makes it hard to understand. The only exception according to the code is when:
- you receive some native tokens
-  you receive some data that is more than 4 bytes.

In this case, the associated LSP17 extension is called.

2023-11-06 20:52 UTC, YamenMerhi commented on contracts/LSP0ERC725Account/LSP0ERC725AccountCore.sol
> +     * Whenever the call is associated with native tokens, the function will delegate internally the handling of native tokens to the {universalReceiver} function passing `_TYPEID_LSP0_VALUE_RECEIVED
This is generic saying all the time when native token is associated (even when data is less than 4 bytes), the universalReceiver is invoked, unless the native token is being forwarded to the extension, but happy to add a suggestion if you have one
> Whenever the call is associated with native tokens, the function will delegate internally the handling of native tokens to the {universalReceiver} function passing `_TYPEID_LSP0_VALUE_RECEIVED` as typeId and the calldata as received data, except when the native token will be sent directly to the extension.

2023-11-07 08:13 UTC, CJ42 approved these changes

2023-11-07 08:14 UTC, merged