refactor!: change set/get TokenId function name in LSP8 and `LSP8TokenIdSchema` to `LSP8TokenIdFormat`
lukso-network/lsp-smart-contracts pull request #822
Opened 2023-12-05 15:37 UTC by YamenMerhi

# What does this PR introduce?

## ⚠️ BREAKING CHANGES
## ♻️ Refactor

- Change `LSP8TokenIdSchema` to `LSP8TokenIdFormat`
- Change set/getTokenIdData/Batch to `set/getData|Batch|ForTokenId`

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2023-12-05 16:06 UTC, b00ste approved these changes

2023-12-05 18:38 UTC, CJ42 requested changes
Added review comments

2023-12-05 18:38 UTC, CJ42 commented on constants.ts
> + * @see for details see: https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-8-IdentifiableDigitalAsset.md#lsp8tokenidformat
Super good catch 👌🏻

2023-12-05 18:38 UTC, CJ42 commented on contracts/LSP8IdentifiableDigitalAsset/ILSP8IdentifiableDigitalAsset.sol
>          bytes32[] memory tokenId,
All params for the batch functions should be plural as we agreed 

bytes32[] memory tokenIds

2023-12-05 18:47 UTC, CJ42 requested changes
We need to change the constant name in constants.ts

It is still called LSP8_TOKEN_ID_SCHEMA

2023-12-05 18:47 UTC, CJ42 commented on constants.ts
>  export const LSP8_TOKEN_ID_SCHEMA = {
The constant name needs to be changed too

2023-12-06 08:59 UTC, CJ42 approved these changes

2023-12-06 10:46 UTC, merged