build!: move LSP4 in its own package
lukso-network/lsp-smart-contracts pull request #855
Opened 2024-01-23 11:50 UTC by b00ste

# What does this PR introduce?

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2024-01-23 15:44 UTC, richtera approved these changes
Looks ok, but npx or npm i -g is not ideal. In many cases yarn turbo will work automatically if turbo is a dependency.

2024-01-23 15:44 UTC, richtera commented on packages/LSP4DigitalAssetMetadata/README.md
> +turbo build
You should not install turbo globally but rather as part of the package.json and then just create a script called turbo so you can call yarn turbo ... The reason is that if you rely on developers to install npm i -g turbo each developer will end up with a different version causing things to possibly work different or not.

2024-01-24 18:00 UTC, CJ42 requested changes
This PR is not complete.

- [x] LSP4 in the contracts folder needs to be removed
- [x] `"lsp4": "*" needs to be added at the root `package.json`
- [ ] all the Solidity import paths and other import paths needs to be updated

2024-01-26 13:06 UTC, richtera approved these changes

2024-01-26 15:17 UTC, CJ42 approved these changes

2024-01-26 16:27 UTC, merged