chore: export artifacts from each package
lukso-network/lsp-smart-contracts pull request #895
Opened 2024-02-29 15:41 UTC by b00ste

# What does this PR introduce?

## 📦 Build

Export artefacts in each package

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2024-02-29 15:41 UTC, Hugoo commented
Task linked: [DEV-10235 Setup artifacts per package](https://app.clickup.com/t/2645698/DEV-10235)

2024-02-29 15:59 UTC, CJ42 requested changes
Added review comments.

Maybe for each individual LSP package only (not the top level `@lukso/lsp-smart-contracts`, we could add the Typechain types of the contracts being included in the `artifacts`?
Typechain types are big if there are a lot, but for artifacts like the LSP6 Key Manager, it should be smaller no?

Let's try to see the package(s) size

2024-02-29 15:59 UTC, CJ42 commented on packages/lsp6-contracts/hardhat.config.ts
> +    contracts: ['LSP6KeyManager', 'LSP6KeyManagerInit'],
Suggest doing a bit like file below to make it look clean and consistent.

```
contracts: [
    'LSP6KeyManager', // Standard version
    'LSP6KeyManagerInit' // Proxy version
],
```

2024-02-29 15:59 UTC, CJ42 commented on packages/lsp7-contracts/hardhat.config.ts
Super 👌

2024-02-29 15:59 UTC, CJ42 commented on packages/lsp9-contracts/hardhat.config.ts
> +    contracts: ['LSP9Vault', 'LSP9VaultInit'],
Same as suggested above

2024-03-01 10:07 UTC, CJ42 approved these changes

2024-03-01 10:07 UTC, merged