feat!: add LSP11 package
lukso-network/lsp-smart-contracts pull request #918
Opened 2024-03-07 10:23 UTC by YamenMerhi

# What does this PR introduce?
## 🚀 Feature

- Adding a draft of LSP11

### PR Checklist

- [ ] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [ ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ ] Ran `npm run format` (prettier)
- [ ] Ran `npm run build`
- [ ] Ran `npm run test`

2024-03-07 12:54 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +    event GuardianAdded(address account, address guardian);
Would it make sense to index the "account" parameter? So we can filter the guardians being added/removed for a specific account?

2024-03-07 12:54 UTC, CJ42 commented on packages/lsp11-contracts/hardhat.config.ts
> +    contracts: [],
Need to include the contract in the artifact here

2024-03-07 12:54 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +    uint256 constant DEFAULT_RECOVERY_DELAY = 40 minutes;
Very nice! 👌🏻

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +     * @notice Allows a guardian to vote for an address to be recovered.
```suggestion
     * @notice Allows a guardian to vote for an address for a recovery process
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +    function voteForRecoverer(
Suggest renaming to:

```suggestion
    function voteForRecovery(
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +        uint256 recoveryDelay
As mentioned by @frozeman, this parameter is not well described for delay. Recovery delay should be mentioned that it is in seconds.

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +        address account,
Suggest for all functions to put `account` as first parameter.

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/ILSP11UniversalSocialRecovery.sol
> +    function commitPlainSecret(
```suggestion
    function commitToRecover(
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +    function commitPlainSecretRelayCall(
```suggestion
    function commitToRecoverRelayCall(
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +        // retreive current recovery counter
```suggestion
        // retrieve current recovery counter
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +        address recoverer,
```suggestion
        address votedAddress,
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +        bytes32 commitment,
```suggestion
        bytes32 secretHash,
```

2024-03-19 12:42 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11UniversalSocialRecovery.sol
> +        emit RecoveryProcessSuccessful(account, recoveryCounter, recoverer);
Suggest renaming event.

Also need to index the first 3.

```suggestion
        emit RecoverySuccessful(account, recoveryCounter, votedAddress, calldata);
```

2024-03-27 23:05 UTC, CJ42 requested changes
Added first round of review.

You also need to register the package in the `release-please-config.json` file.

https://github.com/lukso-network/lsp-smart-contracts/blob/f4def52c3a49798c3d821e795a7b464ce6b13ef4/release-please-config.json#L176-L202

2024-03-27 23:05 UTC, CJ42 commented on packages/lsp11-contracts/package.json
> +  "version": "0.0.1",
I guess?

```suggestion
  "version": "0.1.0",
```

Should it also be rc?

```suggestion
  "version": "0.1.0-rc.0",
```

2024-03-27 23:05 UTC, CJ42 commented on packages/lsp11-contracts/package.json
> +  "scripts": {
You also need to add the scripts for `build:types` and `package` to generate the artifacts that will be shipped

Like in this PR: https://github.com/lukso-network/lsp-smart-contracts/pull/936/files#diff-94e9962874063f2b7d749bd08ea5e0b9be4176ddda28eed4c95858a2abf52043
<img width="1313" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/6de36b4f-7389-4db7-89c4-d86713b88d8f">

2024-03-27 23:05 UTC, CJ42 commented on packages/lsp11-contracts/package.json
> +    "@lukso/lsp25-contracts": "*",
Need to specify the version now: 

```suggestion
    "@lukso/lsp25-contracts": "~0.15.0-rc.1",
```

2024-03-27 23:47 UTC, CJ42 reviewed
added 2nd round of review for the Solidity code

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +// Constants
missing line break here

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +import "./LSP11Constants.sol";
there are only 2 constants to import. I think a specific import syntax could be done here.

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +import "./LSP11Errors.sol";
Here since there are so many, the specific import syntax would be quite big, so maybe we could do:

```suggestion
import ./LSP11Errors.sol" as Errors;
```

And then reference like that:

```
revert Errors.NotAGuardian(...)
```

wdyt?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +    uint256 private constant _DEFAULT_RECOVERY_DELAY = 40 minutes;
would it make sense to show that as `public` for block explorers?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        /// @dev The keccak256 hash of the commitment.
Not sure if these should be above to be parsed. Based on Solidity docs:

<img width="897" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/b5e18288-d5ca-4b6b-a402-8f8616763404">

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        if (guardian != msg.sender)
I see the idea of differentiating between the caller, and the fact that it is not a guardian for a specific account, but I would say that can be combined into a single if statement for simplicity.

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +    function batchCalls(
We could create an abstract contract for this function maybe, since it used in multiple contracts now? But where would that live in the monorepo? 🤔

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        CommitmentInfo memory _commitment = _commitmentInfoOf[account][
Storage might be cheaper here, to not have to copy the whole struct in memory, if protocols interact with this function? Not fully sure.

```suggestion
        CommitmentInfo storage _commitment = _commitmentInfoOf[account][
```

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        _guardiansOf[account].add(newGuardian);
The internal `_add(...)` function from `EnumerableSet` already check through `contains`. So suggest just returning the boolean from this function and revert if it is `false`.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/dc44c9f1a4c3b10af99492eed84f83ed244203f6/contracts/utils/structs/EnumerableSet.sol#L65-L74

<img width="762" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/fe1ea3f1-49bc-4aac-9159-a6f718ce06de">

```solidity
bool guardianAdded = _guardiansOf[account].add(newGuardian);

if (!guardianAdded) {
    revert GuardianAlreadyExists(account, newGuardian);
}

emit GuardianAdded(account, newGuardian);
```

You could also make it as a "one-liner" inside the `if`, but I like it less.

```solidity
```solidity
if (!_guardiansOf[account].add(newGuardian)) {
    revert GuardianAlreadyExists(account, newGuardian);
}

emit GuardianAdded(account, newGuardian);
```
```

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        if (!_guardiansOf[account].contains(existingGuardian))
similar to previous case. Although arguable which error should come first. Still think it might make more sense to no beforehand if `GuardianNumberCannotGoBelowThreshold` is already reached, regardless which guardian you are trying to remove

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            _defaultRecoveryRemoved[account] = true;
what is the purpose of this specific mapping?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        uint256 previousRecoveryCounter = _recoveryCounterOf[account];
can be a one liner. Since this is a post increment operator, the value will be first assigned to the variable, then incremented. So line below can be deleted.

```suggestion
        uint256 previousRecoveryCounter = _recoveryCounterOf[account]++;
```

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            _guardiansVotedFor[account][accountRecoveryCounter][
Would be good if possible to rename the local variable `accountRecoveryCounter` (for instance to `recoveryCounter` or just `counter`, so that the statement are one liner and easier to read.

Like that ideally.

```solidity
            _guardiansVotedFor[account][counter][guardian] = guardianVotedAddress;
            _votesOfguardianVotedAddress[account][counter][guardianVotedAddress]++;
```

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            _guardiansVotedFor[account][accountRecoveryCounter][
This would be a good candidate for named parameter in mappings. But would increase minimum compiler version. If not a big deal, I would do it.

<img width="1131" alt="image" src="https://github.com/lukso-network/lsp-smart-contracts/assets/31145285/8c1919c5-cbe7-416f-969c-d15eac3581fe">

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        bytes32 _secretHash = _secretHashOf[account];
why leading underscore?

```suggestion
        bytes32 currentSecretHash = _secretHashOf[account];
```

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        bytes32 _secretHash = _secretHashOf[account];
or rather suggest changing the parameter name of the function to `commitedSecretHash`

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        // will rely on the hash
put this in previous comment line

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            bytes32 saltedHash = keccak256(abi.encode(account, secretHash));
encode or encode packed?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +                    60 >
what does `60` stands for here? Would that be better in a `constant` for clearer context?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        emit RecoveryProcessSuccessful(
wonder if not better to emit the event before the external call. To avoid out of order events

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/foundry/LSP11UniversalRecovery.t.sol
Wow very nice and extensive testing! 💪 

I just noticed that none of the testing functions have input parameters, so no fuzzing here occur. Would it make sense to fuzz some of the internal functionalities?

2024-03-27 23:47 UTC, CJ42 commented on packages/lsp11-contracts/foundry/LSP11UniversalRecovery.t.sol
> +        // vm.expectEmit(true, true, true, true);
should this be commented?

2024-04-02 22:54 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/ILSP11SocialRecovery.sol
> +    function getGuardiansThresholdOf(
larger discussion

2024-04-02 22:57 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +import "./LSP11Errors.sol";
I don't see the value in adding it

2024-04-02 22:59 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            _defaultRecoveryRemoved[account] = true;
Highlight whether the default recovery delay is set or not

2024-04-02 23:03 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +            bytes32 saltedHash = keccak256(abi.encode(account, secretHash));
No preference

2024-04-02 23:04 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11Constants.sol
> +uint256 constant LSP11_VERSION = 11;
Adding LSP25 to LSP11 caused me some confusion, not sure whether to have it 25 or 11.

2024-04-02 23:14 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        if (!_guardiansOf[account].contains(existingGuardian))
disagree, because the check of guardian going below the threshold is purely for safety and too opinionated and can be discarded by other implementations, the important check is to check whether the address you're trying to remove is a guardian or not, and then check whether the guardian number will go below the threshold

2024-04-02 23:15 UTC, YamenMerhi commented on packages/lsp11-contracts/contracts/LSP11SocialRecovery.sol
> +        if (guardian != msg.sender)
would rather keep it this way, with different errors, as even now its a bit confusing to understand, so I would imagine if combined it would be harder

2024-07-29 14:26 UTC, CJ42 approved these changes

2024-07-29 14:27 UTC, merged