feat: create and test `LSP26FollowingSystem`
lukso-network/lsp-smart-contracts pull request #961
Opened 2024-07-03 08:27 UTC by b00ste

# What does this PR introduce?

## 🚀 Feature

This PR introduces smart contracts for `LSP26FollowingSystem` with functionality and gas tests.
To check gas results check `packages/lsp26-contracts/gasCost.json`.

### PR Checklist

- [ x] Wrote Tests
- [ ] Wrote & Generated Documentation (readme/natspec/dodoc)
- [x ] Ran `npm run lint` && `npm run lint:solidity` (solhint)
- [ x] Ran `npm run format` (prettier)
- [ x] Ran `npm run build`
- [ x] Ran `npm run test`

2024-08-01 07:27 UTC, CJ42 requested changes
Nice new early stage standard! Added review comments

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/README.md
> +# LSP Package Template
Need to adjust the README

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/constants.ts
This file should either be deleted, or updated with the relevant useful constants (e.g: LSP26 interface ID, ERC725Y Data Keys, etc...)

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/ILSP26FollowingSystem.sol
> +    event Follow(address follower, address addr);
How about using the word `account` here? In a social media, we follow an _"account"_ (can be anything). This keyword seems fitting well imo

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/ILSP26FollowingSystem.sol
> +    /// @custom:events {Follow} event when following an address.
Let's put `custom` Natspec comments at the bottom after `param` and `return` natspec tags

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/ILSP26FollowingSystem.sol
> +        uint256 endIndex
Wouldn't it be better to name this parameter `length` and maybe adjust the function name to something that describes more a range or something like that?

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/Imports.sol
Why is this needed?

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26Constants.sol
> +bytes32 constant _TYPEID_LSP26_FOLLOW = 0x71e02f9f05bcd5816ec4f3134aa2e5a916669537ec6c77fe66ea595fabc2d51a;
Nice we should also:

- [ ] add these constants in the `constants.ts`
- [ ] add the interface ID of LSP26
- [ ] add any relevant ERC725Y Data Keys if any

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +// interafces
```suggestion
// interfaces
```

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +import {ILSP26FollowingSystem} from "./ILSP26FollowingSystem.sol";
Is it a **Follower** or **Following** system for the name?

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +    mapping(address => EnumerableSet.AddressSet) private _followingsOf;
Very clean and well organised section! 👌🏻 🦭

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        for (uint256 index = 0; index < addresses.length; index++) {
not sure but I think pre-increment is slightly cheaper in gas.

```suggestion
        for (uint256 index = 0; index < addresses.length; ++index) {
```

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        address[] memory followings = new address[](endIndex - startIndex);
This substraction `endIndex - startIndex` can be cached in a local variable

```solidity
uint256 sliceLength = endIndex - startIndex;
```

<img width="610" alt="image" src="https://github.com/user-attachments/assets/d13e9bbd-71a0-40c3-8bb7-d8472517f238">

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        address[] memory followings = new address[](endIndex - startIndex);
But if we go with changing the `endIndex` parameter to something more around length, this line I suggested above will not be necessary

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +            // returns (bytes memory data) {} catch {}
comment to be removed

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +            // solhint-disable no-empty-blocks
let's move this below above the `catch` line and use:

```suggestion
            // solhint-disable-next-line no-empty-blocks
```

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        emit Follow(msg.sender, addr);
Suggest emitting the event before the external call to LSP1. Otherwise, recursive / reentrant call for re-following other accounts will be emitted first and appear first in the event list, while they actually according to the flow occured second.

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +            // returns (bytes memory data) {} catch {}
Same comments as above

2024-08-01 07:27 UTC, CJ42 commented on packages/lsp26-contracts/hardhat.config.ts
> +      accounts: new Array(10_100).fill('').map(() => ({
Suggest using the static methods from ethers v6

https://docs.ethers.org/v6/api/wallet/#Wallet_createRandom

And then access the `privateKey` property

https://docs.ethers.org/v6/api/wallet/#BaseWallet-privateKey

2024-08-01 08:06 UTC, b00ste commented on packages/lsp26-contracts/contracts/ILSP26FollowingSystem.sol
> +    event Follow(address follower, address addr);
We decided to use a more abstract name, because account is too specific

2024-08-01 08:07 UTC, b00ste commented on packages/lsp26-contracts/contracts/Imports.sol
i need those contracts in the tests

2024-08-01 08:09 UTC, b00ste commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +import {ILSP26FollowingSystem} from "./ILSP26FollowingSystem.sol";
Following

2024-08-01 08:13 UTC, b00ste commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +            // solhint-disable no-empty-blocks
prettier makes it look awful if moved there

2024-08-01 08:15 UTC, b00ste commented on packages/lsp26-contracts/hardhat.config.ts
> +      accounts: new Array(10_100).fill('').map(() => ({
the problem with that is now all those random wallets need funding to be able to send transactions. In current case all the addresses are pre-loaded with native token

2024-08-01 14:14 UTC, b00ste commented on packages/lsp26-contracts/contracts/ILSP26FollowingSystem.sol
> +        uint256 endIndex
It was suggested before, but the decision was to stick with these names

2024-08-02 08:49 UTC, YamenMerhi approved these changes
Minor optimizations

2024-08-02 08:49 UTC, YamenMerhi commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        if (msg.sender == addr) {
Not relevant, as `LSP26CannotSelfFollow` check exist in `_follow`

2024-08-02 08:49 UTC, YamenMerhi commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        _followingsOf[msg.sender].add(addr);
To save on gas
```js
const isAdded = _followingsOf[msg.sender].add(addr);
if (!isAdded) {
    revert LSP26AlreadyFollowing(addr);
}

Instead of accessing it first as a precheck, and doing the check in the background of the `add` function (`add` function calls `contain` function aswell)
```

2024-08-02 08:49 UTC, YamenMerhi commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +        _followingsOf[msg.sender].remove(addr);
To save on gas
```js
const isRemoved = _followingsOf[msg.sender].remove(addr);
if (!isRemoved) {
    revert LSP26NotFollowing(addr);
}

Instead of accessing it first as a precheck, and doing the check in the background of the `remove` function (`remove` function calls `contain` function aswell)
```

2024-08-02 11:07 UTC, CJ42 commented on packages/lsp26-contracts/contracts/LSP26FollowingSystem.sol
> +            // solhint-disable no-empty-blocks
No just above the `catch` line. But not a big deal anyway

2024-08-08 09:35 UTC, CJ42 approved these changes

2024-08-09 11:40 UTC, closed without merging